### ISSUE TITLE
font-weight isn't set in scss/forms/_select.scss

### ISSUE THREAD

**Issue by monosize** [zurb/foundation-sites#10016]
If you change the `$input-font-weight`, there is no effect in select fields, because the font-weight isn't set:

It's missing  `font-weight: $input-font-weight;`

**Comment by IamManchanda** [comment]
`input-font-weight` is in https://github.com/zurb/foundation-sites/blob/develop/scss/forms/_text.scss
Not `_select.scss`. This is not intended to work on Select(till date).

**Comment by monosize** [comment]
It's working ( tested in Chrome, Firefox and Safari) 

![image](https://cloud.githubusercontent.com/assets/1583746/25886104/667c3ba8-355c-11e7-814a-c38d51b1b02b.png)

![image](https://cloud.githubusercontent.com/assets/1583746/25886139/8776b482-355c-11e7-8a05-ebf1dd84d33d.png)

**Comment by denisahac** [comment]
I think the `select` form element should have its `font-weight` property applied according to `input-font-weight` value, since it is technically a form element and to have the `font` properties be applied across form elements. 

Not just this specific property, any `font` declaration that are not present in a particular form element, but present on the other should get applied throughout.

Let me know what you guys think.

**Comment by kball** [comment]
I believe this was fixed in https://github.com/zurb/foundation-sites/pull/9681.

This was a part of a broader change, and so not likely to be backported to 6.3 series, but is in 6.4 (in fact, if you want to try it out early, we just packaged up the first release candidate. Check it out: https://github.com/zurb/foundation-sites/releases/tag/v6.4.0-rc1
