### ISSUE TITLE
Opening AJAX reveal modal by keyboard with data-open in link fails

### ISSUE THREAD

**Issue by xinspire** [zurb/foundation-sites#10019]
#### How to reproduce this bug:

1. Go here: https://codepen.io/rafibomb/pen/kXEwWq?editors=1010
2. Add `data-open="reveal1"` to the button tag.
3. Now click outside the button in the preview area, and press `Tab` on the keyboard so that the button gets the focus, and then press Enter to "click" the button.

#### What should happen:

The modal should pop up with "I'm loaded with Ajax!" and a picture, just like it would if the `data-open` attribute is not in there.

#### What happened instead:

The modal pops up with no content.   The content shows up if you use the mouse to click, but not when you click using the Enter key.  The reason lies in the block of code at line 151 of js/foundation.reveal.js.

#### Browser(s) and Device(s) tested on:

Chrome 58.0.3029.96 on Mac OS X 10.12.4.

I've tested with Foundation 6.3.1 and 6.2.3.

#### Test case link:

- [CodePen with the data-open attribute added, based off of article at http://zurb.com/university/lessons/ajaxing-dynamic-content-with-foundation](http://codepen.io/anon/pen/Njybdd?editors=1010)

**Comment by Owlbertz** [comment]
Hi @xinspire, thank you for that detailed issue.

I also think that the [keydown listener](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.reveal.js#L151-L159) here is causing the AJAX click handler to not fire.

A possible workaround until this is patched would be to unbind this specific listener using
```js
$('#trigger-reveal').unbind('keydown.zf.reveal');
```

**Comment by xinspire** [comment]
Thanks!

**Comment by Owlbertz** [comment]
Hi again @xinspire,
I just notices something while attempting to fix this issue.
As you do manually open the Reveal in your AJAX callback, you could easily just remoe the `data-open` attribute from your button. This way the listener will not behave the wrong way and interrupt the event propagation.

**Comment by xinspire** [comment]
Ah, yes.  That was my initially solution before you commented, but wasn't sure if it was considered "hacky."  Does that mean that data-open doesn't really serve a purpose when reveal is used in AJAX mode?

**Comment by Owlbertz** [comment]
I guess with the current implementation you are correct as the event listener interfere. But even if it would work out as expected, I think for most use cases I'd recommend not opening the Reveal via `data-open` but instead manually as you did. Otherwise the modal would flash with empty content, whereas using your code it will wait for the AJAX to complete before opening.

I would say my first purposed solution would be considered more hacky than my second one.

However, am going to remove the lines you pointed out from the code as they do nothing helpful. The Reveal should just trigger whenever the anchor is triggered. As that is the case for buttons when pressing space or enter, there is no need to have a special handling for those buttons.

**Comment by xinspire** [comment]
Sounds good.  Thank you!

**Comment by IamManchanda** [comment]
@Owlbertz Shall we close this one ??

**Comment by Owlbertz** [comment]
Yeah, I think so. If there are any further issues, please re-open this one @xinspire.
