### ISSUE TITLE
More helpers

### ISSUE THREAD

**Issue by drnkwati** [zurb/foundation-sites#10045]
Sometimes simples tasks such as removing borders around containers like callouts, cards etc is really a pain. 
Can borders be moved to a separate mixin and only added to containers when necessary?
Or a helper class such as no-border be provided for removing borders on any container

**Comment by Deckluhm** [comment]
Because classes like `.no-border` aren't semantic, it goes against CSS good practices (and for that reason, we don't want this kind of stuff in the core framework).

That said, if you want that kind of "helpers" for prototyping only (I don't do prototyping but I understand why this kind of classes can be really helpful for quick prototyping), you may want to read that issue about adding separate prototyping features in the framework: https://github.com/zurb/foundation-sites/issues/9736

**Comment by IamManchanda** [comment]
Yes and i might add that there is a PR too #9738 (Disabled by default, not harming the purists)
But then, i didn't add a `no-border` class so i am now thinking about it!
