### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by jt4000** [zurb/foundation-sites#10095]
Hello, I have some general questions regarding foundation...

1. Is foundation-sites the same as bootstrap? Any differences?
2. Is there any example or prototype that I can test a website using foundation sites?

Thank you!

**Comment by lspoor** [comment]
A simple read of the documentation would explain everything you need to know.

**Comment by Deckluhm** [comment]
> Is foundation-sites the same as bootstrap? Any differences?

They are both open-source, highly maintained front-end frameworks but the philosophy is different.

- Foundation main goal is to help you build the structure/foundations (as the name suggests ;)) of your project, providing a super simple and easy to customize design (using Sass or simple CSS) that makes it easy to write your own
- Bootstrap default design is less neutral (which can be a pro or con depending on what you try to achieve) but they also embraced customization based on Sass (I stopped using Bootstrap years ago so I'm not super up-to-date with everything Bootstrap related)

Basically they do/offer the same things but with a slightly different approach.

I personally prefer Foundation documentation (even more since the fresh new docs revamping: http://zurb.com/article/1470/the-new-foundation-docs-learn-your-way) which I find cleaner, easier to navigate, more organized and complete.

You may also want to take a look at [Building Blocks](http://foundation.zurb.com/building-blocks) which is a set of reusable components built on Foundation created by the community. It's also super new but there is already lot of components which can be helpful while building your project.

> Is there any example or prototype that I can test a website using foundation sites?

This may be what you are looking for: http://foundation.zurb.com/templates.html

If you want to see real examples of websites built using Foundation, you should check these links:
- http://zurb.com/responsive
- http://foundation.zurb.com/showcase/brands

**Comment by lspoor** [comment]
Following on from Deckluhm, a big difference between the two at the moment is Flexbox too. Bootstrap 4 (currently in development) will support it but as of now Bootstrap is without.

I myself couldn't not use Flexbox now.

**Comment by JeremyEnglert** [comment]
Great answers everyone! I'm going to close out this issue for the time being. But feel free to continue the discussion.
