### ISSUE TITLE
y-grid margin-gutters bad reset

### ISSUE THREAD

**Issue by kball** [zurb/foundation-sites#10152]
As highlighted in https://github.com/zurb/foundation-sites/issues/10141#issuecomment-306924371 the `.y-grid` with margin-gutters is still getting negative margin on left and right...

I think this can be taken care of as a part of the margin/padding gutter changes we've been talking about @brettsmason - `.grid-margin-x` and `.grid-margin-y` should be responsible for those negative margins, regardless of the orientation of the grid itself..

**Comment by brettsmason** [comment]
@kball So I think what I've gathered is we want to do:

`.grid-margin/padding-x > .cell` and `.grid-margin/padding-y > .cell` - these classes would purely apply margin/padding to the cells. This would also apply negative margins to the grid in that axis (for margin grids anyway) so that the cells line up flush.

Then `.grid-x`/`.grid-y` would just be responsible for setting the width or height of the `.cell`, as well at the `flex-direction` - is that correct? I'll take a pass at this tonight.

@oxyc Does the above sound correct for your use case?

**Comment by oxyc** [comment]
Sounds like that would solve it yes. 👍 Great work on this new grid btw, it'll solve a lot of the earlier pains I lets me drop 3-4 grid helpers I don't need anymore.

**Comment by brettsmason** [comment]
@oxyc I've put together a PR to sort this out. If you get a chance could you try it out and see if it works for you? https://github.com/zurb/foundation-sites/pull/10157
Don't worry if not 😄

**Comment by brettsmason** [comment]
Closing as this is now included 😄
