### ISSUE TITLE
$grid-column-gutter return isn't a valid CSS value

### ISSUE THREAD

**Issue by stephane-r** [zurb/foundation-sites#10282]
I community,

I would like compile scss source of latest Foundation 6.4.0, but i've this error :

```
$grid-column-gutter: (
                    ^
      (small: 20px, medium: 30px) isn't a valid CSS value.
      /node_modules/foundation-sites/scss/grid/_grid.scss (line 20, column 22)
```

My **_settings.scss** :

```
@import '~foundation-sites/scss/foundation';
@import '~motion-ui/src/motion-ui';
@import 'settings/settings';

@include foundation-global-styles;
@include foundation-grid;
@include foundation-xy-grid-classes;
@include foundation-flex-grid;
@include foundation-typography;
@include foundation-forms;
@include foundation-button;
@include foundation-accordion;
@include foundation-accordion-menu;
@include foundation-badge;
@include foundation-breadcrumbs;
@include foundation-button-group;
@include foundation-callout;
@include foundation-card;
@include foundation-close-button;
@include foundation-menu;
@include foundation-menu-icon;
@include foundation-drilldown-menu;
@include foundation-dropdown;
@include foundation-dropdown-menu;
@include foundation-responsive-embed;
@include foundation-label;
@include foundation-media-object;
@include foundation-off-canvas;
@include foundation-orbit;
@include foundation-pagination;
@include foundation-progress-bar;
@include foundation-slider;
@include foundation-sticky;
@include foundation-reveal;
@include foundation-switch;
@include foundation-table;
@include foundation-tabs;
@include foundation-thumbnail;
@include foundation-title-bar;
@include foundation-tooltip;
@include foundation-top-bar;
@include foundation-visibility-classes;
@include foundation-float-classes;
@include foundation-flex-classes;
// @include foundation-prototype-classes;

@include motion-ui-transitions;
@include motion-ui-animations;
```

#### Foundation Version
6.4.0

#### Node version
8

Anyone have idea ? I've been import util module :

`@import '~foundation-sites/scss/util/util';`

Thank you !

**Comment by kball** [comment]
Hi @stephane-r - can you post more of a backtrace? It looks a little like somewhere the `$grid-column-gutter` variable is being used directly for a CSS value rather than as an input to a mixin (which is the typical behavior within the framework), but the backtrace posted shows only the place where the variable declared

**Comment by AScottJohnson** [comment]
@kball – I'm having a similar issue and getting the following error thrown for my Foundation settings file:

```command
Error in plugin 'sass'
Message:
    src/styles/vendors/foundation/_foundation.settings.scss
Error: (small: 20px, medium: 30px) isn't a valid CSS value.
        on line 123 of src/styles/vendors/foundation/_foundation.settings.scss
>>   small: 20px,
   --^
```

If I comment out `$grid-column-gutter` in my settings file then the error is thrown for `node_modules/foundation-sites/scss/grid/_grid.scss`.
```command
Error in plugin 'sass'
Message:
    node_modules/foundation-sites/scss/grid/_grid.scss
Error: (small: 20px, medium: 30px) isn't a valid CSS value.
        on line 21 of node_modules/foundation-sites/scss/grid/_grid.scss
>>   small: 20px,
   --^
```

I thought it might have been an issue with `gulp-sass` because I was using the latest version (v3.1.0) and noticed Zurb was using v2.1.0. But after downgrading, I was still having the issue.

Not sure how to fix this. And how do I go about doing a backtrace to help provide you more information? `gulp taskname --trace`?

--

**Foundation**: v6.4.3
**Node**: v8.4.0

**gulp**: ^3.9.1
**gulp-sass**: ^3.1.0

**Comment by kball** [comment]
@scttjhnsn is this on a bare/new project? Or are you using grid mixins or the variable somewhere in your own scss? What this looks like is something is trying to use that variable directly in a css property rather than using it to generate gutters as the grid mixins do, but I'm not sure where that use is coming from... the error as I'm seeing it is just showing where the var is defined.

Is it possible to give me access to see your project to help debug?

**Comment by ideaLEVER** [comment]
Oh geeze... this is going to make upgrade our sites from 6.0.x very painful.

**Comment by lineardevon** [comment]
> Or are you using grid mixins or the variable somewhere in your own scss? What this looks like is something is trying to use that variable directly in a css property rather than using it to generate gutters as the grid mixins do

In case it helps anyone else.. I was getting the same error message after upgrading node-sass. @kball was right on the money. Turns out there was an old reference to $grid-column-gutter in one of my own scss files. Removing the reference fixed the issue.

**Comment by ideaLEVER** [comment]
I haven't been following the development of this, but using the $grid-column-gutter var was a great way to keep consistent spacing throughout a project. And I don't really see why this needed to break backward compatibility:

$grid-column-gutters: (
    small: 5px,
    medium: 10px,
    large: 15px,
);
$grid-column-gutter: map-get($grid-column-gutters,large);

**Comment by DanielRuf** [comment]
`$grid-column-gutter` is still in the settings file (6.4.3/4).

**Comment by ideaLEVER** [comment]
Yes, but it's been turned into a map. Which means it cannot be called directly. So if, say, you've built several templates and widgets that are re-used in client projects over and over and over again, that use a semantic grid and call these variables, you are barred from using 6.4.0 and higher until you go through and fix all of these new incompatibilities. This could have been avoided by implementing the solution I suggested above. We have already done all those updates, but it's a lot of wasted time that clients were not paying us for, that didn't need to be spent. 

My proposed solution would have been completely backwards-compatible with old code (and still behaved exactly as expected), yet also allowed for responsive-gutter upgrades if/as required/desired. A much better solution in my opinion.

**Comment by DanielRuf** [comment]
Closing for now. Feel free to reopen if this occurs with new projects.
