### ISSUE TITLE
Updating jQuery Dependency to 3.x Should Cause Major Version Update

### ISSUE THREAD

**Issue by someyoungideas** [zurb/foundation-sites#10295]
In the recent `v6.4.0` release all dependencies to jQuery were bumped from `>=2.2.0` to `>=3.0.0`. Seeing that this is a MAJOR version release in a dependency I was wondering why Foundation's release was not considered a MAJOR version release?

This change in Foundation caused some breaking changes in our site once the jQuery version updated with this release. This is more looking for thoughts why or why not Foundation's version was changed to match the MAJOR version change in jQuery.

**Comment by IamManchanda** [comment]
cc @kball

**Comment by QWp6t** [comment]
Does Foundation use any of jQuery 3's API that isn't available in 1 or 2? If not, then it's API-compatible and therefore doesn't require a major version update, but Zurb should consider changing dependency to `>= 1.12` or something similar.

Bootstrap went through a similar issue here: https://github.com/twbs/bootstrap/pull/17494

In that PR, they raised dependency to 2.x. WordPress developers pointed out that WordPress ships with jQuery 1.x still, and the move by Bootstrap would alienate those developers. (Love it or hate it, WordPress is huge in our industry, and thus winds up shaping the way things progress.) Since Bootstrap doesn't actually use any jQuery APIs that are specific to version 2, then there's no reason for that version to be a hard dependency.

Bootstrap ultimately reversed their move here: https://github.com/twbs/bootstrap/pull/18267

If Foundation does in fact make use of APIs that aren't available 1.x, then yeah, that should warrant a major version update.

**Comment by kball** [comment]
This is a good point... we do in fact work with older versions of jquery (there are plenty of folks using foundation with Wordpress)... however we strongly encourage later versions.  Perhaps the right solution would be to reduce the minimum value in the framework while having the templates consistently push for latest and greatest? I'm by no means a dependency expert - would love other voices here @zurb/yetinauts 

With regards to the major/minor question, we've explicitly avoided semver as it seems to create far more confusion for humans than it solves for machines.

**Comment by DanielRuf** [comment]
Imo we should stop using jQuery in v7.

The change is ok and you can still install and pin jQuery 2.

**Comment by colin-marshall** [comment]
@someyoungideas, as @DanielRuf mentioned, you should be able to pin jQuery to v2 in `package.json` and still use it with Foundation with no problems. This should alleviate your breaking changes, but I'm guessing you already took care of that seeing as how this is 9 months later. I'm closing this out, but feel free to reopen if you feel I have done so in error. Thanks!
