### ISSUE TITLE
Class small-centered not working v6.4.1

### ISSUE THREAD

**Issue by AleeBadara** [zurb/foundation-sites#10316]
this code below used to work when i was using foundation-sites 6.3.1. the column is well centered with the class **small-centered**.

    <div class="row">
      <div class="columns medium-6 large-4 small-centered">
       <p>Test</p>
      </div>
    </div>

But since i update to version 6.4.1, the column is no longer centered. the class **small-centered** has no effect. 
Am i missing something?

**Comment by brettsmason** [comment]
@AleeBadara Seems to be working OK for me with a blank CodePen: https://codepen.io/brettsmason/pen/Ogvwwq

The grid was changed to use XY grid by default from 6.4 so the float and old flex grid are not the defaults. How are you using Foundation? Is using Sass you need to [make sure you set the correct grid includes](http://foundation.zurb.com/sites/docs/sass.html#adjusting-css-output).

**Comment by AleeBadara** [comment]
Thank you @brettsmason. I use npm to install foundation-sites and webpack to bundle all my files. I think it's me. I'm missing something. I'll have a look.

**Comment by BondoS** [comment]
@AleeBadara  I'm facing the same issue, have you fix it?

**Comment by brettsmason** [comment]
@AleeBadara @BondoS The `small-centered` class is [part of the float grid](http://foundation.zurb.com/sites/docs/grid.html#centered-columns) which is no longer the default grid.

By default with 6.4 the variable `$global-flexbox` is set to `true`, which will set it to use the xy grid (or legacy flex grid). In order to use the float grid set this to `false` (assuming you are using `@include foundation-everything`).  [See here](http://foundation.zurb.com/sites/docs/sass.html#adjusting-css-output) for more details on enabling/disabling certain components too. Alternatively if you are using precompiled CSS then make sure you use `foundation-float.css` as this has the class you want in it.

Does that help?

**Comment by AleeBadara** [comment]
@BondoS if you are using the foundation.css file, you also have to import the foundation-float.css as @brettsmason said. 
here is my code. A React-Webpack project:
`require('style-loader!css-loader!foundation-sites/dist/css/foundation.min.css');`
`require('style-loader!css-loader!foundation-sites/dist/css/foundation-float.min.css');`

Thanks to you 2.

**Comment by brettsmason** [comment]
Going to close this as this should be solved, but please reopen if you are still having issues.
