### ISSUE TITLE
[Off-canvas] Docs - open nested off-canvas push does overlap instead.

### ISSUE THREAD

**Issue by rafibomb** [zurb/foundation-sites#10328]
Click example here: 
http://foundation.zurb.com/sites/docs/off-canvas.html#nested-off-canvas
open nested off-canvas push

Overlaps instead of pushes

**Comment by brettsmason** [comment]
@rafibomb This is a docs not being clear enough issue. If you see the callout in that section it mentions nested is only possible for overlap (if set to push it will force it to a push). [See here](https://github.com/zurb/foundation-sites/pull/10003#issuecomment-307249884) for details on why this was done.

So the functionality is right, but the docs example is possibly misleading. cc @kball

**Comment by kball** [comment]
@sassninja would you be able to take a pass on improving the docs here?

**Comment by SassNinja** [comment]
@kball I'm not sure how to explain it better: there's a warning callout in the docs and I've mentioned it in the opened off-canvas
`Since push transition is currently not possible for nested elements, I'm forced to use overlap transition.`

@rafibomb since you haven't noticed this note at first sight, maybe you can let me know what part of the docs you usually focus? Would a another position/color of the callout help?

**Comment by DanielRuf** [comment]
@SassNinja any idea what we can do here? Do you plan to improve this part?

**Comment by SassNinja** [comment]
The plan was to wait for @rafibomb to explain more detailed what he was confusing him ;)

However I've just made PR that updates the off-canvas docs https://github.com/zurb/foundation-sites/pull/10964
This should make it much clearer and fix this issue.
