### ISSUE TITLE
Menu invisible in iPad and iPhone

### ISSUE THREAD

**Issue by rabimx** [zurb/foundation-sites#10354]
I made a mockup of a site that I'm designing. The navigation works fine everywhere... except in iPad and iPhone. The issue is not reproducible in a browser emulator. I don't have any idea of what is happens.
This is the url of the mockup:
http://purosulloa.com/colimafutbol
I'm not sure if is a Foundation's bug or an ios issue. Any help will be appreciated.

**Comment by rafibomb** [comment]
I haven't been able to reproduce this on any of my sites.

The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
