### ISSUE TITLE
Can XY grid support arbitrary dimension cells?

### ISSUE THREAD

**Issue by brgrz** [zurb/foundation-sites#10376]
CSS grid has an important, probably the most far reaching feature: in a 4 by 4 grid we can define a cel that spans for instance [2,2] and [3,3]. While lookingat Foundation's new XY grid I couldn't find out if this was possible but I'm leaning more towards the answer that it wasn't. It seems to me only the grid construction part is covered but cell selection is not. This would mean XY is not a complete CSS grid replacement as advertised. Am I right or can I actually select (how?) an arbitrary item from adjacent cells in XY grid?

**Comment by IamManchanda** [comment]
The current XY Grid is not **CSS Grid**

Current XY Grid (Flexbox) => Horizontal or Vertical
CSS Grid =>  Horizontal **and/or** Vertical

See => #10134 

---

We plan to use CSS Grid in F7... but maybe not the way how we have used Grid in the past or using currently 
See => https://github.com/zurb/foundation-sites/issues/10134#issuecomment-313449506

---

Also @brgrz we like to keep one thread per feature request 
so can you join forces in there instead of here ??

**Comment by IamManchanda** [comment]
Hey thanks for your comment... I am gonna close this 
Hope you don't mind :)
