### ISSUE TITLE
Accessibility of dropdown toggling in Foundation 5 vs 6

### ISSUE THREAD

**Issue by daneah** [zurb/foundation-sites#10391]
Accessibility of toggling dropdowns using keyboard navigation seems to have changed from Foundation 5 to Foundation 6. It was suggested that we direct accessibility issues to the attention of @Owlbertz. Thanks for your time and help!

#### How to reproduce this bug:

Construct a dropdown per Foundation 6's [Dropdown doc](http://foundation.zurb.com/sites/docs/dropdown.html) (explicitly shown below).

#### What should happen:

Using keyboard navigation, TABing to the trigger element and hitting Enter opens the dropdown content. TABing back to the trigger element while the content is open and hitting Enter again should close the content.

#### What happened instead:

Attempting to close already-opened dropdown content by TABing to the trigger element and hitting Enter sends focus to the open content, which _remains_ open.

#### Browser(s) and Device(s) tested on:

macOS + latest Chrome

#### Foundation Version(s) you are using:

Foundation 6.4.1

#### Test case link:

CodePen seems to be having issues saving and forking at the moment. The simplest test case with Foundation JS + CSS presumed is:

```html
<a href="#" data-toggle="my-dropdown">Open Dropdown</a>

<div id="my-dropdown" class="dropdown-pane" data-dropdown>
    Hello
</div>
```

**Comment by Owlbertz** [comment]
Hi @daneah, thank you for reporting this.
However, I am not sure if this is by design or a bug, as `ESC` can be used to close the Dropdown.

When checking the WAI-ARIA authoring practices, imo "Alert" seems to be the equivalent for Foundation's Dropdowns, which also do not have the behavior you expect (see [this example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/alert/index.html)).
Other resources work completely different. For example [this page](http://ianmcburnie.github.io/mindpatterns/disclosure/flyout/) auto-closes the panels automatically once they lost focus.

So while it seems to be not 100% standardized, I agree that Foundation's Dropdowns should close on a second `ENTER`-click as this would follow the mouse interactions.

**Comment by daneah** [comment]
@Owlbertz Thanks for the comparisons! I had an inkling it wasn't an officially-outlined behavior standard but noticed it differed between v5 and v6, so that's what mainly I wanted to call to attention. I think for now we can work around this by adding a close button or some other obvious method of closing, with `ESC` being a pretty normal workflow as well. Look forward to seeing this resolved! Let me know if I do anything further to be of help in the meantime.

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/GxBvwR

**Comment by DanielRuf** [comment]
But what about space?

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/xWJPVV

@Owlbertz is this even good to not focus the dropdown content? Wha about screenreaders and so on?
