### ISSUE TITLE
Foundation XYGrid Auto Cells Issue

### ISSUE THREAD

**Issue by wgstjf** [zurb/foundation-sites#10440]
Hi guys,

Using 6.4.1 and wanted to layout some logos in a horizontal grid using 'auto' cells.  I am struggling to get this to work as I expected.

The 'auto' cells contain images and the images will have defined widths.  What seems to be happening is that the cells are ignoring the width of their contents and not expanding to fit (or wrapping when they reach the end of the 'row').  Instead they keep shrinking to enable all the cells to fit on one row.

Here is a codepen that I have created showing the issue.  We are just begginning to get our heads around the new XYGrid so it is perfectly possible that we have overlooked something but would appreciate any help you might be able to offer on this.

https://codepen.io/indigoconcept/pen/PjMPbp/

Cheers,

Will

**Comment by brettsmason** [comment]
@wgstjf Hey Will thanks for reaching out.

From what I understand from your description and your CodePen, I think you actually want to use the `shrink` class rather than `auto`. Auto fits all available cells to fill a row, were as `shrink` will make the cell the smallest width possible whilst retaining content width.

Can you try it and let me know if that's what you are looking for?

**Comment by wgstjf** [comment]
Doh!!  You're so right...can't for the life of me figure out why is was fixating on 'auto'.  

Thanks for putting me straight, and so quickly too :-)

**Comment by brettsmason** [comment]
@wgstjf No problem glad that works 😄 
Closing this, but if you get any other XY grid (or anything else) feel free to open another issue.
