### ISSUE TITLE
Documentation on webpack integration

### ISSUE THREAD

**Issue by tyteen4a03** [zurb/foundation-sites#10516]
I can't find this anywhere. It would be nice if there is a page on the docs specifying how webpack integration works, and possibly examples with Angular/React/Vue integration as well.

**Comment by Knight-Yoshi** [comment]
Integrating into Webpack itself is easy enough, though their documentation about it definitely needs some improvements for Webpack integration.

Since Foundation's file names already use a namespace structure you can set resolve path

webpack.config.js
```
var path = require('path'); // Node 'path' object

{
    resolve : {
        modules : [
            path.resolve ('node_modules/foundation-sites/js'),
        ],
    },
}
```

JS file
```
import { Tabs } from 'foundation.tabs';

var t = new Tabs($element, {...});
```

I haven't tried integrating it with React, yet. I hear tell that they plan to make it easier to integrate with other libraries in Foundation 7.

**Comment by tyteen4a03** [comment]
In angular, simply importing foundation as usual seems to work.

For SCSS in Angular CLI, I used `@import "~foundation-sites/scss/foundation";` to import foundation CSSes.

**Comment by colinmackinlay** [comment]
Some more documentation would definitely be helpful. I use other jquery scripts e.g tablesorter and typeahead but they don't always play nicely. Tablesorte can be imported ok but the standard typeahead doesn't (it can't see the webpacked version) and I end up impoting jquery again as a quick and very dirty fix so that I can use 6.4.x. I just need a few clues to work out what to do as webpack is completely new to me!

**Comment by kball** [comment]
@Knight-Yoshi would you be up to take a pass on improving the documentation? I'd happily accept a PR in this area.

**Comment by Knight-Yoshi** [comment]
@kball I can give it a shot. Where should I start?

**Comment by IamManchanda** [comment]
@Knight-Yoshi I would say... there should be a separate page for webpack 
See for example => https://getbootstrap.com/docs/4.0/getting-started/webpack/

**Comment by Knight-Yoshi** [comment]
@IamManchanda I just create a new markdown file in the docs/pages directory?

**Comment by IamManchanda** [comment]
@Knight-Yoshi You need to create a PR to request the changes to our main docs!
https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by IamManchanda** [comment]
Ping me up once you are up with a PR (Pull Request)

**Comment by erutan** [comment]
Some information on how to include only certain js components of Foundation like with the old config.yml would be nice.

**Comment by JeremyEnglert** [comment]
https://github.com/zurb/foundation-sites/pull/10925

Closing.
