### ISSUE TITLE
Scrolling Issues with .cell-block-x

### ISSUE THREAD

**Issue by Knight-Yoshi** [zurb/foundation-sites#10525]
I on one of the pages I'm working on, I have some deeply nested grids. To reduce the HTML while I make it more semantic, I have cells that are also grids. One of which is a `.cell.small-12.cell-block-container.grid-x` that has a child, `cell.cell-block-x.grid-x`.

In Firefox the `.cell-block-x` element scrolls. In Safari (and mobile), Chrome, and Opera it does not.
I made code pen that demonstrates the issue I'm having, the container at the bottom  with the form fields should scroll: https://codepen.io/KnightYoshi/pen/RZpOaP
The elements are styled by my classes, but I have the Foundation classes on there to make it more obvious about what styles each element has applied.

**Comment by irawel** [comment]
I believe there is no .cell-block-x class but .cell-block and .cell-block-y classes.

**Comment by brettsmason** [comment]
@Knight-Yoshi The `cell-block` behaviour actually requires quite a strict markup structure, primarily because of the differences in how browsers handle this.

I've taken your pen and created a new one with just basic markup to create what I think you want. Take a look here: https://codepen.io/brettsmason/pen/qXmrqw

Is that the correct behaviour?

Also @irawel is correct - its `cell-block` or `cell-block-y` just in case that causes any confusion.

**Comment by Knight-Yoshi** [comment]
@irawel You're right, but the class name wasn't the issue since I'm using the Sass mixins to make my HTML more semantic.

@brettsmason Thanks for that. I had to make some changes to the HTML to get it to where I need it, but you pointed me in the right direction!
