### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by asecondwill** [zurb/foundation-sites#10537]
#### How to reproduce this bug:

1. http://foundation.zurb.com/sites/docs/installation.html
2. Select manual
3. git clone https://github.com/zurb/foundation-sites-template
4. cd projectname
5. npm install
6. npm watch

#### What should happen:
compiles foundations sass?

#### What happened instead:
Error in plugin 'sass'
Message:
    scss/_settings.scss
Error: File to import not found or unreadable: util/util
       Parent style sheet: /Sites/www/hi/wwwroot/themes/foundation-sites-template/scss/_settings.scss
        on line 63 of scss/_settings.scss
>> @import 'util/util';

#### Browser(s) and Device(s) tested on:
na

#### Foundation Version(s) you are using:
6.4
#### Test case link:
na

**Comment by asecondwill** [comment]
i'm on osx sierra btw

**Comment by asecondwill** [comment]
node: v8.1.3
npm: 5.0.3

**Comment by asecondwill** [comment]
looking in the dir, there is a bower.json file.  i'm never quite clear why we need bower when npm includes things? anyway - i tried a bower install.. and now it works.  just a couple of deprecation warnings.

**Comment by SassNinja** [comment]
@asecondwill I was able to reproduce the issue. As you've already spotted `bower install` must be executed after `npm install` (the foundation-cli does the same)

The docs should definitely mention that. 
Would you like to make a PR for this?

To answer your question why using bower:
Compared to npm bower makes sure you've got only one version of a package instead of several ones (e.g. only jQuery 2 instead of jQuery 2 and jQuery 3). Thus it's more suitable for web assets where size matters.

**Comment by asecondwill** [comment]
ok, thanks

where would i make a pull request for:
http://foundation.zurb.com/sites/docs/installation.html 

?

**Comment by SassNinja** [comment]
what do you mean with 'where'?

in your fork of the [foundation repo](https://github.com/zurb/foundation-sites) you have to edit the appropriate file (in a feature branch) `/docs/pages/installation.md`

After that you can test your changes by running `gulp` in terminal and make a [PR](https://github.com/zurb/foundation-sites/pulls) if it looks good.

**Comment by asecondwill** [comment]
thats what i meant,  which repo / where in the repo.  thanks.

**Comment by RiZKiT** [comment]
I have the same problem with a different setup, when I use `@import "foundation-sites/scss/settings/settings"`. I think `@import "util/util";` in that file should be `@import "../util/util";` regardless of the setup, because it is in another directory.

My current and [the suggested solution](https://github.com/zurb/foundation-sites/blob/develop/meteor-README.md#3-overwrite-foundation-settings) is to copy `_settings.scss` file into your own project. Then adjust the path to util like `@import "foundation-sites/scss/util/util"`. You can remove the lines from the settings files you don't want, because every variable is already defined in another file.

**Comment by DanielRuf** [comment]
I do not see any watch task there in https://github.com/zurb/foundation-sites-template. The watch task normally does not directly compile.

**Comment by DanielRuf** [comment]
> I have the same problem with a different setup, when I use @import "foundation-sites/scss/settings/settings". I think @import "util/util"; in that file should be @import "../util/util"; regardless of the setup, because it is in another directory.

Right.

**Comment by ncoden** [comment]
This is an old issue (#8293)

`settings/_settings.scss`should not be imported by the Foundation sources but copied into your project repo, like `foundation.scss`. See https://foundation.zurb.com/sites/docs/sass.html#the-settings-file
