### ISSUE TITLE
Feature Request - Sematic Versioning ( Originally Depreciation issue - Settings )

### ISSUE THREAD

**Issue by isapir** [zurb/foundation-sites#10556]
After upgrading from foundation-sites 6.4.1 to foundation-sites 6.4.3 I get the following warnings when compiling Sass:

>WARNING: $offcanvas-size is deprecated and not used anymore! Please update your settings and use the map $offcanvas-sizes instead
Backtrace:
        lib/foundation-sites-6.4.3/scss/components/_off-canvas.scss:78, in mixin `off-canvas-basics`
        lib/foundation-sites-6.4.3/scss/components/_off-canvas.scss:439, in mixin `foundation-off-canvas`
        scss/app.scss:31

>WARNING: $offcanvas-vertical-size is deprecated and not used anymore! Please update your settings and use the map $offcanvas-vertical-sizes instead
Backtrace:
        lib/foundation-sites-6.4.3/scss/components/_off-canvas.scss:82, in mixin `off-canvas-basics`
        lib/foundation-sites-6.4.3/scss/components/_off-canvas.scss:439, in mixin `foundation-off-canvas`
        scss/app.scss:31

(Added after title change) I would argue in favor of Semantic Versioning: http://semver.org/ which recommends that a patch version should not introduce any non-backwards compatible changes.

That will allow users to know if they can do a simple update by just copying files, or if an update requires more attention to backwards-incompatible issues.

**Comment by Renkas** [comment]
Did you read what's written there?

**Comment by IamManchanda** [comment]
@isapir Just replace the below code

```scss
$offcanvas-size: 250px !default;
$offcanvas-vertical-size: 250px !default;
```
to this below code in your settings file 

```scss
$offcanvas-sizes: (
  small: 250px,
);
$offcanvas-vertical-sizes: (
  small: 250px,
);
```

---

I am closing this but let me know if you are still facing the issue!

**Comment by isapir** [comment]
@Renkas I did, but I missed the part where the issue is in _my_ settings file rather than the foundation files because settings were not mentioned in the `Backtrace`.

@IamManchanda Thanks, I realize now that my `_settings.scss` was out of sync with the library since I updated the library and kept my previous settings file.

I would argue in favor of Semantic Versioning: http://semver.org/ which recommends that a patch version should not introduce any non-backwards compatible changes.

**Comment by IamManchanda** [comment]
Reopening on request of semantic versioning

**Comment by SassNinja** [comment]
@isapir there haven't been introduced any non backwards compatible changes.
What you see on gulping is a **warning** not an **error**.

I've added this to prompt the user to update his settings at an early stage instead of waiting until it has been removed and cause an actual error.
Right now the deprecated `$offcanvas-size` is still working and gets internally converted into the new `$offcanvas-sizes`.

I think it's not a backwards compatibility issue if you get only a warning.

**Comment by IamManchanda** [comment]
But the thing is we need to improve our settings the way we handle it!

**Comment by SassNinja** [comment]
@IamManchanda do you have anything specific in mind that you don't like regarding the current settings setup?

I think it's hardly possible to avoid the necessity of updating the custom settings file after a couple of releases. Personally I like the current setup nevertheless because it offers a fast & easy way to customize the components.

However, what probably might be a great help for many users is an interactive update guide. Some tool that asks for the foundation version in use and then shows all needed steps to update to the latest version.

**Comment by colin-marshall** [comment]
@SassNinja I like that idea. Something that we will definitely consider for updates in Version 7.
