### ISSUE TITLE
Row under Row always full-width

### ISSUE THREAD

**Issue by ashussen** [zurb/foundation-sites#10558]
```
  .row:not(.expanded) .row {
    max-width: none; }
```

I've got this code after I update to the latest Foundation version. 
I think it doesn't make sense, row not expanded should have the `$global-width` as max-width. Otherwise, there will be no difference between `row.expanded` and `row:not(.expanded)`.

I have the parent `.row` as full-width but child `.row` are expected to have `max-width: $global-width`. Now after that code is added, all my content became full-width.

The code I would see make sense are
```
  .row.expanded) .row {
    max-width: none; }
  .row:not(.expanded) .row {
    max-width: $global-width; }
```

I am not sure if this is a bug or just a feature, but this is annoying changes.

**Comment by kball** [comment]
I believe what this is trying to do is make the child row expand to fill the parent row, which should *already* be providing the container functionality at $global-width.

That said, there's been a lot of back and forth on this area of the code... the difficulty of navigating exactly what should make sense in various nested cases comes from the combination of the concept of a container and a row in the traditional foundation grid, and is one of the big reasons we separated those concepts in the new XY-grid.

Due to the above, going to close this as an issue, but if you have questions about how to get a particular behavior would be happy to help
