### ISSUE TITLE
.button-group color palette

### ISSUE THREAD

**Issue by repoles** [zurb/foundation-sites#10576]
In file `.button-group.scss`, line 210, iteration should be over $button-palette instead of $foundation-palette.

https://github.com/zurb/foundation-sites/blob/373344ecdcbd29c0c00a26d98e92dfb6d99f214c/scss/components/_button-group.scss#L210

**Comment by kball** [comment]
Good catch @repoles would you like to submit a PR for this?

**Comment by repoles** [comment]
Sure, @kball. Here you go. Thanks.

**Comment by IamManchanda** [comment]
@repoles Thanks a lot but please check my comment on the PR and create a new branch :)

**Comment by repoles** [comment]
@IamManchanda i tried, but:

```
➜ foundation-sites git:(hotfix/button-group-color-palette) git push origin HEAD 
Username for 'https://github.com': repoles
Password for 'https://repoles@github.com': 
remote: Permission to zurb/foundation-sites.git denied to repoles.
fatal: unable to access 'https://github.com/zurb/foundation-sites.git/': The requested URL returned error: 403
```

**Comment by IamManchanda** [comment]
@repoles Sorry for late reply... This seems fixed by other user

But, for your learning
You should replace `origin` with the remote name you added for your own forked PR `git@github.com:repoles/foundation-sites.git`

---

Normally if you create a PR for a repo that you don't have direct access, You should be doing

1. Fork that repo to your profile... In your case git@github.com:repoles/foundation-sites.git
(This way remote gets set to origin)

2. Now set Main repo to `upstream`
=> `git remote add git@github.com:zurb/foundation-sites.git`

3. Now if you do `git remote -v` ... It will print out both remotes `origin(repoles) and upstream(zurb)`

4. Now create a new branch `git checkout -b hotfix/iterate-button-pallete`

5. Once your commit is done, push it => `git push origin HEAD` or `git push origin hotfix/iterate-button-pallete`
