### ISSUE TITLE
Sticky plugin- possible to stick and stack multiple elements [FEATURE REQUEST]

### ISSUE THREAD

**Issue by dlewand691** [zurb/foundation-sites#10595]
Have asked this on the forum with no replies.

Trying to use the Sticky plugin to stick and stack 2 elements on top of each other with the first having variable height. Is this possible with the current state of Foundation?

Looking for a solution similar to this plugin but would be ideal if it's already available in Foundation:
[http://alextaujenis.github.io/jquery-stuck/](http://alextaujenis.github.io/jquery-stuck/)
[http://leafo.net/sticky-kit/](http://leafo.net/sticky-kit/)

And here is a rough comp of what I'm trying to accomplish:
[https://codepen.io/danlewski/pen/QMZYaq](https://codepen.io/danlewski/pen/QMZYaq)

The expected result is for the smaller blue bar to stick to the bottom of the larger gray bar, regardless of the text length. 

Thank you!

**Comment by mattbag** [comment]
@dlewand691 Do you want the small bar to be on top of the big one? You just need to apply another class like in this demo, or give one of the bar a margin top correct

https://codepen.io/IamManchanda/pen/aWaJpM?editors=1011

**Comment by mattbag** [comment]
https://codepen.io/mattbag/pen/GvwxjW

something like this?

**Comment by dlewand691** [comment]
Brilliant! Thank you! This is exactly what I was looking for and makes total sense. Sometimes the most obvious solutions are right in front of your face.

However, I wonder if this might still be something worth integrating into the Sticky plugin? The ability to stick to its "parent" instead of the body?

**Comment by ultra86** [comment]
I ran into a similar problem when trying to use the sticky element when I have a manually placed sticky header in place (header = position:fixed / page-content = padding-top:90px). The sticky element wasn't kicking in until it reached the top of the body and when it did the first 90px was hiding behind the sticky header. To fix this I applied the data-top-anchor to an element (#sticky-fix) that was absolute positioned -90px (actually -75px because there was a 15px discrepency for some reason) and applied a margin top of 90px when the element was sticky. 

Tried to wrap my head around why it was -90px (-75px) instead of +90px, but gave up because it worked. 

Note that this solution positions the sticky element in the correct place AND it kicks in at the right time (as opposed to the example above where it kicks in quite late)

![image](https://user-images.githubusercontent.com/5143892/55573442-96384580-56cf-11e9-8d41-2afe71157e95.png)

![image](https://user-images.githubusercontent.com/5143892/55573463-a9e3ac00-56cf-11e9-8e4f-cea954d14d61.png)
![image](https://user-images.githubusercontent.com/5143892/55573484-b49e4100-56cf-11e9-87b1-e501870fa56e.png)

Anyhow, thought I would post this as I ran into this thread when trying to solve my problem.
