### ISSUE TITLE
Dropdowns have broken ARIA references

### ISSUE THREAD

**Issue by erutan** [zurb/foundation-sites#10627]
#### How to reproduce this bug:

1. Go to http://foundation.zurb.com/sites/docs/dropdown.html (or any page where you have a dropdown), and run the wave extension http://wave.webaim.org/extension/
2. If you check it you'll see that the ARIA references in the dropdown don't reference their parent.

#### What should happen:

ARIA references should not be broken/isolated and refer to the parent.

#### Browser(s) and Device(s) tested on:

Firefox/Chrome/Safari

#### Foundation Version(s) you are using:

7.4.3, 6.3.1

**Comment by knabe** [comment]
@erutan are you referring to the labelledby reference? They could be clearer about it. But it's defined by applying an ID. example : https://codepen.io/knabe/pen/BwNErP

**Comment by erutan** [comment]
Thanks I'll look into that - someone brought up the issue and I was about to be offline backpacking in the Sierra Nevada so didn't dig into it too much. Could have just missed that step from docs. :)

**Comment by Owlbertz** [comment]
@erutan Were you able to check this?

**Comment by webuxr** [comment]
@Owlbertz ...appreciate the bump.

@erutan ...still looking for an update on this. Any notable progress?

**Comment by ncoden** [comment]
@erutan @knabe @webuxr @fburleigh Please see https://github.com/zurb/foundation-sites/pull/10840

**Comment by elrolito** [comment]
@ncoden is this fix only in the develop branch, and not in 6.4.4-rc1?

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/pull/10840 is after October 2017 so this has not landed yet afaik.

**Comment by ClaytonMassey2** [comment]
@ncoden  Hey Nicholas, will moving from 6.4.1 to 6.5 introduce any breaking bugs?

**Comment by DanielRuf** [comment]
See https://github.com/zurb/foundation-sites/pull/11340

**Comment by ClaytonMassey2** [comment]
Thanks Daniel for the quick response

**Comment by silenceway** [comment]
Hello,
I left the comment on merged commit but I added here because it's related to this issue.
The aria-labelledby attribute must point to the id of the label, if it's created with GetYoDigits function, this new id must be added to this.$currentAnchor to prevent an accessibility error.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute
In demo page: https://foundation.zurb.com/sites/docs/dropdown.html you can see that all aria-labelledby are broken because id doesn't exist.
Thanks.
