### ISSUE TITLE
[Off-canvas] Missing link / text color variable

### ISSUE THREAD

**Issue by thomasfrobieter** [zurb/foundation-sites#10647]
We have $offcanvas-background in the _settings.scss but no $offcanvas-color / link-color?

**Comment by mattbag** [comment]
I guess it might be a specificity problem for most, I usually use modifiers for text colors...

**Comment by SassNinja** [comment]
@thomasfrobieter you're right, a variable to adjust the general color in the off-canvas makes probably sense (if you choose e.g. background color black you definitely have to adjust it).

But we shouldn't affect any other links / components in the off-canvas because this will result in a lot of more code and may cause specificity issues. This should be done by the user.

 So imo a new variable `$offcanvas-color: $black !default;` is fine.

@brettsmason @IamManchanda what do you think?

**Comment by rafibomb** [comment]
If you are setting link colors, I'm assuming you are using a `.menu`? If so, it doesn't make sense to me because this is something you can easily write CSS for. You may have color apply to text, links, or links in a `.menu`. It's too many use cases and a variable may yield unexpected results.

Also, the _settings.scss file has a lot of variables already and too many make it hard to name and hard to find values for users. Unless the variable does something that is hard to do with simple CSS it will not be a good idea to add.

**Comment by thomasfrobieter** [comment]
You can argue like this for almost every variable we have. It's not a lack of css skills or something, it's simply a case of sense and nonsense. Why do we need the BG color setting if we don't able to set the color on the same place?
