### ISSUE TITLE
[Tabs] data-tabs-target produces Javascript error

### ISSUE THREAD

**Issue by reinhardmohr** [zurb/foundation-sites#10660]
Hi,
thanks for making foundation!
I use 6.4 and usually work with Safari for Mac.
In your documentation http://foundation.zurb.com/sites/docs/tabs.html you have Containers > Tabs and there is the Basics panel with the first code to copy. 
There you have the code snippet
`<a data-tabs-target="#panel2" href="#panel2">`
This obviously stops Tabs from working. With me it produces a Javascript error that says.
`foundation.js:5118Error: Syntax error, unrecognized expression: ##panel2 — jquery.js:1579`
The tabs simply don't open the content. It seems to be caused by the double ##.
When I remove `data-tabs-target="#panel2"` so that only `<a  href="#panel2">` remains everything works fine.
Thanks for making foundation, again!
Reinhard

**Comment by ahimsauzi** [comment]
Same issue here. In my case passing the target id without the hashtag also fixes the issue. LIke so:
`data-tabs-target="panel2"`

**Comment by denisahac** [comment]
The extra `#` in the said example as you pointed out has been resolved. See *Tabs &bull; Basics* section [here](https://foundation.zurb.com/sites/docs/tabs.html#basics)

**Comment by bjornet** [comment]
This is fixed in the documentation on the as stated above by @denisahac, tnx for pointing out. What fogged my view was that – I use a offline documentation which updates monthly/weekly. But Zurb seems to have missed to update this part of the docs in both places (for the online and the offline docs). (The offline docs I refer to is read through Dash, I don't know exactly where they are fetched from).

**Comment by DanielRuf** [comment]
Closing as this seems to be fixed. Feel free to create a new issue if this is not fixed.
