### ISSUE TITLE
Foundation 7 - progress?

### ISSUE THREAD

**Issue by qdbdbp** [zurb/foundation-sites#10686]
What stage is Foundation 7?
Can I download the Foundation 7 versions or testing?

https://github.com/zurb/foundation-sites/wiki/Project-Roadmap#70-november-2017

**Comment by christianmagill** [comment]
How does one sign up to become a member of the beta when released?

**Comment by digitalfuel** [comment]
I too would like to access any beta when available. Or see an update on the direction of 7 when possible.

**Comment by rafibomb** [comment]
The latest releases - 6.3 and 6.4 are a progression to get to F7 with an updated grid, menu, dropdown and the JS architecture changes incorporating module bundling. The timeline there needs  to be updated since there are a couple more major releases before 7 is in beta.

**Comment by qdbdbp** [comment]
Your answer is unclear.
What is the real state of foundation 7 at this time?

**Comment by IamManchanda** [comment]
To be honest... 

Due to some internal reasons, I don't think we can release foundation 7 on time in november.
That said, We are getting clarity on the progress of where we need to go for foundation 7
Hard to commit but it seems like early 2018 would be the correct time 

cc @kball on updating wiki roadmap!

**Comment by qdbdbp** [comment]
Thanks for the honest answer.
Good luck on your way to Foundation 7.
It will be a revolution!

**Comment by IamManchanda** [comment]
> It will be a revolution!

It can be if people like you wants to contribute :)

**Comment by murdoch** [comment]
Is there update on on the timeline for Foundation 7 yet? Is it still in production? Do you need help with anything in partiular?

**Comment by ncoden** [comment]
Hi @murdoch.

There is a good and a bad news.

The bad news is that the roadmap and objectives changed since October. Foundation 7 will not be built on Foundation 6 (like small improvement and new features), but the whole architecture have to change. So this will be take far more time than expected.

The good news is that we're not doing that for nothing. The whole new framework architecture would make us able to provide far more components, more customizable than ever and - most importantly - usable in any modern framework like if it was a native component, with all the features offered by the framework.

We are really excited by Foundation 7. There's still a lot of work before we ever begin to implement it, but we will make public announcements to keep you informed about the work progress.

**Comment by grantcarthew** [comment]
I recently came across frameworks like https://www.iviewui.com/ and evaluated options outside of Foundation. I am using Vue.js. After spending a day looking at this and other Vue.js specific frameworks, I have decided to stick with Foundation. This is a great framework and you guys have done a fantastic job. The JavaScript side of things are a little lacking which I gather is the drive for v7.

Thanks guys.

**Comment by proov** [comment]
when i'm working with Vue and Nuxt. I'm using only the SCSS part of Foundation, the breakpoint, rem calc, and others mixins are really great and very modular. The JS part is not very friendly to be used as modules or components. I think Foundation V7 have to be really lighter than V6. I'm using Foundation since the V3, ithink it's time to contribute now :D Is there a tutorial to contribute ?

**Comment by rafibomb** [comment]
@proov that's awesome! https://github.com/zurb/foundation-sites/blob/develop/CONTRIBUTING.md

**Comment by rafibomb** [comment]
@grantcarthew glad to hear it, thanks!

**Comment by colin-marshall** [comment]
Closing this out to keep things tidy.

**Comment by ncoden** [comment]
@jamJamDev There is still _a lot_ of work before Foundation 7, so you can upgrade to Foundation 6.

**Comment by jamJamDev** [comment]
@ncoden thanks! Do you happen to know if an upgrade guide for 5 to 6 might be released? Reading across some different forums, it seems like it's not exactly a straight forward process & a guide would be extremely helpful.

**Comment by jamJamDev** [comment]
@ncoden apologies, I didn't see your reply [here](https://github.com/zurb/foundation-sites/issues/7318). Thanks! :)

**Comment by lcges** [comment]
Any news related to the development of Foundation 7?

**Comment by guci0** [comment]
It's only Number ;) Get latest and go.

**Comment by lcges** [comment]
I like **Big Numbers** ;) Do not worry about me, I always work on the latest version.

**Comment by IamManchanda** [comment]
> lcges => Any news related to the development of Foundation 7?
> guci0 => It's only Number ;) Get latest and go.

Not just a Number. We have big plans for F7 ... We will update you guys... Cheers!

**Comment by QuantumInformation** [comment]
Does anyone have a set of breakpoints that will be added to foundation 7? I want to add to https://github.com/quantumjs/css-variables/tree/master/breakpoints

**Comment by DanielRuf** [comment]
I don't think that we will change existing or add new breakpoints.
So far we do not know if there will be any changes as we are in the early planning phase.
We do not create Foundation Sites from scratch so you can expect that we will keep them as they are.

**Comment by DanielRuf** [comment]
> I would suggest we move the medium breakpoint down 1px so that the ipad falls into the medium breakpoint.

Right. Had the samd issue here. But I think iPad Pro 10.5 is also very special regarding the viewport.

**Comment by DanielRuf** [comment]
> I would suggest we move the medium breakpoint down 1px so that the ipad falls into the medium breakpoint.

Right. Had the same issue here. But I think iPad Pro 10.5 is also very special regarding the viewport.

**Comment by murdoch** [comment]
How can we contribute to to F7? I'd love to help make the new version.

**Comment by kevinmu17** [comment]
Any news on this?? it's been a big while now since we heard something new :)

**Comment by DanielRuf** [comment]
Hi, we are currently actively working on a few things for Foundation and we will let you know then.

**Comment by lcges** [comment]
Hi @DanielRuf.

It's nice that you're doing something there, but you haven't said anything specific to the community since 2017. It looks like an abandoned project. 
And times and needs are changing - what was important in 2017 is already history in 2019... and on the horizon it's already 2020.

**Comment by DanielRuf** [comment]
We are aware of it and will let you know. There will some news very soon.

**Comment by kevinmu17** [comment]
Awesome, i can't wait! i'm always hyped when a new version comes out (big fan since F3)

@DanielRuf 
> We are aware of it and will let you know. There will some news very soon.

This feels like christmas is coming!

**Comment by TiagoDeSousa** [comment]
Any news on foundation 7 yet?

**Comment by DanielRuf** [comment]
No ETA yet, we are currently working on 6.6 before we work on 7.

**Comment by Baggio89** [comment]
6.6 will be the best christmas present evurrrr!!
My whole career is build on Foundation. When i saw that development stopped i blacked-out for a few days... when i came back to consciousness this is where i landed. 

Happy to see positive words here. Much love for the Zurb team, it has always been you <3

**Comment by TiagoDeSousa** [comment]
Any updates on Foundation 7?

**Comment by DanielRuf** [comment]
> Any updates on Foundation 7?

No updates so far as you can see.

**Comment by TiagoDeSousa** [comment]
@DanielRuf yeah I can see that Mr obvious. You didn't understand my question. I wanted to know if there's any news on this like is Foundation 7 going to happen or not? Is anyone working on this. What progress has been made? Things like that.  It's been years since F7 has been announced in the roadmap hence my question.

**Comment by DanielRuf** [comment]
> I wanted to know if there's any news on this like is Foundation 7 going to happen or not? Is anyone working on this. What progress has been made? Things like that. It's been years since F7 has been announced in the roadmap hence my question.

Thanks for the clarifying your question. No, there is no progress so far because we need more active contributors and maintainers. Currently I am the only active maintainer and without the support from @joeworkman and all needed rights I can not do much and I do not want to push forward without deciding things together with all current and previous maintainers.

It will probably happen, but not in the near future. And working on this alone in my free time for free is not that great.

**Comment by DanielRuf** [comment]
> I wanted to know if there's any news on this like is Foundation 7 going to happen or not? Is anyone working on this. What progress has been made? Things like that. It's been years since F7 has been announced in the roadmap hence my question.

Thanks for clarifying your question. No, there is no progress so far because we need more active contributors and maintainers. Currently I am the only active maintainer and without the support from @joeworkman and all needed rights I can not do much and I do not want to push forward without deciding things together with all current and previous maintainers.

It will probably happen, but not in the near future. And working on this alone in my free time for free is not that great.

**Comment by Baggio89** [comment]
@joeworkman Let get this started then! i can contribute and would love to work on this! I can think of many things that could be done, upgrade the webpack workflow, css-grid implementation, swap the oribit slider for swiper instances dispose the animation UI and make it more gsap orientated :) Any many more.....

**Comment by kevinmu17** [comment]
> Currently I am the only active maintainer and without the support from @joeworkman and all needed rights I can not do much and I do not want to push forward without deciding things together with all current and previous maintainers.

This sounds very troubling! Isn't there some recruitment page? Routemap of alle the work that needs to be done? etc etc?
Like many, Foundation is my go to framework but this gives me very doubtful thoughts of proceeding using it. So, I want some information on how to enter maintainer, helper etc. It has been 3 years since this thread is openend so work needs to be done.

So, Joe, get to work man :D

**Comment by DanielRuf** [comment]
For the current discussion please see https://github.com/foundation/foundation-sites/issues/11847

PRs, reviews and issues (with PRs) are always very welcome.

**Comment by 0924249460** [comment]
ok
