### ISSUE TITLE
Broken Navigation on Zurb Foundation Website

### ISSUE THREAD

**Issue by COLABORATI** [zurb/foundation-sites#10718]
Are you guys aware that your website navigation is broken with Chromium Browser on Ubuntu 16.04 LTS?

![zurb-f6-site-broken-menu-chromium-ubuntu](https://user-images.githubusercontent.com/6514273/31461231-3046aaf0-aec9-11e7-9c42-8cde2725ed0b.png)

![zurb-f6-site-broken-menu-chromium-ubuntu-b](https://user-images.githubusercontent.com/6514273/31461239-3a128054-aec9-11e7-8bc5-ab046e5c2cfa.png)

**Comment by IamManchanda** [comment]
Chromium browser has been replaced with Chrome beta/dev 
so that can use them simultaneously 
https://support.google.com/chromebook/answer/1086915?hl=en

Visit here to download 
http://www.chromium.org/getting-involved/dev-channel/#TOC-Linux

Closing this... let us know if this needs any more discussion!

**Comment by IamManchanda** [comment]
FWIW ... I have tested the concerned pages in Chrome for Ubuntu (Beta, Stable, Dev) 
and everything works fine!
