### ISSUE TITLE
Flex grid combined column/row should be display: flex

### ISSUE THREAD

**Issue by dherran** [zurb/foundation-sites#10759]
When using the flex grid and a column/row is created, like so:

```
<div class="row medium-7 column">
  <div class="medium-6 columns">a</div>
  <div class="medium-3 columns">b</div>
  <div class="medium-3 columns">c</div>
</div>
```

The below is being applied to the row:

```
  .column.row.row {
    float: none;
    display: block;
  }
```
https://github.com/zurb/foundation-sites/blob/develop/scss/grid/_flex-grid.scss#L177

This is causing the column/row not to work as expected and the child columns will stack. Commenting out those lines fixes the problem.

Example: https://codepen.io/anon/pen/oojypr?editors=1111

Happy to send a pull request if you agree this is a bug.

**Comment by rafibomb** [comment]
This is intended behavior because combining `.row.column` on the same element is really only for creating a wrapper to give your content a max-width. 

The grid has to have a few rules to make it work in most cases and one of those is that a `.column` should not be a direct child of a `.column` to avoid padding issues.
