### ISSUE TITLE
Reinitializing a slider doesn't reset min/max/step props

### ISSUE THREAD

**Issue by gcoombe** [zurb/foundation-sites#10775]
I want am trying to update min/max/step values on a slider and reinitialize the slider with the new properties but am not having any luck.

I've tried:
- Calling Foundation.reInit on the slider components
- Destroying and recreating the slider with new Foundation.slider

In both cases the slider still has the original min/max.  Is there something I'm doing wrong or a workaround? 

See fiddle: https://jsfiddle.net/bhrqus25/3/

**Comment by denisahac** [comment]
# Your Approach
Instead of setting the new value of `data-end` from the `elem` instance you changed it in the **jQuery** object `$target` via its `attr` method; `$target.attr("data-end", "500")`

After instantiating an object the components doesn't listen to the *data-attributes* changes in **HTML** -- and re-initializing the same object without destroying doesn't re-initialize either.
```html
...
 <div class="slider" id="slidervol" data-slider data-end="100">
      <span class="slider-handle" data-slider-handle role="slider" 
          tabindex="1"  aria-controls="sliderVolOutput"></span>
      <span class="slider-fill" data-slider-fill></span>
 </div>
...
```

```js
var $target = $("#slidervol");
var elem = new Foundation.Slider($target);

$target.attr("data-end", "500");
Foundation.reInit($target)
```

# Solution
If you want to change the value of a **Foundation** components on the fly, you don't need to reinitialize them to see the desired effect. You can set new values via its instance by calling the `options` field as follows:

```js
var elem = new Foundation.Slider($('#slidervol'));
elem.options.end = 500; // set the data-end to 500
```

# Other thoughts

I don't know if setting the `options` field directly is the recommended way of changing values in **Foundation**. Could there's a method perhaps: `elem.set('end', 500)`  and further validation inside the setter method in case we set a wrong value.

**Comment by gcoombe** [comment]
Thanks for the reply! 

I wasn't aware of that there was an options field that you could update.  Is this documented anywhere?

**Comment by denisahac** [comment]
It is no where to be found in the documentation, you actually need to see the code on how it works. Gladly I worked with some of the plugins so I know that there's a field variable `options`. I think it is not a recommended of getting/setting data attributes. 

@rafibomb @IamManchanda would it be possible and reasonable if we provide a setter method for changing the options data-attributes on the fly, and at the same time update the rendered HTML with the new data attributes value assigned?

```js
var slider = new Foundation.Slider($('#target_id'));

// `set` is a function setter
slider.set('end', 500);
slider.set('min', 10);
```

**Comment by IamManchanda** [comment]
I am on! Exactly having a setter would be in this case!

**Comment by denisahac** [comment]
Would it be reasonable for all the Javascript plugins to have a **setter** function? I think this is something that needs to be discussed in more elaborate details to determine what plugins should have the **setter** function.

**`Slider`** setter function could look like the code snippet below:

```js
/**
 * Attribute setter.
 * @function
 * @public
 * @param {string} name - the attribute name.
 * @param {*} value - the new attribute's value.
 */
setter(field, value) {
     switch(field) {
          case 'start':
               this.options.start = value;
               break;
          case 'end':
               this.options.end = value;
               break;
          case 'step':
               this.options.step = value;
               break;
          ...
          // update rendered HTML attributes
    }
}
```

**Comment by IamManchanda** [comment]
Agree ...

**Comment by colin-marshall** [comment]
Thanks for this feature request. We’re going to close out this ticket, as we will not be adding more features to Version 6, but your request is being considered for Version 7.
