### ISSUE TITLE
What's the available values for $global-color-pick-contrast-tolerance?

### ISSUE THREAD

**Issue by mistalaba** [zurb/foundation-sites#10787]
What range can you use for the $global-color-pick-contrast-tolerance variable?

The docs (https://foundation.zurb.com/sites/docs/global.html#sass-variables) only says a number and that default is 0. Actually, it's not (for me) very clear on what this will do? Are there any examples in the wild?

Thank you!

**Comment by SassNinja** [comment]
That's not really an issue but I agree it's not clear in the docs how to use it.
To be honest I think this variable is not suitable for many users because the topic is not easy. Maybe it shouldn't be mentioned in the docs at all...

But I'll try to explain it briefly anyway.
This tolerance is used by the `color-pick-contrast' function that tries to pick the color of a map (default black & white) that has the best contrast for a given color.

So let's say your base color is '#333'. Then the function will compare it to black and white and return white because it has the best contrast.
The tolerance is used here to specify how much the color that is currently checked (e.g. white) has to be better than the previous match.

0 means if the color has any contrast improvement (even if only 0.1) it will be the new match in the iteration. If you take a look at the `_color.scss` you will find the line
```scss
@if ($current-contrast - $contrast > $tolerance) {
```
The worst possible contrast is 1 (e.g. white on white) and the best possible contrast is 21 (black on black). So if the tolerance is >= 20 the condition will never be true.

Hope this helps a little bit to understand it better. Usually you're fine with the default 0 value and should only adjust it if you know what you're doing. If you want to know more about this I highly recommend checking the mentioned `_color.scss` and the comments in it.

**Comment by mistalaba** [comment]
Thanks for your reply!
I looked at the code in ```_color.scss``` and the javascript it is adapted from, but I don't get a clear idea how it works (sorry, it's not your explanation, it's my lack of understanding of this concept).
So, I was looking at this because I wanted to use the contrast checking properly. The problem I had was that black almost always "won" with the background colors I am using, even though using white clearly looks better. So I wanted to ease those contrast values a little bit, but still be able to use the automatic contrast checking, especially if you changed a color and it clearly was bad contrast (like light grey on white). Anyways, it's not a big deal so I'll just use manual coloring for now, until I have a chance to try and wrap my head around it next time.

Cheers!

**Comment by vanilla-thunder** [comment]
hi, sorry for bumping this issue, but is there any way to debug this color picking / contrast checking process?
When creating css for just "button" class, it keeps suggesting me white text color for yellow background. (#ffff00 / rgb(255,255,0) )
but everything is fine when generating style for "button primary".
According to what i found about the contrast checking functions (e.g. issue #9555 or #9747) the text collor is definitely supposed to be black.
my scss:
````SCSS
$foundation-palette: (
        primary: #ffff00,
        secondary: #555,
        success: #1cd361,
        warning: #ee8e51,
        alert: #e9443f
);
@import 'foundation';
@include foundation-everything;
````
nodejs v10.0.0
node-sass v4.9.0
libsass v3.5.4 

best regards!

**Comment by DanielRuf** [comment]
> hi, sorry for bumping this issue, but is there any way to debug this color picking / contrast checking process?

Do you mean `@debug`?
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#debug

**Comment by vanilla-thunder** [comment]
Thank you Daniel, 
I found out, that default .button style ignores contrast checks and is generated with default ``$button-background`` (which is primary color) and ``$button-color`` (which is white).
Basically, when changing colors, you have to adjust ``$button-color`` + ``$button-color-alt`` to match primary color.
