### ISSUE TITLE
Why `<hr/>` max width is 75 rem instead of 100% width

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10838]
<img width="2559" alt="screen shot 2018-01-07 at 11 46 43 am" src="https://user-images.githubusercontent.com/4970624/34647154-b4afda98-f3a0-11e7-96a2-1cdba0d50090.png">

#### Test case link:

https://codepen.io/IamManchanda/pen/KZXQYr?editors=1010

Reproduced in: Apple iMac

**Comment by markadrake** [comment]
Only my opinion, but...

- Please do not style base HTML tags for any other reason than _providing consistency and stability between browsers and devices_. 

- The `<hr>` tag, like many others, now has a _semantic meaning_. A responsible and mature frontend framework will avoid mixing styles with semantics. Allow those who manage content and context to do so without worrying about the styling that's applied. 

- If you want to add your own personal style to `<hr>` - that's great. Please do. For your site, for your project, for your branding standards, for your content authors who've been trained - this is fine.

- If you (Zurb) absolutely must style this element due to consistency reasons, non-breaking changes, etc - please scope it out. You mentioned that the `<hr>` tag needs these properties when displayed correctly between grids. Why did you not go with an adjacent sibling selector like `.row + hr`?

**Comment by ncoden** [comment]
I **fully** agree with you.

I simply explained the reasons why `<hr>` _currently has_ these styles. But if we talk about what I think we _should_ do, i'll promote a `.hr` class independant from to the `<hr>` tag. A standalone component without side-effects on the semantic of the document.

This is the idea behind "However, we may should remove this max width and rely on a "container" instead": remove the `max-width` (and others properties) from `<hr>` and rely on dedicated components (`.container` or `.hr`) to get the same render.

The best would be something like:
```
<main class="zf-container">
    <hr class="zf-hr">
</main>

**Comment by DanielRuf** [comment]
> Please do not style base HTML tags for any other reason than providing consistency between browsers and devices.

Why not? The only problem is that it is generally applied and not a component with a better scope like @ncoden writes.

**Comment by ncoden** [comment]
> The only problem is that it is generally applied and not a component with a better scope

This is the problem ;) `<hr>` can be used in a lot of complex contexts where we do not expect it to have the Foundation design.

**Comment by DanielRuf** [comment]
> Look at how many issues reported to Foundation and others frameworks are unexpected CSS properties.

Ok so Foundation Sites is too opiniated in some places atm and this should be prevented in upcoming releases?

**Comment by ncoden** [comment]
If you mean `opinionated` yes, it is.

**Comment by JeremyEnglert** [comment]
I don't think there is anything to resolve here. Let's keep this in mind for V7.
