### ISSUE TITLE
[Off-Canvas] Width not calculating correctly

### ISSUE THREAD

**Issue by nickmagee** [zurb/foundation-sites#10860]
#### How to reproduce this bug:

1. Step one - Generate off-canvas
2. Step two - inject an image/text
3. Step three - see it's not calculating correctly

#### Foundation Version(s) you are using: 6.4.3

https://codepen.io/NickMagee/pen/jYKGJE

**Comment by ncoden** [comment]
Off canvas width is not calculated but static (`250px`), is CSS. The problem here is the grid with negative margins (`grid-margin-x`). The quick solution would be to avoid using this in an off-canvas. A better solution (but maybe breaking) would be to ensure prevent any scroll in off-canvas with `overflow-x: hidden`.

**Comment by SassNinja** [comment]
Imo the easiest solution is to simply use `grid-padding-x` instead of `grid-margin-x` to avoid problems with the grid's margin.

Apart from that I agree with @ncoden it's not a calculation issue since the width is not getting calculated.

**Comment by ncoden** [comment]
@SassNinja  Beside that the question is: do we expect a scroll to appear inside the offcanvas panel ? If I use a component that is too big, should it but "cut" or have scroll ?

**Comment by SassNinja** [comment]
I can imagine use cases for both (e.g. non responsive content within the off-canvas where horizontal scrolling might be desired – although it's not pretty).

The advantage of scroll is it's more obvious if the developer has done sth wrong (in this case used the grid wrongly). So imo overflow scroll should be preferred.
