### ISSUE TITLE
Full-screen Modal on iOS

### ISSUE THREAD

**Issue by jordanbommelje** [zurb/foundation-sites#10879]
#### How to reproduce this bug:

1. Open https://foundation.zurb.com/sites/docs/reveal.html#full-screen on iOS Device
2. Tap on "Click me for a full-screen modal"

#### What should happen:
Expecting it to be full screen like on desktop/laptop

#### What happened instead:
Appended to the end of docs-sticky-top-bar instead of covering this as well

#### Browser(s) and Device(s) tested on:
12.9" iPad Pro - Does not work
iPhone X - Does not work

#### Foundation Version(s) you are using:
v.6.4.3

#### Test case link:
It can be seen directly on the Foundation for Sites documentation page for Reveal: https://foundation.zurb.com/sites/docs/reveal.html#full-screen

**Comment by DanielRuf** [comment]
Can you provide some info about the iOS and Safari / webkit version?

**Comment by p8** [comment]
I see the same problem on iOS 10.3.3:
![img_0030](https://user-images.githubusercontent.com/28561/36841153-52ac491c-1d3f-11e8-958e-ad74b7d7f8ae.PNG)

**Comment by p8** [comment]
This is on a iPhone with iOS 11.2.6
![image-1](https://user-images.githubusercontent.com/28561/36841879-bc1d25cc-1d41-11e8-9be7-ca3dd2ce78d2.jpg)

**Comment by DanielRuf** [comment]
Which Safari / webkit version is installed?

**Comment by DanielRuf** [comment]
iOS 10 uses often Safari 10 which has some flexbugs and is not supported by Apple anymore.

**Comment by DanielRuf** [comment]
Attention, you have different viewports there.

**Comment by p8** [comment]
@DanielRuf I've added the webkit versions.

**Comment by DanielRuf** [comment]
Sorry, meant the Safari version. This is actually what matters.
Also the one looks like desktop breakpoint / view.

**Comment by p8** [comment]
I've added the safari versions. Thanks for looking into this. 👍

**Comment by DanielRuf** [comment]
These are not valid Safari versions. They are in the settings of Safari. Like Safari 10, 11, and so on.

**Comment by DanielRuf** [comment]
I guess I know what issue is meant. On small screens the modal gets some top value which moves it a bit down.

There might be other issues which describe the same behavior.

I'll check the reveal component,

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/blob/develop/js/foundation.reveal.js#L117-L129

**Comment by DanielRuf** [comment]
@SassNinja does the code make much sense?

https://github.com/zurb/foundation-sites/blob/4fbcb916b72295b6058a2edf968a3e0739925f1a/js/foundation.reveal.js#L117-L129

**Comment by p8** [comment]
On mobile all modals are fullscreen. The tiny, small and large modals work correctly and don't append to the sticky top-bar.

**Comment by p8** [comment]
I've fixed it by forcing the top to 0:
`.reveal.full {
  top: 0 !important;
}
`

**Comment by jacobcarrington** [comment]
So I ran into this same issue and I think this is a cleaner fix: I added `data-v-offset="0"` to the reveal pattern. Seems the auto offset calc is inconsistent.

**Comment by ncoden** [comment]
Hi 👋,

I made some tests. The `_updatePosition` position method works well and have the behavior we can expect from it. The issue comes from the viewport height on iOS when you scroll down/up and the Safari topbar collapses/expands.

When it is collapsed on iPad pro, the window height is about `984px`. When is expanded, there is less place for the web page and the window height is about `954px`.

However, the CSS viewport is still `984px`. Because the modal uses `height: 100vh`, it will still be `984px`, taller than the window, and the `_updatePosition` will position it differently.

See this article: [Viewport height is taller than the visible part of the document in some mobile browsers])https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html)

**Comment by ncoden** [comment]
Fixed at https://github.com/zurb/foundation-sites/pull/11462
