### ISSUE TITLE
Component styling not functional by default ?

### ISSUE THREAD

**Issue by udf2457** [zurb/foundation-sites#10890]
Foundation-sites 6.4.3

As per `https://foundation.zurb.com/sites/docs/prototyping-utilities.html#component-styling`, it should be possible to use `rounded` to style a button.

However this does not appear to work, the button stays rectangular for me no matter what.  See [this codepen](https://codepen.io/anon/pen/jZOZPw)

**Comment by colin-marshall** [comment]
@udf2457 the prototype classes aren't included by default. Adding this stylesheet after `foundation.min.css` will let you use them:
`https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation-prototype.css` to your codepen makes them round.

**Comment by IamManchanda** [comment]
Hi @udf2457 Sorry but the way foundation works (Framework Pledge), we won't make prototype classes default 
So marking this as invalid

As colin said you can however use them using `foundation-prototype.min.css` instead of `foundation.min.css` or using Sass variables as mentioned in docs.

Let us know if you have any other issues you are facing for the same!

**Comment by udf2457** [comment]
@IamManchanda @colin-marshall 

So you're basically saying for rounded buttons I have to DIY or import some other library ?

Your biggest competitor (Bootstrap) does rounded buttons out of the box ?  I really really struggle to see your thinking here ?

**Comment by IamManchanda** [comment]
We just disable Prototype classes by default 
https://foundation.zurb.com/sites/docs/prototyping-utilities.html#enabling-prototype-mode

You can reenable it as mentioned in the docs

or using `foundation-prototype.min.css` instead of foundation.min.css 
Check https://cdnjs.com/libraries/foundation/6.4.3

**Comment by IamManchanda** [comment]
> Not all projects require Prototyping Utilities and adding utility classes like these increase your CSS file size especially if you're not using all of them. For these reasons Prototype mode is disabled by default.

**Comment by colin-marshall** [comment]
@udf2457 here's another issue that goes over some history and reasoning:
https://github.com/zurb/foundation-sites/issues/7026

I will admit that there seems to be a void for people like yourself that use the precompiled Foundation CSS and want to use rounded buttons but also don't want to add the bloat of prototype classes. 

The workaround is pretty simple thankfully. You can just add only the `.rounded` class from the prototype CSS to your site's custom CSS:

```css
.rounded {
  border-radius: 5000px !important;
}
```

**Comment by udf2457** [comment]
@colin-marshall 

Thanks for the tip. Guess that'll do !
