### ISSUE TITLE
Failed build React.js

### ISSUE THREAD

**Issue by wwwaddell** [zurb/foundation-sites#10987]
I have encountered an error msg when running the buildprocess för React.js. It says:

```
Failed to minify the code from this file:

        ./node_modules/foundation-sites/js/foundation.util.core.js:24
```

Anyone seen this, have a solution?

Error msg takes me to this link; http://bit.ly/2tRViJ9, says that code isn't compiled to ES5 before published to npm.

**Comment by DanielRuf** [comment]
Please provide some more info like the full terminal output, your babel settings and webpack config.

**Comment by ncoden** [comment]
Hi @wwwaddell,

This is a known issue. The default entry file for NPM in `v6.4.3` is in ES6. This should be fixed in the next release. Take a look at https://github.com/zurb/foundation-sites/pull/10864 and https://github.com/zurb/foundation-sites/pull/10930.

For now, you can manually import the compiled dist file:
```
var Foundation = require('foundation-sites/dist/js/foundation');
```

**Comment by wwwaddell** [comment]
Thank you so much @ncoden! I tried searching before posting but was unsuccesful.. So thank you :)
