### ISSUE TITLE
build: Yeoman generator (and alternatives)

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#11047]
We should create a yeoman generator for creating a custom version of Foundation Sites (replacement / addition for the customizer).

https://github.com/yeoman/yo
https://github.com/yeoman/generator

As far as I know this is already on our roadmap in the wiki.

https://github.com/SBoudrias/Inquirer.js
https://github.com/dthree/vorpal
https://github.com/vadimdemedes/ink

**Comment by colin-marshall** [comment]
@DanielRuf I'm not sure if this is worth our time for v6. Is this something we could integrate into the `foundation-cli`?

Also, I don't think we want to replace the customizer because it is used by more "novice" developers that are probably intimidated by the command line. If we could make a web-based GUI/front-end for the Yeoman generator, then it could replace the customizer.

**Comment by DanielRuf** [comment]
> I'm not sure if this is worth our time for v6

Planned for v7 afaik, see the roadmap in the wiki.

> Is this something we could integrate into the foundation-cli

Probably.

> Also, I don't think we want to replace the customizer because it is used by more "novice" developers that are probably intimidated by the command line. If we could make a web-based GUI/front-end for the Yeoman generator, then it could replace the customizer.

Possibly with React for example. But this is just an idea and proposal.

**Comment by colin-marshall** [comment]
The roadmap hasn't been updated since November and a lot of plans have changed since then. Either way, I think we should close this issue and add the Revisit for F7 tag. We're trying to limit open issues while we resolve outstanding issues in F6. There's also the Foundation 7 channel on Slack.

**Comment by DanielRuf** [comment]
> Foundation 7 channel on Slack.

Where? =)
