### ISSUE TITLE
Foundation 7: Drop Prototype & Flexbox Utilities and recommend Tailwind for Utility use cases!

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#11170]
I know I have worked largely on them being the creator of [Prototype Utilities](https://github.com/zurb/foundation-sites/pull/10091) and worked good amount on [Flexbox Utilities](https://github.com/zurb/foundation-sites/pull/10224)

But,
I really think that time is now with Foundation 7 we can dump it 
Instead we can and should recommend Tailwind on top of Foundation 7
https://tailwindcss.com/docs/what-is-tailwind

## Can Tailwind be used together with Foundation 7
Yes if we plan to use **prefixes** like `zf-` then why not!

**Comment by IamManchanda** [comment]
Moreover it allows prefixes also https://tailwindcss.com/docs/configuration#prefix

So I think a recommendation like this for Foundation 7 will be a great combo 

`zf-` for **A Solid Foundation** for the website
`tw-` for Utility classes that was never a motive of Foundation? Am I Right or Am I Right?

**Comment by DanielRuf** [comment]
But be aware that Tailwind may create too many classes. I always thought about using Tailwind in small projects but it will introduce many new classes.

**Comment by IamManchanda** [comment]
We are just recommending tailwind for utilities stuff 

We are not saying that you should use utilities ...

I think main motive of dumping all these classes would be that we eliminate all these classes from our project

Foundation 7 should only care about helping users to create components and that's it ...
People should not use any utility classes in production instead should use sass mixins which foundation workflow already provides :)

**Comment by DanielRuf** [comment]
You are right on this. I agree with you that we can move this out of the component framework.

**Comment by SassNinja** [comment]
> We are just recommending tailwind for utilities stuff

Just to be sure I understand you correctly @IamManchanda:
you're suggesting to completely remove the Prototype Utilities for Foundation 7 and instead leave it up to the user (by only recommending tailwind)?

**Comment by IamManchanda** [comment]
@SassNinja ... Not only prototype but also flexbox utilities

**Comment by SassNinja** [comment]
Alright and what do you have in mind regarding the replacement with Tailwind?
Own page / chapter in the docs incl. a ready-to-go setup in the foundation templates or only a brief recommendation with linking to docs of Tailwind?

I'm asking because as far as I (currently) understand it feels somehow like a downgrade. I mean many users are used to the utilities and removing the completely without an alternative that is equally easy to use will end in frustration.

**Comment by GCheung55** [comment]
An upgrade path/guide seems necessary if Tailwind is suggested as replacement to the tools/utils Foundation provides.

**Comment by GCheung55** [comment]
@sassninja I agree. I think a guide that maps utilities between Foundation and Tailwind would be useful, as well as a guide for upgrading from v6 to v7

**Comment by rafibomb** [comment]
I totally love the idea of using outside resources in Foundation. I don't agree that Tailwind is the answer because I don't fundamentally agree with polluting my HTML with so many utility classes. This kind of feature needs to be small and opinionated.

If we use something like Tailwind, perhaps we only include a small set of utilities and show people how to use the others. 

What's the benefit? Less maintenance of our own CSS?
