### ISSUE TITLE
Foundation 6 Reveal Scrolls up when clicking close button

### ISSUE THREAD

**Issue by aldrinhart** [zurb/foundation-sites#11201]
I know that it mentions in the below reference link to remove the href="#" or href from when you click on an element when you reveal a container and to keep you at the same position of the page. However when you click the close button span or anywhere outside of the reveal to close the container it scroll you back up on top of the page, leaving the viewer of missing their spot on the page. Is there a solution to this?

https://github.com/zurb/foundation-sites/issues/8883

**Comment by ncoden** [comment]
Hi @aldrinhart, 👋 

I am sorry, I don't understand your issue. Here are some informations that would be useful to us:
* What is your code. Did you remove `href="#"` ?
* How is your issue different from #8883 ?

Could you please follow [the new GitHub template](https://github.com/zurb/foundation-sites/issues/new) and edit your issue ? It will be closed otherwise.

You can take a look at [CONTRIBUTING.md](https://github.com/zurb/foundation-sites/blob/develop/CONTRIBUTING.md) too. Thank you.

**Comment by CarlosSouza** [comment]
I'm having this exact same problem.

I've been using link without `href` but it keeps moving screen to the top. I also tried using `button` (as the official documentation examples), with no success.
It's happening on `small` and `medium` breakpoints, while on `large` it works as intended.

**Comment by aldrinhart** [comment]
Hi ncoden, sorry for the late reply. Yes I had managed to solve it removing the href="" and just having the data-toggle. For example <a data-toggle="modal1"> Thank for the reply
