### ISSUE TITLE
Interchange with multiple stacked images

### ISSUE THREAD

**Issue by dlewand691** [zurb/foundation-sites#11332]
## What should happen?
I'd like to use an Interchange background image plus a 2nd image stacked on top by comma separating the paths in the url attribute.

Currently, I can't find a way to do this without creating separate divs. Does, or could, Interchange support multiple backgrounds?

## What happens instead?
Single image is shown instead of multiple backgrounds

## Possible Solution

Possibly use pipe (|) to separate multiple backgrounds.

## Test Case and/or Steps to Reproduce

Test Case:
https://www.dannylewandowski.com/_cog-DEV/_PROTOTYPING/Components/build/Header-Banners-composed.html

How to reproduce:
1.
2.
3.

## Your Environment

- Foundation version(s) used: 6.3.1
- Browser(s) name and version(s): Chrome 66
- Operating System and version (desktop or mobile): Mac desktop

**Comment by SassNinja** [comment]
@dlewand691 no, interchange does not support multiple background images for the same query name

How is this supposed to work?
The same element can't have multiple background images because they would override each other.

**Comment by dlewand691** [comment]
It would work by comma-separating each background image. Similar to these techniques:

[https://css-tricks.com/css-basics-using-multiple-backgrounds/](https://css-tricks.com/css-basics-using-multiple-backgrounds/)

The example I shared separate the line graphic from the background image so it can be managed/positioned/scaled separately without having to create multiple variations. 

How Interchange could implement this is by pushing the 2 URLs to the background attribute. Could use regex to run through the data element until the vertical pipe to signal what the multiple URLs are. 

I've separated the line graphic into another div which works fine but was hoping Interchange might be a little smarter.

**Comment by SassNinja** [comment]
To be honest I haven't used multiple bg images yet but makes sense if you are using images as shown in your example.

Often I'm not able to use it like this because multiple image layers (in particular `png`) cause much more traffic than putting it all in one picture.
When you check your example on mobile device you'll notice the transparent mesh image file is greater than any other image.

However one thing that should be specified is the responsive behavior:
What is supposed to happen if you specify two images for mobile and only one for medium?

Imo it should simply override the whole `background-image` and not try to merge the images.

Example markup

```html
<div data-interchange="[smallA.jpg|smallB.jpg, small], [medium.jpg, medium]"></div>
```
would result in

```html
<div style="background-image: url(smallA.jpg), url(smallB.jpg)" data-interchange="[smallA.jpg|smallB.jpg, small], [medium.jpg, medium]"></div>

<div style="background-image: url(medium.jpg)" data-interchange="[smallA.jpg|smallB.jpg, small], [medium.jpg, medium]"></div>
```

Poke @ncoden @DanielRuf – what do you think abt this feature?

**Comment by dlewand691** [comment]
Yeah, it comes in handy for things like this...editors and authors always want to make changes and this keeps the tasks of the production team at a minimum. 

You're right about the mesh size, it's not optimized yet.

Being able to specify different images at breakpoints would be great too. 

Thanks!
