### ISSUE TITLE
Importing Foundation component as ES6 module includes the whole code and not only the code which is necessary for the component

### ISSUE THREAD

**Issue by marvinhuebner** [zurb/foundation-sites#11401]
Currently I'm updating our boilerplate project to 6.5.0-rc2. As i've read in #10864 it should now be possible to include a JavaScript component with this way:

```
import $ from 'jquery';
import { Reveal } from 'foundation-sites';

$(document).foundation();
```

## What should happen?

Only the code which is necessary for the Reveal should be included in the bundle.

## What happens instead?

The whole Foundation JavaScript gets included in the bundle. 

## Possible Solution

Use the "old" solution, as described here: https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/js/lib/foundation-explicit-pieces.js

## Test Case and/or Steps to Reproduce

Test Case:

_See code example above, or the example:_

[![Edit #11401 Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8y19xzqr89?module=%2Fsrc%2Findex.js)

## Your Environment

- Foundation version(s) used: 6.5.0.rc.2
- Browser(s) name and version(s): Chrome
- Operating System and version (desktop or mobile): MacOS

## Checklist (all required):

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title is descriptive.
- [ ] The template is correctly filled.

**Comment by marvinhuebner** [comment]
I've added an example here:

[![Edit #11401 Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8y19xzqr89?module=%2Fsrc%2Findex.js)

**Comment by mattbag** [comment]
https://codesandbox.io/s/5w114vn64k
Looking at the zurb template I usually use, this is what they do.
It's in js/lib/ docs need to be more explicit

**Comment by ncoden** [comment]
Hello @marvinhuebner.

I seen your issue some days ago and planned to work on it this weekend. I watched at [zurb/foundation-zurb-template:src/assets/js/lib/foundation-explicit-pieces.js](https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/js/lib/foundation-explicit-pieces.js) and don't see how this would resolve the issue.

I'll make some tests to see how treeshaking is handled by most used builders.

**Comment by ncoden** [comment]
Hi @marvinhuebner @mattbag. Could you take a look at https://github.com/zurb/foundation-sites/pull/11445 ? 😉

**Comment by marvinhuebner** [comment]
I've tested your PR, and have some question. 

First I tested this:

```js
import Accordion from 'foundation-sites/js/foundation.accordion';

$(document).foundation();
```

This seems not to work, i get `Uncaught TypeError: (0 , _jquery2.default)(...).foundation is not a function`.

To get the manual import working, i have to do the following:

```js
import Foundation from 'foundation-sites/js/foundation';
import Accordion from 'foundation-sites/js/foundation.accordion';

var test = new Foundation.Accordion($('.accordion'));
```

So it seems i have to manually initialize my foundation components, and i have to import `Foundation`. I'm wrong with my examples or is this the way for doing it? If it is, maybe https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/js/lib/foundation-explicit-pieces.js is the way to go, for solving this problem.

Maybe i have some time this week and can dig into this whole ES6 import/export topic and can contribute something to this.

**Comment by paxperscientiam** [comment]
I was under the impression this would be fixed in 6.5.0; it seems the problem remains.

**Comment by DanielRuf** [comment]
Can you share your package.json and webpack config?

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/pull/11445 was merged and released.

If there are new related issues please open a new issue with all relevant details.

**Comment by javierjulio** [comment]
This issue still remains. I actually have the exact same setup. I only use the Reveal plugin when it comes to Foundation JS. In v6.5.3, with Parceljs, using the same import it actually includes the full library, not just what's required for using Reveal.

Using [the documented approach in the tree shaking section](https://foundation.zurb.com/sites/docs/javascript.html#tree-shaking) doesn't work either (the second part in that section).

The only way I think I've been able to get Reveal to work with defaults and to not include the full Foundation JS library is to do the following:

```
import { Foundation } from 'foundation-sites/js/foundation.core';
import { Reveal } from 'foundation-sites/js/foundation.reveal';
Foundation.addToJquery($);
Foundation.plugin(Reveal, 'Reveal');
$(document).foundation();
```

I'm not sure if that's expected or intentional. Another thing too is that even if this is what I have to do I don't know what else I'm missing if other behavior from that plugin doesn't work as expected.

**Comment by DanielRuf** [comment]
Hi @javierjulio,

as mentioned in the docs it may depend on the config of your bundler.

The plugin itself resolves its dependencies.
See https://github.com/zurb/foundation-sites/blob/develop/js/foundation.reveal.js#L3-L10

**Comment by javierjulio** [comment]
@DanielRuf yes that's why I commented here. I expected it to resolve its dependencies since I know it does in the plugin file. I wasn't sure what's wrong. The thing is Parcel is zero config and uses webpack but if it doesn't resolve, what does any config have to be? If it would require config shouldn't it be documented?

**Comment by DanielRuf** [comment]
I can not answer this as I do not use or know Parcel. You might want to ask in their communities (Gitter, Slack, GitHub, ...).

**Comment by WestMec200** [comment]
@javiercejudo I've only been working with Parcel for about 24H but so far I've noticed a lot of serious issues where I basically have to provide the path all the way back to the node_modules. I'm sure it's probably a configuration issue but Parcel is supposed to be zero-config...

```scss
@import 'settings';
@import 'node_modules/foundation-sites/scss/foundation';
```
`.posthtmlrc.js`
```js
module.exports = {
  plugins:
    [
      require('posthtml-include')({ root: './src/' }),
      require('posthtml-expressions')(),
    ]
}
```

If you figure out a better way let me know because I'm been rewriting the [zurb template](https://github.com/zurb/foundation-zurb-template) with ParcelJS, scss and PostHtml to replace Panini. It's way faster and still works with the cli and building-blocks.

<img width="250" alt="Screen Shot 2019-08-30 at 7 55 41 PM" src="https://user-images.githubusercontent.com/52793815/64058461-46678880-cb60-11e9-84d2-5de01032e597.png">

**Comment by DanielRuf** [comment]
Regarding Sass, node-sass supports resolvement via config and `~packagename`.

**Comment by DanielRuf** [comment]
In this case please ask the ParcelJS creators and open an issue there. We can not provide support for other tools which are not maintained by us.

**Comment by javierjulio** [comment]
@WestMec200 all you need is a `.sassrc` file in the root directory of your project with the following contents:
```json
{
  "includePaths": [ "node_modules" ]
}
```
That way in your SASS code you can change the import to be:
```sass
@import './foundation-sites/scss/foundation';
```
It should work fine from there.
