### ISSUE TITLE
[Installation] Installation not fully documented

### ISSUE THREAD

**Issue by lukos** [zurb/foundation-sites#11432]
## Expected Behavior
I should be able to follow the instructions from the [web site](https://foundation.zurb.com/sites/docs/installation.html) (using Foundation-CLI) and those in readme.md in the zurb full site template, pretty much word-for-word from and end up with a working site.

## Current Behavior
- Running `foundation new` causes errors if python is not installed
- After installing python using npm, I followed the instructions in readme.md in the template and running `yarn` causes 'yarn' is not recognized as an internal or external command

## Possible Solution
If someone tried this on a clean machine, they would know what elements are missing and update the documentation to include pre-requisites with links.

## Test Case and/or Steps to Reproduce (for bugs)
How to reproduce:
1. Clean build of Windows 10 (mine is not a clean build but is still missing the pre-reqs)
2. Run `foundation new` and observe errors due to missing python install
3. After installing windows-build-tools using npm, run yarn in the root directory as described in readme.md and observe that yarn is not a known command

## Context
My first attempt to create a blank foundation site to evaluate it as a framework

## Your Environment
- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): N/A
- Operating System and version (desktop or mobile): Windows 10 1803 desktop
- Link to your project: N/A

## Checklist (all required):
- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is fully and correctly filled.

**Comment by DanielRuf** [comment]
> causes errors if python is not installed

I guess you mean node-gyp and its Python dependency.

Please try `yarn global add windows-build-tools` or `npm i -g windows-build-tools`.

**Comment by DanielRuf** [comment]
And it seems like yarn was not correctly installed or the terminal session / computer not restarted (yarn is probably not in your PATH variable).

**Comment by lukos** [comment]
`yarn` runs after I ran `npm install yarn -g` without restarting the console window but now yarn errors because it can't find python, although I installed it using windows-built-tools and that fixed the node-gyp error. I'm currently searching for where python was installed so I can modify the PATH.

**Comment by DanielRuf** [comment]
In general it is recommended to install yarn using the msi installer and normally the PATH should be adjusted by the windows-build-tools script (afaik).

Often it is in C:/Python or similar.

**Comment by lukos** [comment]
I can't find Python but I will attempt to install it from the web. Either way, the original issue is that the instructions are missing a lot of information to make installation foundation easy for newbs and people like me evaluating it. It would be a shame if people passed it by just because it was so hard to get working.

**Comment by lukos** [comment]
It doesn't have to be detailed instructions but the readme.md already mentions git and nodejs as requirements so it wouldn't be too hard to say that you need (or might need) python 2.7 and yarn in order to use the instructions?

It's not a big deal for people really used to node development but although I have been developing for 20 years, I don't know what yarn is, the right way to install it, which version of python to use (v2 vs v3) etc. and many complete newbs would struggle much more than me.

Compare to something like Yii, which has no external dependencies and installs directly from composer with a single line of code and that is a big tick for people learning?

**Comment by DanielRuf** [comment]
> yarn in order to use the instructions?

yarn is not needed as you can also use npm which comes bundled with Node.js.

**Comment by DanielRuf** [comment]
> which version of python to use (v2 vs v3)

2

**Comment by cnc137** [comment]
I agree with @lukos on this topic.

### A Little History

I have been using Zurb Foundation since version 4 back in 2013 for client projects and really like it. I have been very happy using it to build websites over the past 5 years, but I have to admit that I struggled recently getting Foundation up and running on my new Windows 10 computer. 

Up until last week I used Foundation on my Hackintosh running OS X Mavericks. I recently built a new computer to create a new Hackintosh that I had up and running, but ultimately decided to switch to Windows 10 for easier OS updates related to security and other things. My goal is to install MacOS in a Virtual Machine for testing within my Windows 10 environment instead of relying on a Hackintosh for client projects.

I think I ran into problems with getting Foundation working on my Hackintosh in the past also. I vaguely remember needing to install Ruby and learning about Bundler, Compass, Grunt, and other things for a previous version of Foundation to work. This isn't just a Windows problem, but it can be frustrating when you think something is going to be simple to install and it ends up taking you hours of debugging and research to get it working. Like lukos mentioned, I can see where some people would give up and move on to something else.

### Zurb Foundation and Windows 10  Installation Problems

I have built, configured, used, and supported custom computers with Windows, MacOS, and Linux for almost 30 years, but I still ran into trouble when trying to get Foundation working on my new Windows 10 computer. I agree that some of the problems are related to Node.js and node-gyp on Windows and not having Python installed, but it would've been nice if Foundation mentioned those things in the documentation. I found out that I needed Python when I tried to install Foundation and received an error message stating that I didn't have it.

To fix the Python problem I downloaded and installed it from https://www.python.org after searching and reading the following:

- [Zurb Foundation CLI - Finally, a no error install on Windows 10](https://foundation.zurb.com/forum/posts/55733-finally-a-no-error-install-on-windows-10)

The above also mentioned that I needed Python 2.7 instead of the latest version (3.7) that I originally thought about installing.

The forum post above also mentioned using the "Visual C++ 2015 Build Tools", but the link was broken. I ended up searching and found the following that I installed:

- [Microsoft Build Tools 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159)

This got me further, but I was still getting errors. After more online research I found that there is an npm package that installs Python and the Microsoft Build Tools for you and sets up the correct settings and it is located at:

- [Install C++ Build Tools for Windows using npm](https://github.com/felixrieseberg/windows-build-tools)

I installed this and finally the Foundation CLI and the "foundation new" command worked, but I am not totally sure why. 

After getting it all working I tried removing the "Microsoft Build Tools 2015" via "Uninstall or change a program", since I thought it wasn't needed, but then the Foundation CLI installation stopped working. I also tried uninstalling "Microsoft Visual C++ Build Tools" and then reinstalling it via the npm command, but the Foundation installation still wouldn't work. I ended up installing them both again and everything started working again. I think I even had to install "Microsoft Build Tools 2015" first to get everything to work without errors. I hate installing things without knowing why, but it is working, so I guess I shouldn't complain. 

This took me a few hours to figure out and was very frustrating, since I had Foundation working on my old Hackintosh and thought it would be easy to get running on my Windows 10 machine based on the simple instructions in the Foundations documentation.

### "foundation new" Problem

I still ran into problems after getting everything working though. 

When you currently run "foundation new" it downloads and installs the latest version of Foundation on GitHub, which is v6.5.0-rc.2, but that version is NOT recommended for production environments. I tried researching how to get "foundation new" to download a previous version (6.4.3) and it looks like that is not an option. 

I ended up using the following to download the latest version of Foundation:

`git clone https://github.com/zurb/foundation-zurb-template project-folder-name`

Then I used the following command to check out an older version:

`git checkout e78b9421b0eeb3c7315f2a7402654480969e25db`

I found this older version by doing more research online to figure out how to check out an older version from GitHub and by running the following command to find the correct hash to check out:

`git log`

After all of this I ran the following command to install all the node modules:

`npm install`

Then I used the following command and version 6.4.3 was up and running:

`foundation watch`

You can also use the following command instead of "foundation watch" if you don't have the Foundation CLI installed:

`npm start`

The "npm install" and "npm start" isn't mentioned in the online documentation at https://foundation.zurb.com/sites/docs/installation.html, but I found it on https://github.com/zurb/foundation-sites.

### nodule_modules - 17MB vs 329MB

As a side note, I noticed that when I used "foundation new" and installed the site using the Foundation CLI it downloaded everything and the "node_modules" directory is only 17.3MB and only includes the modules that are listed in the "package.json" file. When I use "npm install" to install everything and get Foundation up and running the "node_modules" directory has a ton of modules in it and is 329MB. I noticed this on my Hackintosh under OS X also, so this is not a Windows 10 problem. 

Every new site I work on using the Zurb Foundation framework has the potential to be 330MB+. I know I have a 2TB hard drive, but 3 sites will take up almost 1GB of my total 2,000GB. I read that this is maybe a Node.js and npm problem, but I find it interesting that the Foundation CLI is able to make the site work with 312MB less stuff in the "node_modules" directory compared to setting up the site with "npm install". 

Is this something that can be fixed or is there a way to install via "npm install" and use what "foundation new" is using to avoid all the extra modules being installed?

### Additional Windows Support Information

I also found the following during my research that might help people having trouble with getting Foundation, Node.js, npm, etc. working on Windows:

- [npm-windows-upgrade](https://github.com/felixrieseberg/npm-windows-upgrade) - Use this to upgrade npm on Windows correctly.
- [Configuring your Windows development environment](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#configuring-your-windows-development-environment) - Tips for setting up Node.js on Microsoft Windows
- [Microsoft + Node.js Guidelines](https://github.com/Microsoft/nodejs-guidelines) - Tips, tricks, and resources for working with Node.js and Windows.

### Conclusion

I think this covers everything I ran into while trying to get my Foundation projects up and running again on my new Windows 10 system. Luckily, I had a little extra time this week to focus on getting this all figured out. If I had major client projects due this week I would've been even more frustrated that it took so long to get everything up and running, especially when the Zurb Foundation documentation makes it sound like it should take about 5 or 10 minutes to run two commands and be up and running.

I understand that you don't want to go down the path of explaining every detail on how to configure a Windows, Mac or Linux system to work with Node.js, npm, and Zurb Foundation. This is a lot to include, maintain, and support to help people use Zurb Foundation, but it might be helpful if you linked to some additional online resources like mentioned above in the documentation. This would at least point people in the right direction if they run into problems like lukos and I did while trying to get Foundation working.

**Comment by DanielRuf** [comment]
> if they run into problems like lukos and I did while trying to get Foundation working.

We mainly have the issue tracker for this as the platforms are very different and also the preconditions and can often change (eg the steps to get node-gyp running).

In general these (node-gyp and others) also have issue trackers which explain the solutions in detail.

macOS comes preinstalled with Python 2 and Windows users already often use windows-build-tools.

Still, node-gyp is one of the things that Ryan Dahl regrets and it was not used by Google anymore, after Node.js integrated it.

**Comment by cnc137** [comment]
I tried the `npm i foundation-sites@6.4.3` command before and tried it again now and received the following messages:

`
PS D:\Users\cnc137\Documents\Projects\foundation-test> npm i foundation-sites@6.4.3
npm WARN saveError ENOENT: no such file or directory, open 'D:\Users\cnc137\Documents\Projects\foundation-test\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'D:\Users\cnc137\Documents\Projects\foundation-test\package.json'
npm WARN wave-makers No description
npm WARN wave-makers No repository field.
npm WARN wave-makers No README data
npm WARN wave-makers No license field.

+ foundation-sites@6.4.3
added 3 packages from 3 contributors and audited 3 packages in 1.177s
found 0 vulnerabilities
`

This is why I went down the path of determining the 6.4.3 version via `git log` and checking it out the way I mentioned above.

When I run the  `npm i foundation-sites@6.4.3` command I only get the following directories and files in my current working directory:

- node_modules
--- foundation-sites
--- jquery
--- what-input
- package-lock.json

This is not enough to allow `npm start` to function and load Browsersync and other things to work like when you run `foundation new` and then `foundation watch`. From what I have read and seen the `npm i foundation-sites@6.4.3` command allows you to pulled down the necessary files for your own development project, but it expects you to have your own build tools and other things in place to work with it.

Are you suggesting that I run `npm i foundation-sites@6.4.3` after I run the "foundation new" command to pull down the latest Foundation v6.5.0-rc.2 and set up my build environment? I don't think this is the case, but I am not sure how to get the Zurb Template build environment that comes with the `foundation new` command using `npm i foundation-sites@6.4.3`.

**Comment by DanielRuf** [comment]
`foundation new` creates the package.json and lockfile so you can always change the version in the package.json or downgrade.

**Comment by cnc137** [comment]
I created a new test directory and ran `npm init -y` inside of it and it created a "package.json" file in the directory that fixed the warnings above, but I still don't see the full "Zurb Template" after running `npm i foundation-sites@6.4.3`. I also tried running `npm install` after this to see if it would download everything and then tried `npm start` and received an error stating that the "start" script is missing.

I thought about changing the version in "package.json" before going to my `git log` route, but I wasn't sure if running "npm install" after that would work correctly.

Is the following one of the paths you would recommend taking to get to 6.4.3?

1. Run `foundation new`
2. Change version in "package.json"
3. Delete "node_modules" directory
4. Run `npm install`
5. Run `foundation watch`

Will the above work to get the correct files?

This sounds similar to my method above to get Zurb Foundation 6.4.3 working to allow `foundation watch` or `npm start` to work.

This is what @lukos and I were talking about above related to the Foundation documentation. Zurb Foundation is a great product and I really enjoy using it and recommend it to other web designers and developers that I know, but it, along with other web design and development tools, rely on people having knowledge of a lot of things before getting started. This can make it very challenging for someone new trying to jump in.

I have been designing and developing websites and web-based applications since 1997 and have used a lot of tools over the years. Zurb Foundation is one of the better documented solutions I have seen, but it still can be challenging and frustrating sometimes to get things working when you may have different knowledge than someone else that doesn't match up with what you need to get a particular tool up and running. 

I feel like an idiot by stating the problems I have run into above and asking the questions. I feel like I should know everything and not have to ask any questions and get frustrated with myself when I don't know everything. The discussions above that we have been having reminds me of the blog post titled ["just"](http://bradfrost.com/blog/post/just/) by Brad Frost. It is hard for everyone to know everything and sometimes we forget as developers that we have a lot of knowledge in our heads that others may not have when explaining and documenting things.

I have Foundation 6.4.3 running in my development environment by running the commands I mentioned above in my first post. I also pulled down a previous project based on Foundation 6.4.3 from my Git repository to get started, so I don't need to get 6.4.3 working. 

I just (no pun intended) wanted to let you know about my troubles and to give feedback on what others might be running into when trying to get Zurb Foundation up and running. I also wanted to point out that people trying Zurb Foundation for the first time right now and running the `foundation new` command are getting Foundation v6.5.0-rc.2, which is not recommended for production environments and there is not an easy way to switch to 6.4.3 for them.

I hope everything above makes sense and I appreciate your help and the Zurb Foundation project and community in general. I just wanted to document my path to getting Zurb Foundation up and running again on my new Windows 10 system and hopefully it helps someone understand what to do and not to do to get it working.

**Comment by DanielRuf** [comment]
You only get the template with `foundation new` in an empty folder or by cloning the wanted template from https://github.com/zurb

**Comment by DanielRuf** [comment]
Run foundation new
Change version in "package.json" to ~6.4.3
Run npm ci (npm 6+ required)
Run foundation watch

**Comment by DanielRuf** [comment]
We also have a Gitter channel where everyone tries to help which is often better than the normal issue tracker.

**Comment by cnc137** [comment]
I tried the commands above and here are the results:

1. Run `foundation new` - WORKED
2. Changed "package.json" from "~6.4.1" to "~6.4.3" in the "dependencies" section - WORKED
3. Run `npm ci` - ERROR

npm WARN prepare removing existing node_modules/ before installation
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
npm ERR!
npm ERR! Missing: gulp@gulpjs/gulp#4.0
npm ERR!

4. Run `foundation watch` - FAILED

I ran `npm install` based on the suggestion in the error message in #3 above and installed everything. Then I ran `foundation watch` and everything worked.

I still ended up with a directory that is 330MB instead of 17MB as mentioned above, but I guess there is no way around that if you use `npm install` to get everything set up instead of just `foundation new`.

**Comment by DanielRuf** [comment]
Well, npm i also installs the devDependencies afaik. The change in the package.json was not actually needed. At least npm has issues with semVer.

Either just `6.4.3` without `~` or `npm i foundation-sites@6.4.3` is needed.

**Comment by DanielRuf** [comment]
I think we should move the current conversation as it is just about the cli.

The size of node_modules does not really matter as you just upload the dist / compiled files, not the dependencies. If the size of it, try pnpm.

**Comment by cnc137** [comment]
The "node_modules" size of 330MB instead of 17MB depending on how I install Foundation is important to me because I have multiple Zurb Foundation projects that I am working on and each of them takes up 330MB on my local hard drive instead of only 17MB. If I have 10 Foundation projects I am working on then I am using 3.3GB of my hard drive instead of 170MB.

This also means that my backup program (Backblaze) is uploading 3.3GB to cloud storage instead of 170MB. Luckily Backblaze offers unlimited storage, but other cloud based backup solutions do not. My local backup to USB is using more space also to back up all these extra files.

Maybe there isn't a way to reduce the size of the "node_modules" folder when using `npm install`, but it is interesting that `foundation new` is able to install differently where it still works, but takes up a lot less hard drive space.

**Comment by SassNinja** [comment]
I agree it should be easier to get foundation-cli running on a clean machine.

I've just tested it on a clean Win10 (only node.js installed) and were facing the same issue because python v2.7 was missing.

I've made a PR to provide more help for windows users #11458

@cnc137 yup, pnpm is great to save space on disk in particular if working on many node projects

**Comment by Syed51214** [comment]
Snooze rules for sleeping. Never let your child sleep in a playard that's full of toys. If you're using it as a portable crib, leave the toys outside. Make .[best pack n play for sleeping](https://bestpacknplays.reviews/)
