### ISSUE TITLE
Add full screen support as an option in off-canvas menu

### ISSUE THREAD

**Issue by Payam121** [zurb/foundation-sites#11503]
## What is missing?

I think supporting of full screen mode in off-canvas can be awesome because instead of menu some features like filtering data or etc need be open in off-canvas menu but be in full screen mode.
...

## What is wrong now ?

Not supported by default.
...

## Possible Solution

...

## Context

...

## Your Environment

- Foundation version(s) used:  6.4.3
- Browser(s) name and version(s): Firefox, Opera(Engine: Chrome 65)
- Device, Operating System and version: Win 7 X64

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Which fullscreen mode do you mean? What prevents you to use 100vw and 100vh?

**Comment by Payam121** [comment]
> 
> 
> Which fullscreen mode do you mean? What prevents you to use 100vw and 100vh?

You know, i know that we can customize Off-canvas Sizes with scss and it's awesome feature, but sometimes we force our developer to standard their code with framework that we choose. and i don't like to change default size of zurb foundation. as you know for future automatic update in our websites our goal is minimum changing and updated A.S.A.P

If you mean that i can configure Zurb foundation with other approach instead of changing in settings file, i would be happy to see the standard way for it.

**Comment by DanielRuf** [comment]
> instead of changing in settings file

This is the recommended and official way.

**Comment by SassNinja** [comment]
> but sometimes we force our developer to standard their code with framework that we choose. and i don't like to change default size of zurb foundation – @Payam121 

So you also stay with default colors of the foundation palette and use default settings for everything?
Sounds like a bad choice that makes you quite unflexible imo.

Foundation offers many options to easily customize it (e.g. customize the off-canvas width/height)
I don't recommend to avoid using this just because you're afraid of future updates.

However it doesn't make sense to provide any `.off-canvas-fullwidth` class and increase the CSS size if this can easily be achieved with a setting.
Therefore I'm closing this issue.

**Comment by Payam121** [comment]
Thanks guys
