### ISSUE TITLE
Documentation: Off-canvas events are improperly cased (Typo)

### ISSUE THREAD

**Issue by ogzcoder** [zurb/foundation-sites#11523]
## Description
 In the docs for Foundation 6 Off-canvas component it lists the event triggers to listen for as:

`opened.zf.offCanvas`  | Fires when the off-canvas menu opens.
`closed.zf.offCanvas`  | Fires when the off-canvas menu opens.

However neither of those events are ever triggered, however, when changed to a lowercase "c" everything works as it is supposed to:

`opened.zf.offcanvas`  | Fires when the off-canvas menu opens.
`closed.zf.offcanvas`  | Fires when the off-canvas menu opens.

## Possible Solution
Change the docs to provide the correct casing for the events

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Please let us know which version of Foundation you use.

We changed the event names in the RC releases and the docs are for the latest release (see top left).

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/blob/develop/js/foundation.offcanvas.js#L405

https://github.com/zurb/foundation-sites/blob/develop-v6.5/js/foundation.offcanvas.js#L354

**Comment by ncoden** [comment]
> cc @ncoden is the event name change not part of the current RC release?

No it is not. It is a breaking change.

This is a documentation issue, related to https://github.com/zurb/foundation-docs/pull/24.

**Comment by DanielRuf** [comment]
@ncoden see the docs.

There is currently `opened.zf.offCanvas` written.

6.5.0 RC3 uses `opened.zf.offcanvas`

**Comment by DanielRuf** [comment]
The docs do not reflect the current events in RC3. So the docs are not consistent atm.

**Comment by ncoden** [comment]
I seen the docs. But this is fixed in RC4 with #11512.
We can keep the issue open until it is released if you want. But until now, the policy was to close them as soon as the related PR is merged. This way, it is easier to be focused on "what should be done".

**Comment by ncoden** [comment]
My bad. I double checked everything and RC4 have the good event names but rely on the wrong version of `foundation-docs`: it uses a commit on `develop` to get the latest fixes but there is also new stuff on `master`.

I took a look at the history of this bug, and we are back at https://github.com/zurb/foundation-sites/issues/10155. OffCanvas events are in CamelCase because we rely on `memberof`, which is the best information about the event namespace we can have (except for OffCanvas). There is too solutions now:
- Change the OffCanvas events documentation to make them part of the `Offcanvas` class (which is not true).
- Add support of event namespaces to Supercollider.

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-sites/pull/11526
