### ISSUE TITLE
Plugin events - differences between already compiled .js and self-compiled with gulp

### ISSUE THREAD

**Issue by bonovski** [zurb/foundation-sites#11615]
I'm developing a **Wordpress** theme and have some issue with how to properly use/import the `.js `part of foundation.

The two scenarios:

**1. Import foundation and compile with gulp:**

`main.js`
```
 import $ from 'jquery';

import whatInput from 'what-input';

window.$ = $;
import Foundation from 'foundation-sites';

window.Foundation.addToJquery(jQuery);

jQuery(document).foundation();
```

`gulpfile.js`
```
function scripts(cb){
	return browserify({
		entries: js.entrySrc
	})
		.transform( babelify, { presets: [ '@babel/preset-env' ] } )
		.bundle()
		.pipe( source(js.src) )
		.pipe( rename( {
			extname: '.min.js'
		} ) )
		.pipe( buffer() )
		.pipe( gulpif( production, stripDebug() ) )
		.pipe( gulpif( !production, sourcemaps.init({ loadMaps: true }) ) )
		.pipe( gulpif( production, uglify() ) )
		.pipe( sourcemaps.write( '.' ) )
		.pipe( gulp.dest( js.dest ) )
		.pipe( notify ({ message: 'Assets compiled!' }) )
		.pipe( browserSync.stream(), cb );
}
```
In an external `3rdparty.js` file which **is not imported** into `main.js`  file I have some ajax code that creates a `data-accordion`. 

Both files are enqueued/loaded directly into worpdress with jQuery as dependency. So it is 

- jquery (wordpress version - noConflict)
- main.js
- 3rdparty.js

When an `accordion-item` is opened the item should be populated with ajax data. 
To achieve this we are listening for `down.zf.accordion` to trigger the ajax call.

The problem is that this event **never fires**, I have the same issue with `open.zf.reveal`.

Everything else works as expected.

2. **Import already compiled` foundation.min.js `directly in Wordpress.**

The curious thing is that when I load `foundation.min.js` directly into Wordpress both events start firing.

`main.js`
```
 import $ from 'jquery';

import whatInput from 'what-input';

window.$ = $;

jQuery(document).foundation();
```

Wordpress loads the files in this order:
- jquery (wordpress version - noConflict)
- foundation.min.js
- main.js **(without foundation import)**
- 3rdparty.js

My question now is what is the difference between these two approaches and why is the first scenario not working.

**Comment by DanielRuf** [comment]
In general, there seem to be multiple things not how they should be. `jQuedy` is not defined in your code snippet.

**Comment by DanielRuf** [comment]
In general, there seem to be multiple things not how they should be. `jQuery` is not defined in your code snippet.

**Comment by DanielRuf** [comment]
Take a look at https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/js/lib/foundation-explicit-pieces.js

You are missing probably the core utils and so on.

**Comment by DanielRuf** [comment]
And in contrast, see https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/js/app.js

**Comment by bonovski** [comment]
> And in contrast, see https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/js/app.js

I've been at this for the better part of the week. Trying every possible combination I could find on the net.
This was my starting point. 
```
import $ from 'jquery';

import whatInput from 'what-input';

window.$ = $;

import Foundation from 'foundation-sites';

$(document).foundation();
```

This worked as intended with all my js code I have written so far as.

The problem with this was when I added `3rdparty.js` in the mix.  I got  **_$(...).foundation is not a function_** errors whenever `$('#some-element').foundation()` was initialized in the ajax calls.

So I added the `Foundation.addToJquery($)`

Now the errors were gone and stuff was working, but the events still wouldn't fire.
Then I read that because wordpress uses no.conflict I should replace $ with jQuery.

DId that, everything else was still working except for the events in the `3rdparty.js` file.

There has to be some difference with how the already compiled `foundation.min.js` works compared with my imported one.

**Comment by bonovski** [comment]
6.5.1

**Comment by ncoden** [comment]
> Now the errors were gone and stuff was working, but the events still wouldn't fire.

Could you check the sizes of your files with the different build methods you used? IMHO it looks like multiple versions of jQuery are being imported in your app.

**Comment by ncoden** [comment]
About the differences between the behavior of the pre-bundled vs self-bundled packages, you can take a look at:
- How we build the Foundation bundle: https://github.com/zurb/foundation-sites/blob/develop-v6.5/js/entries/foundation.js
- How we import it later: https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/js/app.js

I took a closer look at your issue and came with the following:

At first you started with:
```js
import Foundation from 'foundation-sites';
```
...but Foundation was not included because the `Foundation` object is not used, so you got the `$(...).foundation is not a function` error (this is an issue we are working on, see https://github.com/zurb/foundation-sites/pull/11607).

Then you used the Foundation object (making it be included) with
```js
Foundation.addToJquery($);
```
...but it looks like `3rdparty.js` is loading its own version of jQuery, preventing him to watch for the Foundation events. This may actually be the expected behavior of "no.conflict".

So here is what you can try:
- Remove `Foundation.addToJquery($);`. As you can see in [foundation.js](https://github.com/zurb/foundation-sites/blob/develop-v6.5/js/entries/foundation.js), the `Foundation` object you import is already initialized with the global `$` object. Use the following:
  ```js
  window.jQuery = $;
  require('foundation-sites');
  ```
  As explained [here](https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/js/app.js#L4), this ensure it to use the global `jQuery` object and forces it to be imported even when not used directly.
- Use jQuery as an external module. This means that instead of including jQuery in the generated file, you import it once separately (like from a [CDN](https://code.jquery.com/)) and use the same jQuery everywhere. See the browserify [external](https://github.com/browserify/browserify#bexternalfile)) option or [https://github.com/thlorenz/browserify-shim](browserify-shim).

**Comment by bonovski** [comment]
Ok, I came to the same conclusion as you @ncoden. 
Thank you for tipping me in the right direction with `browserify-shim`, though.

So, yes. The problem was that in the build process `foundation-sites` includes the `jquery` library from `node-modules` and this creates a conflict with the one wordpress already loads. The pre-built CDN `foundation.min.js` comes without `jquery` bundled and that's why it worked without problems.

I would recommend, though that in the future `jquery` shouldn't be handled like this as a dependency being automatically required by foundation, should be up to the user to implement it in gulp or webpack. Or at least it should be mentioned in the documentation that there could be potential issues when using it with wordpress.

So let's get to the fix:

1. Install `browserify-shim`.

2. Add this to your package.json:

```
"browserify": {
   "transform": [
         "browserify-shim"
        ]
 },
"browserify-shim": {
        "jquery": "global:jQuery"
}
```
3. Because jquery is a dependency of foundation this alone won't work. You have to tell browserify to do this even for dependencies of dependencies.
Add the option `global: true` in your gulp task like this:
```
.transform( babelify, { presets: [ '@babel/preset-env' ] } )
.transform({global: true}, 'browserify-shim')
```
This removes jquery from foundation-sites.
