### ISSUE TITLE
ZURB template uninstallable (advanced installation)

### ISSUE THREAD

**Issue by incognito75** [zurb/foundation-sites#11627]
## What should happen?

Error-free advanced installation of the ZURB Template.

## What happens instead?

npm ERR! code E404
npm ERR! 404 Not Found: har-validator@5.1.2

## Possible Solution

package-lock.json update to other har-validator version - there is no version 5.1.2 
on
https://www.npmjs.com/package/har-validator?activeTab=versions
or
https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. git clone https://github.com/zurb/foundation-zurb-template projectname
2. cd projectname
3. npm install

## Context

...

## Your Environment

...

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
See https://github.com/ahmadnassri/node-har-validator/issues/112

**Comment by incognito75** [comment]
@DanielRuf 
The repo was the only one where I could open an issue related to foundation-sites/foundation-templates. 
Yes, I can regenerate the lock file but shouldn't the file also be regenerated in the repo?!
Thank you.

**Comment by DanielRuf** [comment]
> Yes, I can regenerate the lock file but shouldn't the file also be regenerated in the repo?!

We'll do it with the next release.
Or shall we do a fast patch release @ncoden?

**Comment by ncoden** [comment]
> Or shall we do a fast patch release @ncoden?
I don't really understand the issue. The lockfile of `foundation-sites` is not correct ?

**Comment by DanielRuf** [comment]
> foundation-zurb-template

Search for `har-validator@5.1.2` or `har-validator`.

**Comment by ryancausey** [comment]
This appears to still be an issue when installing the foundation-zurb-template dependencies using NPM. Yarn works for some reason. The foundation-sites lockfiles appear to pin an older version of har-validator, so probably aren't affected.

Is there a plan to update the official foundation-zurb-template lockfiles soon?

**Comment by Geddo** [comment]
"npm install har-validator@latest --save-dev" should help

**Comment by KnobCode** [comment]
I'm also having the same problem with foundation-zurb-template, using git clone and cli as well it ask me to do an npm audit fix I used --force but still need  6 manual fix I notice this when I try to install sweetalert2 



`Binary found at /Users/giovanni/Desktop/zurb/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine
+ har-validator@5.1.3
added 1403 packages from 903 contributors and audited 30918 packages in 14.263s
found 44 vulnerabilities (19 low, 13 moderate, 12 high)
  run `npm audit fix` to fix them, or `npm audit` for details
giovanni-iMac:zurb giovanni$ npm audit fix --force
npm WARN using --force I sure hope you know what you are doing.`
`+ gulp-imagemin@5.0.3
+ js-yaml@3.13.1
added 79 packages from 44 contributors, removed 159 packages, updated 73 packages and moved 2 packages in 89.485s
fixed 38 of 44 vulnerabilities in 30918 scanned packages
  6 vulnerabilities required manual review and could not be updated
  1 package update for 23 vulns involved breaking changes
  (installed due to `--force` option)`

[sweetalert2 copy.pdf](https://github.com/zurb/foundation-sites/files/3086002/sweetalert2.copy.pdf)

**Comment by DanielRuf** [comment]
`npm audit fix` is not recommended.
This will upgrade packages and break things.

Try `snyk` or keep it as is. There are no production facing vulnerabilities.

**Comment by KnobCode** [comment]
I'll try that but the problem is that is not installing the npm package at all no matter how I do it.
