### ISSUE TITLE
Alignment classes don't respect flex direction

### ISSUE THREAD

**Issue by scottsawyer** [zurb/foundation-sites#11772]
## What should happen?

Alignment classes assume flex-dir-row, which should be documented at a minimum, but when combined with flex-dir-column, their meanings are reversed.  The better solution would be for their meaning to remain constant, regardless of the flex direction.  

...

## What happens instead?

When applying flex-dir-column to a flex-container, the alignment classes reverse their meaning.  i.e. "Vertical Alignment" now means "Horizontal Alignment" https://foundation.zurb.com/sites/docs/flexbox-utilities.html#horizontal-alignment

...

## Possible Solution

The mixin for alignment classes should consider the flex-dir-{direction} and {size}-flex-dir-{direction}.  There should be a 1:1 mapping of vertical to horizontal alignment based on the direction of the container.

so, it should output something like:
```
.flex-dir-row.align-middle {
  // default behavior
}
.flex-dir-column.align-middle {
  // vertical alignment becomes horizontal alignment and visa versa
}
.large-flex-dir-row.align-middle {
  // default behavior
}
.large-flex-dir-column.align-middle {
  // swap vertical and horizontal alignments 
}
```

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://codepen.io/anon/pen/xNvgXR

## Context

I am building a UI in a CMS where users can build a page that injects alignment classes into the markup.  There is a field for "Vertical Alignment" and "Horizontal Alignment", however, if they have also selected "Layout: Column", then they get unexpected results. To the users, it appears to not function correctly, since they choose "Vertical Align: Middle", and it horizontally aligns child items.  

...

## Your Environment

- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): Chrome 74
- Device, Operating System and version: Ubuntu 16.04

## Checklist
- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

I couldn't find issues about this topic.

**Comment by rafibomb** [comment]
I'm not seeing the benefits of this proposed change for the framework as a whole.
-  I don't think it's intuitive to change a class's behavior based on another modifier class. It requires deeper understanding of what the classes do rather than understanding how CSS works.
- align-items: center; and justify-content: center; do do exactly the same thing. Align items changes how flex children stretch and do not allow spacing like justify-content (space around, space-between)

This might be a good case for you to have some custom classes for your use in the project. You could share it as a gist for the greater community.
