### ISSUE TITLE
offcanvas programmatic hide doesn't reset aria-expanded

### ISSUE THREAD

**Issue by ErikKrause** [zurb/foundation-sites#5793]
If I toggle an offcanvas menu by clicking or touching inside the exit-off-canvas area, the aria-expanded tag on .left-off-canvas-toggle or .right-off-canvas-toggle is set to false. If I toggle the menu using $('.inner-wrap').foundation('offcanvas', 'hide', 'move-right'); (f.e.), aria-expanded stays true.

BTW.: $('.off-canvas-wrap').foundation('offcanvas', 'hide', 'move-right'); like described in the docs does not work (for me). It closes the menu but after that it doesn't react any more.

**Comment by ejwaibel** [comment]
+1 This is also not working for me in version 5.5.2

**Comment by fiasst** [comment]
I found this was a problem recently where the "offcanvas" would only open and close once then fail on click. It turned out to be event bubbling. Below is a potential patch:

S(this.scope).off('.offcanvas')
        .on('click.fndtn.offcanvas', '.left-off-canvas-toggle', function (e) {
            e.stopPropagation();this fixed the issue
            self.click_toggle_class(e, move_class + right_postfix);

**Comment by zurbchris** [comment]
To fix this would require a pretty major overhaul of the events function for off-canvas. That being the case, I doubt we folks at ZURB will have time to fix this issue properly. If anyone would like to submit a pull request for it, however, I'd be interested to see it. 

In any case, this issue is stale, if anyone wants to reopen, feel free, but I'm considering this a non-vital bug at this point. Thanks for your input folks.
