### ISSUE TITLE
Query string breaks deep linking hash.

### ISSUE THREAD

**Issue by DAC84** [zurb/foundation-sites#6476]
When adding a query string i.e. for tracking an exception is thrown in foundation.js:

    Line 64: Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Document': '#community?utm_source=email&utm_medium=events&utm_campaign=email' is not a valid selector.

Whilst I'm working on a fix I wondered if there was an existing workaround that I may of missed?

**Comment by nibelune** [comment]
Same issue here... if you found a solution to that issue please share it :)

**Comment by nibelune** [comment]
Hey (and sorry for my poor english),
I had some time to look at this issue a bit more.

It works fine if the order is url?query#hash.
it fails if the order is url#hash?query because location.hash returns EVERYTHING after the # (both # and ? are fragments identifiers so location.hash behavior seems unexpected).

**Comment by DAC84** [comment]
Apologies for not replying sooner and thanks for the update.

I still haven't had time to resolve the issue but your findings seem to explain it, although as you say the behaviour seems unexpected.

I'll try swapping them around in my code and see how that goes.

**Comment by zurbchris** [comment]
This issue is stale, so I'm closing it, sorry for the lengthy delay in response. 
In this case, however, there's only so much we can do to make it easy for you, I'm hoping the reversal of order worked well.
