### ISSUE TITLE
Invalid margin from the top when button near input, Chrome.

### ISSUE THREAD

**Issue by AleshaOleg** [zurb/foundation-sites#6541]
Hey, I'm freshman in Foundation and today decided to start use it. I opened "Getting started" and in "What Comes With Foundation?" > "Navigation" I saw a button near input (see attached image). In Chrome button have too bit padding-top. I I fitted value for it. The perfect value: 0.40625rem.
I repeat - I the freshman in Foundation. Maybe I don't understand the whole structure of it, but it looks horrible.

Can I make pull request which will change this padding-top (and padding-bottom for synchronous)?

    .top-bar .button, .top-bar button {
        font-size: 0.75rem;
        margin-bottom: 0;
        padding-bottom: 0.40556rem;
        padding-top: 0.40625rem;
    }

![capture](https://cloud.githubusercontent.com/assets/1459899/7548138/26595ae8-f606-11e4-8a18-b2aa14a18eac.PNG)

Thanks! With best regards, Oleh Aloshkin.

**Comment by rafibomb** [comment]
I dowloaded a fresh copy of 5.5.2 and added the workspace template into the index. We cannot replicate this.
![screen shot 2015-05-12 at 4 48 37 pm](https://cloud.githubusercontent.com/assets/5652085/7601092/0b6786f6-f8c7-11e4-99d1-8f6253d296d0.png)

The docs are also using the same CSS from the latest version. 

What browser can you replicate this on? Are you using the latest version?

**Comment by AleshaOleg** [comment]
I have Windows 7 x64, Chrome version is 42.0.2311.152 m (latest). Also I have a classical them of Windows, but I don't think this problem is because of this.
![image](https://cloud.githubusercontent.com/assets/1459899/7607059/24fc4c78-f967-11e4-9c21-aac92476fd55.png)

So, I downloaded this and there's no problem there. This problem just only in docs, I don't know what it is connected. I'll try to find it in the near future. Please do not close the issue.

**Comment by gakimball** [comment]
This issue is pretty old, so let's close the book on it.

We've been plagued by this issue for a while, and tried a few times to fix it. Ultimately, it's proven very difficult to consistently fix, because of differences in how browsers round pixels. Some will round up, some down, and some round to a different number of decimal places.

With that in mind, we've unfortunately had to sort of live with that 1 pixel difference. Since Foundation 5 is now EOL, we're only fixing critical bugs.
