### ISSUE TITLE
slider.js undefined property

### ISSUE THREAD

**Issue by jovpet** [zurb/foundation-sites#6588]
I'am receiving this console error output `foundation.slider.js:44 Uncaught TypeError: Cannot read property 'vertical' of undefined`
I am quite sure I've set up everything fine. The thing is that slider works, but sometimes it appears to brake and to output this error. My html is set like this:

``` html
<div class="range-slider-holder">
    <div class="range-slider" data-slider data-options="vertical: false;">
        <span class="range-slider-handle" role="slider" tabindex="0"><span class="fill">touch</span></span>
        <span class="range-slider-active-segment"></span>
        <input type="hidden">
    </div>
</div>
```

I've tried with and without vertical in options but it was the same. Any ideas?

**Comment by uxtronaut** [comment]
@jovpet if you're still having this issue, check and make sure that your `mousedown.fndtn.slider touchstart.fndtn.slider pointerdown.fndtn.slider` event here https://github.com/zurb/foundation/blob/v5.5.2/js/foundation/foundation.slider.js#L34 is being triggered from the slider handle itself rather than an element within your slider handle.

In my case, I had added icon elements within the `.range-slider-handle` element, so the `event.target` being set here https://github.com/zurb/foundation/blob/v5.5.2/js/foundation/foundation.slider.js#L38 was the icon element rather than the `.range-slider-handle` element.

To fix this I added a check in the `mousedown.fndtn.slider touchstart.fndtn.slider pointerdown.fndtn.slider` event handler:
```javascript
.on('mousedown.fndtn.slider touchstart.fndtn.slider pointerdown.fndtn.slider',
'[' + self.attr_name() + ']:not(.disabled, [disabled]) .range-slider-handle', function (e) {
  if (!self.cache.active) {
    e.preventDefault();
    var $target = $(e.target);

    if (!$target.is('.range-slider-handle')) {
      $target = $target.parents('.range-slider-handle');
    }

    self.set_active_slider($target);
  }
})
```

**Comment by uxtronaut** [comment]
An easier change is to use `e.currentTarget` rather than `e.target` in the handler for `mousedown.fndtn.slider touchstart.fndtn.slider pointerdown.fndtn.slider`

**Comment by daslicious** [comment]
I'm experiencing the same error after I ajax in a range-slider.

**Comment by FeiTeng-Alfred** [comment]
I'm experiencing the same error.

**Comment by daslicious** [comment]
@FeiTeng-Alfred yeah, foundation's slider is jacked.  i went with https://jqueryui.com/slider/ and had a much better experience.

**Comment by nevez** [comment]
I was experiencing the same error with backbone/marionette when redrawing a view containing a slider, but without calling $(document).foundation('slider', 'reflow') on the entire document. Calling "reflow" on the view containing the slider before showing it to screen triggers the error starting from the second redraw on (the first behaves well). Putting the slider on screen and then calling $(document).foundation('slider', 'reflow') solves the problem for me.

**Comment by nileshprolix** [comment]
s
