### ISSUE TITLE
rtl select background image position

### ISSUE THREAD

**Issue by ahmedsaoud31** [zurb/foundation-sites#6656]
background-position: 100% center;

in rtl will be

    background-position: left center;

**Comment by rafibomb** [comment]
Why would it not be the same?

**Comment by ahmedsaoud31** [comment]
because in RTL the text in right side and the arrow should be in the left side

**Comment by gakimball** [comment]
In the latest version of Foundation this is resolved. Here's the commit that fixed it: 80165c4a05627478902c073a546994e7a3b0ba3d

![image](https://cloud.githubusercontent.com/assets/1142001/12491862/1ff6480e-c032-11e5-8b45-7af7ec5e28a1.png)

If you're using the Sass version of Foundation, ensure that the `$text-direction` Sass variable is set to `rtl` instead of `ltr`.
