### ISSUE TITLE
should em-calc() for media queries should ignore $rem-base?

### ISSUE THREAD

**Issue by t-wright** [zurb/foundation-sites#6682]
I may be totally off track on this but the new method for specifying breakpoints in 5.2.2 75a2271b3af9d6062df2150f3f905df2feb7848d uses em-calc() which is sensitive to $rem-base. Since browsers don't use font-size when calculating ems for media queries (https://css-tricks.com/em-based-media-queries-are-based-on/), shouldn't it ignore $rem-base and just use the browser default (16px)? 

Otherwise, if I set `$rem-base` to 20px:

`$medium-breakpoint: em-calc(1024)` = 51.2em as you would expect

But:

`$large-up: "#{$screen} and (min-width:#{lower-bound($large-range)})";`

media query kicks in at 820px (16*51.25)

**Comment by sattes-faction** [comment]
I'm currently having the same problem - I set $rem-base and $base-font-size to 14px and the function does calculate the wrong em-values for this base values. Also `em-calc(640, 16px)` doesn't seem to solve it.

**Comment by Zetberg** [comment]
+1 same issue

**Comment by rafibomb** [comment]
I think the point of using a rem-base is that changing it will affect the layout and breakpoints as well. You can define your breakpoints in px if you want it to be a definitive value.

**Comment by SalahAdDin** [comment]
Use rem please :D

**Comment by t-wright** [comment]
@rafibomb I agree. However I guess that’s my point: it doesn’t appear to affect breakpoints (at least not in the way you’d expect) because we can't control the em base used by media queries in the browser. Also, if the purpose of the em-calc() is to convert a pixel value to an em value, then I don't believe it's doing that correctly in this context. I tend to think by default when defining breakpoints in settings, we should pass a $base-value of 16.

**Comment by brianlenz** [comment]
I would have to agree with the assessment of others here. It does seem like the em-calcs should be based off of the expected default browser font size of 16px.

In any event, it's easy enough to work around. However, there appears to be a bug in the em-calc function in 5.5.3. Specifically:

```
@function em-calc($values, $base-value: $rem-base) {
  $remValues: rem-calc($values, $base-value: $rem-base);
...
```

It seems pointless to have a second argument on the em-calc function if it's not being used, isn't it? I believe that above line should change to:

```
@function em-calc($values, $base-value: $rem-base) {
  $remValues: rem-calc($values, $base-value);
...
```

so that the second argument in em-calc gets properly passed through correctly to rem-calc. As it stands now, we are having to redefine the em-calc function to fix this issue so that we can set the breakpoint and range variables based off of a 16px rem baseline in all cases (independent of $rem-base).

**Comment by gakimball** [comment]
We aren't going to introduce any more breaking changes to Foundation 5, so we're going to close this.

In Foundation 6.1, we simplified how the base font size interacts with rem calculation. `$rem-base` is gone, and `$base-font-size` is used in `rem-calc()`. We also fixed font sizing affecting the grid size and breakpoint widths.

**Comment by SalahAdDin** [comment]
Which use then instead rem-base?
