### ISSUE TITLE
Calling foundation('slider', 'reflow') for sliders in hidden divs does not work

### ISSUE THREAD

**Issue by dmamolina** [zurb/foundation-sites#6702]
The reflow method has to be called when the div containing the slider is visible, otherwise the slider does not work.

Foundation: 5.5.2
Chrome: 43.0.2357.132

Cheers

**Comment by jnemeth** [comment]
Good catch!  Just tested it out and it appears setting the visibility property to hidden does indeed prevent the range slider from working with reflow.

I must admit I cant quite grok why this is happening yet, but if you or anyone else determines where this issue is coming from, please do submit it.  We'll look into it.

**Comment by dragthor** [comment]
Does the example markup look like this?

```html
	<div id="test" style="visibility: hidden">
		<div id="slider" class="range-slider" data-slider data-options="step: 1; start: 1; end: 200">
		  <span class="range-slider-handle" role="slider" tabindex="0"></span>
		  <span class="range-slider-active-segment"></span>
		  <input type="hidden">
		</div>
	</div>
```

**Comment by kelster44** [comment]
Hello,

This has been sent to me accidentally I think. My incident # is 6899 and the text is below. I think this email you sent me has to do with range-slider not what I mentioned below. But thank you for the quick reply!

Hello,
I just bought Clean Html5 Audio Player with Playlist on Envato this morning and already have it working. I am having a couple of issues. I am using Zurb Foundation for grid layout. My header uses data-interchange feature to serve different size images for different devices. This is causing a conflict with the jplayer jquery. If I remove the data-interchange code and just put in a src attribute all works correctly but I want to serve different sizes for devices. When I try validating the html the data-interchange doesn't validate due to mising src attribute. I don't know if that could be causing this weird situation? Basically, I think there is a conflict between the jplayer's jquery and yours. Do you know what it could be? If I remove jplayer jquery code and use Foundation's the header still won't work correctly and it messes up the jplayer. I created several files to illustrate:
scfpapresents.com/stella-music-cds-fj.php (includes only foundation jquery)
scfpapresents.com/stella-music-cds-yourj.php (includes only Clean HTML5 jquery)
scfpapresents.com/stella-music-cds-both.php(includes both jquery)
scfpapresents.com/stella-music-cds.php (includes both but header changed to src)

Thank you for any help you can give me!

**Comment by dmamolina** [comment]
@dragthor the markup is using "display: none;" instead of "visibility"

**Comment by zurbchris** [comment]
Reference #7011 closing. Thanks for the input!
