### ISSUE TITLE
How to keep _settings in sync with components but still keep overrides? Best workflow?

### ISSUE THREAD

**Issue by luxmedia** [zurb/foundation-sites#6941]
Hi everybody,

i really like foundation but i have still a missing part in my perfect workflow: An up-to-date but overrideable _settings.scss (in my case .styl).

Overriding variables in _settings is clean and clear, but what if i (or zurb) change some components and add some variables or alter the default values or add new components. How do i keep that in sync with my _settings.scss but without replacing my overrides? Ok, i could do it manually, but this can not be the final solution even more you have lots of projects.

I am wondering if it would be possible to have something like a "settings-builder", e.g. with grunt. My idea:
A programmatic routine which collects all variables from all /components/*.scss files and puts them commented in the _settings.scss but keeps the overrides.

Or a readonly default _settings.scss with all variables (commented) and a second _settings-override.scss, which just contains your overrides. The downside: To get the overview of all available variables you have to look in the _settings.scss or components.scss again. 
A webform could be the solution. It collects dynamically all variables from the _settings.scss and display them nicely in a "builder-form". You can then check and override the variables you want using the webform. The result will be saved in the _settings.scss or a json or whatever.

What are your workflows or ideas for that.

Regards
Volker

**Comment by rafibomb** [comment]
Couple thoughts on that - In Foundation 6 we've planned carefully about the types of settings that need to be variables and therefor there are more useful and fewer variables.

We've built a tool in our docs to automatically doc document and update the setting file if a variable is added. If one is added, it will be called out in the change log.

Having said that, we do not plan to add more variable often (or ever) so this may be less of a task for people.

We'd be very interested in an automated task to add any missing variable to an existing _settings file and would love to hear more ideas on that.

**Comment by gakimball** [comment]
Here are some steps we're taking to improve use of the settings file in Foundation 6, which is released today:

- The file is now automatically generated, so from our end, maintaining it is easier.
- We're going to be more diligent in our changelogs on what variables are added, removed, or changed. [Here's an example](https://github.com/zurb/foundation-apps/releases/tag/v1.1.0) from Foundation for Apps. (Scroll down to the "Sass Variable Changes" section.)

Due to the lack of structure inherent to a Sass file (or a file in any programming language), it's very difficult for us to create a system that makes keeping that file up to date easy. So we'll do what we can in terms of communicating with developers.
