### ISSUE TITLE
Sass precompiler does not work with abide form error class

### ISSUE THREAD

**Issue by jontro** [zurb/foundation-sites#6942]
Currently when generating the css abide will not generate correct css

`"[data-abide]" .error small.error, "[data-abide]" .error span.error, "[data-abide]" span.error, "[data-abide]" small.error {`

the correct css should look like
`[data-abide] .error small.error, [data-abide] .error span.error, [data-abide] span.error, [data-abide] small.error {`

**Comment by gakimball** [comment]
We tested this in Libsass 3.3.0 and Ruby Sass 3.4.20 yesterday, and both compilers rendered `[data-abide]` without quotes.

I believe the issue was related to a bug in Libsass that's been fixed in more recent versions. Since Foundation 5.5, our recommendation has been to always use the latest versions of Libsass or Ruby Sass.
