### ISSUE TITLE
Documentation Offline

### ISSUE THREAD

**Issue by labae** [zurb/foundation-sites#7005]
Hello, 
have zurb offline documentation and where i can download it.?

**Comment by Deckluhm** [comment]
You can find the documentation here: https://github.com/zurb/foundation/tree/master/doc/pages

Since it is written in markdown, you can easily read it using a markdown reader (if you use an editor like Brackets / Atom, you have packages to preview markdown files, making them nicer to read) or even directly (as markdown is pretty easy to read / understand).

As far as I know, there is no easiest way to download and read the documentation.

**Comment by labae** [comment]
okay..
thanks for your information Mr. Deckluhm

**Comment by Deckluhm** [comment]
@labae: I don't know how I missed it but there is a [section in the README.md](https://github.com/zurb/foundation-sites#view-documentation-locally) that explains how to build the documentation offline. It's a much better solution than the one I gave you previously.

Enjoy!
