### ISSUE TITLE
media-queries ranges bug

### ISSUE THREAD

**Issue by donnervetter** [zurb/foundation-sites#7012]
I've recently had to fix an issue which was caused by media queries - some elements would collapse while others wont appear, the bug occured in a very specific situation - ipad mini landscape, 1024px screen width.

Then i noticed this strange thing in _settings.scss file:

//Media Query Ranges
$small-range: (0em, 40em);
$medium-range: (40.063em, 64em);
$large-range: (64.063em, 90em);
$xlarge-range: (90.063em, 120em);
$xxlarge-range: (120.063em);

There are delays/gaps between media queries, the one between $medium-range and the $large-range was causing my issue which was fixed when i edited the value to 64em, not 64.063 em. 

http://stackoverflow.com/questions/33753830/foundation-media-query-ranges-bug/

Why is that?

**Comment by dan-at-unkubed** [comment]
Does it work if you use 64.0625 instead of 64.063?  0.0625 is 1/16th, which for a default body font size of 16px is 1px.  Rounding the actual, exact value of 1/16 up to 0.063 might have been causing the ipad mini landscape view to render it up to the next pixel value, which would be 0.125, and you'd have a 1px gap in your defined ranges.

Seems to me that if you change the lower value of $large-range to 64, then both ranges would apply if the screen width was exactly 64em.  Have you seen any issues there?

**Comment by zurbchris** [comment]
This is user configurable, and has been resolved in Foundation 6, and would be a core change to Foundation 5 media query handling. Please use a method similar to the one described above. Thanks for the note!
