### ISSUE TITLE
Getting javascript to work?

### ISSUE THREAD

**Issue by phoob** [zurb/foundation-sites#7024]
Trying out Foundation 6.0, but I can't get the Foundation javascript to work. Steps to reproduce:

1. Install foundation-cli
2. run foundation new project, and foundation watch
3. Add a snippet involving javascript to index.html from the foundation 6.0 docs

I get no javascript errors – the javascript files are loading correctly (jquery, foundation.js and app.js) – but the javascript is just simply not activated. What am I doing wrong? When running docs from foundation.zurb.com, the javascript works – so I don't think it is anything wrong with my browser...

**Comment by p-h-i-l** [comment]
same. 

1. bower install foundation-sites
2. cd bower_components/foundation-sites
3. npm install && bower install
4. npm start --> not working | gulp serve etc. not working. 
5. Go into Project, add query and foundation.js in this order before closing body tag.
6. add some markup (top-bar, responsive) 

Result: not working : (

**Comment by colin-marshall** [comment]
@p-h-i-l you are running `npm install && bower install` install from the wrong directory. You should be in the main project folder (the one that bower_components resides in) when you run those.

**Comment by colin-marshall** [comment]
@phoob what is the exact javascript snippet you added and where exactly did you add it?

**Comment by p-h-i-l** [comment]
Hey Colin,

to be exact, i am having a project using KirbyCMS. (getkirby.com).
My bower_components folder is in /root/assets/bower_components. Furthermore i am using CodeKit to preprocess the sass and .js files, since it also supports bower to manage components. 

I am minifying 

- bower_components/jquery/dist/jquery.min.js
- bower_components/foundation-sites/dist/foundation.min.js

into app.min.js , which i am loading before the body closing tag. 
Afterwards i am initialising with $(document).foundation(); 

I also tried to use the non minified jquery and foundation version, but then i received errors where some variables were unknown... like this i don't get any errors, but no .js either. :sob: 

Thanks for you input though ;)
Philipp

**Comment by gakimball** [comment]
I updated the template and it should fix these issues: 7d78382632629a9b40a69696420449ba7dcc0907

You can download a fresh template with `foundation new`, or update the `Gulpfile.js` of your existing template. At the top is the variable `PATHS.javascript`, and you can replace the reference to `bower_components/foundation-sites/dist/foundation.js` with these three lines:

```js
'bower_components/foundation-sites/js/foundation.core.js',
'bower_components/foundation-sites/js/foundation.util.*.js',
'bower_components/foundation-sites/js/foundation.*.js',
```

**Comment by p-h-i-l** [comment]
thanks, that works... not a nice working solution.. : )

**Comment by gakimball** [comment]
Arguably that's probably how it should have been to begin with. We don't necessary want to encourage developers to include every plugin in their final build if they aren't using all of them. By using `foundation-sites/dist/foundation.js` you're always bundling every JS plugin in your final build.

**Comment by p-h-i-l** [comment]
Sure. I understand that. In the beginning of a project it's easier to include everything and just go from there and remove unnecessary stuff before deploying the product.

I got one question, off-topic maybe i can ask it here:

I have an app.scss. In this i am importing the foundation.scss and then including the components. In order to use the settings.scss right --  what would be the correct way?

Make a copy of it near the app.scss and import it in the app scss after including the components? 

Best regards, and thanks a lot for your hard and continuos work in this project!
Philipp

**Comment by p-h-i-l** [comment]
edit: found it in the docs ;)

**Comment by gakimball** [comment]
Always put the settings file before the Foundation import.

```scss
@import 'settings';
@import 'foundation';
```

**Comment by phoob** [comment]
Regarding the original issue: the solution from @gakimball worked for me as well :+1: Thank you for all your hard work – and swift response!
