### ISSUE TITLE
BUG: Responsive Toggle not working!

### ISSUE THREAD

**Issue by anik786** [zurb/foundation-sites#7064]
I have copied the responsive toggle code here:
http://foundation.zurb.com/sites/docs/responsive-navigation.html#responsive-toggle

and included the full CSS and JS, but it doesn't function the way it supposed to. It justs a div that doesn't do any thing (i.e. no toggling and doesn't hide for larger screens).

Here's the code:
http://jsfiddle.net/anik786/aeodhuLp/2/

Resize the browser to see that nothing happens!

**Comment by zurbchris** [comment]
That's an issue we had with mangling the .min file. Fixed yesterday with v6.0.1

**Comment by anik786** [comment]
Thanks, I forgot to copy over the new .min.js file

**Comment by zurbchris** [comment]
Side note, it appears for now that if you use a copy of .min from the customizer, it still won't work. We're working on it.

**Comment by hi2u** [comment]
I'm unsure if there's still a bug here, or if I'm doing something wrong?

I've been trying to get a simple copy and paste of the demo menu from the docs to work in my own simple project over the last couple of days, but I can't get it to work no matter what I do.  I've tried the min and non-min files for 6.0.1 and 6.0.3.  And I've just copy and pasted the demo menu from http://foundation.zurb.com/sites/docs/responsive-navigation.html into a page.  Does it need anything apart from jQuery 2.1.4, foundation.css and foundation.js?  I've also tried removing all my other css and js files. 

The docs don't tell us which files are required for it to work, and it would at least be easier to figure out if I was doing something wrong if the online docs just used the standard foundation files themselves instead of some different customized files like docs.js

I made an offline copy http://foundation.zurb.com/sites/docs/responsive-navigation.html - and without any changes, it works locally.  But it breaks as soon as I remove the custom ./page_files/docs.js javascript file.  So it's hard for me to figure out where the problem is in my own project.
