### ISSUE TITLE
Yeti Launch - Uncaught Exception error message and grayed out files

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites#7090]
I thought I'd give Yeti a whirl. It looks like it will be a fabulous tool.

After uninstalling the older CLI - via terminal as per instructions,  on launch of Yeti - after installing in my Applications. I'm on MAC (OS- EL CAPITAN)

1 -  On launch first time (no previous projects) Uncaught Exception Error
see attached 

yeti launch error.jpg
![yeti launch error](https://cloud.githubusercontent.com/assets/14908417/11314730/8488daba-8fa5-11e5-9d00-99c5f1fcc9c0.jpg)

2 - I click  OK on the error  box and continue to create a NEW PROJECT.
Test Yeti using STARTER 
All seems well - despite the disconcerting exception uncaught.

- Revised below

3 - Click Settings "Gear Icon" > SELECT YOUR PROJECT FOLDER
which I did. See attached.

I have a project but it says under the NEW PROJECT BUTTON

![no projects yet](https://cloud.githubusercontent.com/assets/14908417/11315305/fe97802a-8fac-11e5-9ab2-67b628b0f79c.png)

You don't have any projects yet . . . 

I see this
$ Creating Test Yeti in /Users/iBarb/Desktop/Test_Yeti
$ Finished creating Test Yeti project!
$ Test Yeti launching with livereload.
$ [16:39:57]
$ Using gulpfile ~/Desktop/Test_Yeti/gulpfile.js
$ [16:39:57] Starting 'sass'...
$ [16:39:58] Finished 'sass' after 510 ms
$ [16:39:58] Starting 'default'...

4 -I click FINDER in the left bar.

scss folder in root -
I open it

inside  is:
_settings.scss (this is where i made my background color changes)
app.css

I click Browser - I see the starter template - but no background color changes.

____

Ok - so now I see  there is also the foundation-sites folder . . . .

___

I think what is needed is  accompanying  instructions for yet - besides just - 
DOWNLOAD AND LAUNCH YETI

**Comment by phifa** [comment]
same here

**Comment by erikmellum** [comment]
Projects not created with Yeti Launch do not directly import into it (yet!). As for the javascript error, we are in the process of QAing the patch for this bug. Thanks everyone for letting us know!

**Comment by blynnc** [comment]
I tried it again.Cleaned Yeti out - redownloaded it from http://foundation.zurb.com/sites/docs/
Much better this time. Still get the  Exception Not Found Error,

1 - Initial opening screen - tells you to create the path to your project first. That makes sense.
So I 

1 - create the folder and select it.
2 -  Continue and sign up later
3 - New project button
4 - Basic template
5 - Project Name

Note - Can not create any projects with  an underscore _  
like test_bl, test-bl works.

6 - Create project
7 - Browser - Launches the kitchen sink
8 - Finder - Open test-bl folder, open scss -
Yipee!  No grayed out files and clean install - no extra scss folders or files,  or extra foundation-sites folder.

Yeti terminal says 
$ Creating test-bl in /Users/iBarb/Desktop/test yeti/test-bl
$ Finished creating test-bl project!

Under New Project - test-bl shows. Did not last time even though I followed same process.

9 - FNDER  >  Open _settings.scss file.
(it opens in my TEXT WRANGLER)

Duplicate line
// $body-background: $white;
and remove // and change color to black
 $body-background: $black;

SAVE

RUN PROJECT - 

$ Creating test-bl in /Users/iBarb/Desktop/test yeti/test-bl
$ Finished creating test-bl project!
$ test-bl launching with livereload.
$ [10:27:37]
$ Using gulpfile ~/Desktop/test yeti/test-bl/gulpfile.js
$ [10:27:37] Starting 'sass'...
$ [10:27:38] Finished 'sass' after 537 ms
$ [10:27:38] Starting 'default'...
$ [10:27:38] Finished 'default' after 9.18 ms
$ Watching all sass files for changes!


Note - No variable not found error this time

index is showing in browser - no background color change.

What step am I missing ?

**Comment by blynnc** [comment]
Addendum -

Apps should leave users with a  successful outcome. The design of an app should lead uses through the process and and options. 

So far a great stride was in making the CREATE PATH TO FOLDER the first allowable user interaction -
However  as you can see by my notes above  . . .      a bit more work needs to be done on YETI LAUNCH design and interaction so people have no questions.

**Comment by erikmellum** [comment]
@blynnc Thanks for sharing your experience. 

I think that the reason the background color isn't changing is that it doesn't know what $black is.

I checked, and there is a line a few lines above the background color, that defines the black color. I tested your situation with the $black also uncommented, and it worked. Could you try that and let me know if it solves your problem?

The other issue is that Yeti Launch isn't reporting the scss error of an undefined variable (or anything else). This can give the impression that scss succeeded in compiling, when in reality there is an error. We have patched this so that Yeti Launch does report scss errors . The patch is in QA right now, apologies for any trouble that has caused you. We will be releasing it as soon as we possibly can. Expect it no later than early next week.

Lastly, I agree 100%. The app should leave users with a successful outcome, and guide them through the whole process. We definitely have had some bumps during launch week, but are firmly committed to seeing them through. We want this to be an incredible resource for front end developers, and these small usability issues certainly hamstring its potential. Feedback like yours is helpful for us to bring a great product to the table, so thank you for sharing.

Screenshot of the setting to also uncomment: http://prntscr.com/971g29

Have a happy thanksgiving! 
- Erik

**Comment by blynnc** [comment]
Thank-you!  That fixes my problem and that explanation is also a big stepping stone to guiding me through the rest of the_scss file.  I hope this helps someone new to Foundation 6.   

Underscores _ are a rather common  special character used in naming  files and folder names.   At least I've always used them or a combination of  underscores and dashes. underscore_item-1.jpg or  folder_system-2

Thanks again. Happy Thanksgiving to entire crew.

**Comment by erikmellum** [comment]
Hello everyone,

Hello everyone,

The patch been released! You can download it at http://foundation.zurb.com/develop/yeti-launch.html.

The patch addresses:
Javascript error on startup,
Scss error reporting
Glitch for users with a space in their path trying to open an editor

Big enhancement:
Hosted code integration

A few other minor enhancements:
Allow underscores in project names @blynnc 
Change editor button in settings sidebar

Thanks everyone for your patience,
Erik

**Comment by SalahAdDin** [comment]
whats about yeti for linux?

**Comment by erikmellum** [comment]
We are hoping to add linux support in the future. Be patient, and thanks for letting us know!
