### ISSUE TITLE
[F6}[Drilldown Menu] Drilldown links in submenu li's not working on mobile device

### ISSUE THREAD

**Issue by aibrean** [zurb/foundation-sites#7099]
**How can we reproduce this bug?**

Access a nested drilldown (anything inside of `<ul class="menu vertical" data-submenu>`) and click on any linked li's (not ones with additional sub-menus as I know they aren't supposed to be clickable outside of navigation). They will not load links with a mobile device (tested against iOS and Android).

**What did you expect to happen?**
I expected the link to work

**What happened instead?**
Nothing happens. You can hold on the item and get a window to open, but just clicking does nothing.

**Test case**
Must use iOS/Android device. This can't be replicated on a browser emulator.
http://jsfiddle.net/aibrean/cgq9gy8f/

Click on Level 1 Has Sub and JS Lint link... then Level 3 has sub and anything in there

**Comment by pablocrs** [comment]
I have the same problem with a normal dropdown menu (.menu.dropdown).

Looking for a fix :)

**Comment by pablocrs** [comment]
Just fixed it updating to 6.0.4. Tnx

**Comment by Renkas** [comment]
It's now fixed for dropdown but drilldown still has this problem in 6.0.4. I think this issue was prematurely closed.

Even the example does not work fir me: http://foundation.zurb.com/sites/docs/drilldown-menu.html#

On 1. level clicking on the "Item 4" will make page jump to top (as there's empty anchor). But on sub items nothing happens. In my dev I have real links and have the same issue.

**Comment by mattferderer** [comment]
This issue still appears to be happening on 6.0.5

**Comment by zurbchris** [comment]
Seems to work fine on the docs with iOS 9 Chrome and Safari.

**Comment by Renkas** [comment]
Works fine for me also now. @mattferderer maybe you have not re-compiled the files for you project (I almost forgot to do that)?

**Comment by aibrean** [comment]
Works for me on 6.0.5

**Comment by mattferderer** [comment]
I will try to narrow the reason down then & re-open a new ticket if necessary. Thank you for the feedback.

**Comment by h8h** [comment]
I re-open it since this is still a problem for android browser < 5.6.X and I can provide a solution.

Referencing to [caniuse](http://caniuse.com/#search=transform) android browsers < 5.6.X needs the `webkit-transform` property to work properly. 

I couldn't provide a PR because I don't know if this is a foundation problem and I'm somewhat a bad sass coder. 

I found this line for example: [Line 50 drilldown component](https://github.com/zurb/foundation-sites/blob/develop/scss/components/_drilldown.scss#L50):
```
    &.is-active {
      z-index: 1;
      display: block;
      transform: translateX(if($global-text-direction == ltr, -100%, 100%));
    }

```
after compling it to css the result is:
```
 .is-drilldown-submenu.is-active {
    z-index: 1;
    display: block;
    -ms-transform: translateX(-100%);
        transform: translateX(-100%); }

```

If I manually add  `-webkit-transform: translateX(-100%);`  into the compiled css it worked for me. 

Is transform a sass property that gets compiled into `-ms-transform` and `transform`?
