### ISSUE TITLE
Collapse is not working

### ISSUE THREAD

**Issue by ivanjaros** [zurb/foundation-sites#7148]
Adding collapse class to the row class has no effect.
F603

**Comment by rafibomb** [comment]
See it working on the docs - though the example needs the classes .panel changed to .callout which I just did on the master branch. 

The [Foundation forum](http://foundation.zurb.com/forum/)</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by ivanjaros** [comment]
Hi, I just tried to add collapse class to a row in http://foundation.zurb.com/sites/docs/flex-grid.html and it is not working either so it is a bug.
