### ISSUE TITLE
normalize should be loaded on demand

### ISSUE THREAD

**Issue by fergaldoyle** [zurb/foundation-sites#7159]
To keep things modular and explicit, I tend to `@import 'foundation';` at the top of any file I want to access foundation mixins, functions, variables or media queries. 

But doing this outputs `normalize.css` multiple times in the output CSS. To me, `@import 'foundation';` should generate a blank CSS file, and rules should be only added when we `@include foundation-everything;` or individual `@include foundation-grid;`.

So normalize should also be added by using `@include normalize;`

**Comment by gakimball** [comment]
Good call, I'm amazed this slipped through. I think we can put it into `@include foundation-global-styles`, because Normalize is considered a mandatory piece of the framework.

It's worth noting, though, that because Sass is global by default anyway, your modular approach won't have any benefits. As long as `@import 'foundation'` happens at the top of your main Sass file, you can access all of the framework's variables, mixins, and functions *anywhere*, in any file. (Which isn't really the best thing, but it's how Sass happens to work at the moment.)

**Comment by gakimball** [comment]
Done. Normalize is now baked into `@include foundation-global-styles`.
