### ISSUE TITLE
Failed to install via composer

### ISSUE THREAD

**Issue by nexxome** [zurb/foundation-sites#7205]
I'm not able to install it with composer.
I tried:

composer require zurb/foundation-sites
-> Could not find package zurb/foundation-sites at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

composer require zurb/foundation-sites:6.0.4
-> The requested package zurb/foundation-sites could not be found in any version, there may be a typo in the package name.

I also tried to change the "minimum-stability" option to dev, but also doesnt work.

**Comment by Raphy** [comment]
I had the same issue, then I tried to find out about the issue.
The package is not yet available on Packagist. When you list the packages of Zurb (https://packagist.org/packages/zurb/), the package have not been renamed yet.

That's why !

**Comment by lukashillebrand** [comment]
Any news about this issue?

**Comment by Raphy** [comment]
We have to wait the manual update of the package in Packagist.

**Comment by gakimball** [comment]
I would have preferred to make a new package called `foundation-sites`, but the existing `foundation` package is already using this Git endpoint.

I'm guessing the package isn't updating because the `composer.json` defines the package name as `zurb/foundation-sites` instead of `zurb/foundation`? So if I update that, it should work the next time we tag a release?

**Comment by douglogue** [comment]
@gakimball Any update on this?

**Comment by gakimball** [comment]
@douglogue I need to know from a Composer user what we need to change on our repository to get it updating again. We don't own the package so we can't change anything about it, and we can't register our own because this Git endpoint is already in use by the original `foundation` package.

Read my comment above and let me know if you think that would fix the problem. We're still tagging releases like always, and yet the package isn't updating.

**Comment by gvanto** [comment]
I had same issue, then changed ""zurb/foundation-sites": "*" to "zurb/foundation": "*", and the composer update seems to have worked but I'm curious (and a little worried?) - what is difference between the two?

**Comment by gakimball** [comment]
@gvanto The difference is `zurb/foundation-sites` doesn't exist as far as I know. (Our documentation correctly lists the package as `zurb/foundation`, although our readme did not, so I corrected that: 873387c1a156f1d36364902ae46b4345d00b15e8) Someone else made the package back in the day. We've made a point to use the name `foundation-sites` on all new packages starting with v6, although the Composer package is one we don't have control over.

**Comment by gakimball** [comment]
I'm seeing that version 6.0.6, the latest version of Foundation, is showing up on [Packagist](https://packagist.org/packages/zurb/foundation), so I'm going to close this.

**Comment by michaelze** [comment]
v6.2 seems to be missing on packagist.org.

**Comment by gakimball** [comment]
@michaelze Yep, I only see `6.2.0-rc.1`, but we have `v6.2.0` tagged and in the `master` branch, and Composer is supposed to automatically update, right?
