### ISSUE TITLE
!important for .hide, Do we really need to?

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#7218]
We have had this [discussion before](https://github.com/zurb/foundation-sites/issues/6190) in F5. Must we have `!important` for `.hide`? I realize that there are cases where `!important` is needed but I would rather have another class for situations when you needed a `display:none !important;`. For example, we could have a class of `must-hide` or something similar. 

My biggest problem with `.hide` having an `!important` is the fact that I have used this class for years and use it in conjunction with my javascript. Javascript doesn't override `!important` so I have to either use an inline style or create another class. 

Thank You

**Comment by gakimball** [comment]
We felt it was important to be consistent with visibility classes, so that meant putting `!important` on pretty much everything in the visibility file. Moving from 5 to 6 was the opportunity to do that properly.

If you're using `.hide` in conjunction with JavaScript that manages component state, I'd recommend adding/removing that specific class as part of that.
