### ISSUE TITLE
!default missing from $foundation-colors prevents overridding.

### ISSUE THREAD

**Issue by umutahmet** [zurb/foundation-sites#7219]
Can !default be added to the $foundation-colors list so it can be overridden? 
Thanks

**Comment by dherran** [comment]
This is an odd one. The colours you define in _settings.scss wont be taken into account when generating the $foundation-colors map.

It seems like the map is being rendered in SASS with the default values, even though the settings file is being imported *before* the foundation-global-styles include.

The only solution I found after many tries is to have the !default flag in $foundation-colors and redeclare the map inside the settings file. I wonder if there is a way for the $foundation-colors map to grab the colour values already preset in the settings file.

**Comment by umutahmet** [comment]
Yeah, that's exactly how I've got it working. The only other thing I can think of is to create a mixin which can help extend / merge the two maps together, but this seems overkill. "$button-sizes" mapping is another example, except this time it's set up with the !default flag allowing overriding..

**Comment by gakimball** [comment]
`$foundation-colors` is considered to be an internal variable—we use it in `@each` loops to generate coloring classes for buttons, callouts, and so on. It has no `!default` flag because it's intentionally not in the settings file. If you want to change the default colors, use the variables themselves, like `$primary-color` and `$alert-color` and so on. Or are you saying you did this and colors still aren't changing?

**Comment by dherran** [comment]
@gakimball exactly, I changed the colours, like $alert-color, $primary-color, etc and nothing happens. SASS is still taking the default values for these vars whenever $foundation-colors is used.

You can try for example the callouts. If you change the $alert-color to a different shade of red, it will be ignored and the default value in _global.scss will be rendered. You will see the callout rendered with the default shade of red instead of the new one.

**Comment by andycochran** [comment]
This give me an idea. Could we instead define our own color palette quantities? Not every project will use all the buttons/badges/labels/callouts/etc generated by the various colors. Of course, `$primary-color` is required, as it's used outside of `@each` loops. But I can imagine projects that would benefit by removing the cruft other colors make, or by defining their own color palette in the settings.

For instance, if I don't need alerts, but I do need additional colors to match brand guidelines:  
```
$foundation-colors: (
  secondary: #ff19f0,
  tertiary: #9c45ff,
  success: #3adb76,
//  alert: #ec5840,
  warning: #ffae00,
);
```
Then all the `@each` loops could loop through both `$primary-color` and `$foundation-colors`.

**Comment by gakimball** [comment]
@andycochran Interesting idea, similar to how the breakpoints work. I'll see what the team thinks.

**Comment by andycochran** [comment]
@gakimball That's exactly what I was thinking (similar to breakpoints). I imagine you could slim customizations even further by including color palette variables in `_settings.scss` for applicable components that would `!default` to using the whole defined palette in their `@each` loops, but could be overridden to use only select colors from the palette. This way I could have 5+ different button colors but only 1 badge color, 2 label colors, 1 callout color, etc…

**Comment by mediabeastnz** [comment]
Is this why my colour for primary-color in settings won't work?

**Comment by zurbrandon** [comment]
Yeah, i'm down with that is along as it's non-breaking.

**Comment by gakimball** [comment]
We had some internal discussion about this, and here's our idea:

How about, instead of having both the separate color variables—`$primary-color`, `$secondary-color`, etc.—and the `$foundation-colors` map, we shift people towards only using the map?

This means we're giving people just one way to define colors, and they get the added benefit of being able to define their own palette.

To keep backwards-compatibility (and to keep developers sane), the `$primary-color` etc. color variables still work, but they reference the values in the map.

```scss
$foundation-colors: (
  primary: #fff,
  secondary: #fff,
  success: #fff,
  alert: #fff,
  warning: #fff,
) !default;

$primary-color: map-get($foundation-colors, primary);
$secondary-color: map-get($foundation-colors, secondary);
$success-color: map-get($foundation-colors, success);
$alert-color: map-get($foundation-colors, alert);
$warning-color: map-get($foundation-colors, warning);
```

In the interim, we've merged #7637 so developers can modify `$foundation-colors`, but for 6.2, we're going to look into transitioning developers to *only* using the palette.

**Comment by umutahmet** [comment]
Sweet! This is a nice update, I'm interested to see how you take this forward. I personally like to customise foundation at it's core instead of writing themes to overwrite base styles.. I know this is what css is for but why write more when you don't need to :)

Thanks

**Comment by andycochran** [comment]
:+1: to map-only color palette.

**Comment by andycochran** [comment]
Not sure if SASS can do this, but could you create the backwards-compatible variables dynamically? 
```
@each $color-name, $color in $foundation-colors {
    $#{$color-name}-color: $color; 
}
```

**Comment by gakimball** [comment]
Sass doesn't support dynamically-named variables unfortunately.

**Comment by gakimball** [comment]
Finalized the new `$foundation-palette` feature on the `v2` branch: 27cd825ee585e24e308cdcda84faade5bf5331c4 fb1c8567cd1e876f5b2c3b3b1aa8e1f0dd66f164

**Comment by titaniumbones** [comment]
Would it not make a lot of sense to also define colors like $white, $body-background, $titlebar-color, $topbar-color, etc., in the palette? There do seem to be a number of somewhat hidden colors in the foundation schme that the five main color variables don't cover.  

At a minimum, I find the following colors are all set directly to hex values in scss/:

```
 > ag '#[0-9]'                        
components/_button.scss
35:$button-color-alt: #000 !default;

settings/_settings.scss
50:$primary-color: #2199e8;
51:$secondary-color: #777;
52:$success-color: #3adb76;
57:$dark-gray: #8a8a8a;
58:$black: #0a0a0a;
235:$button-color-alt: #000;
323:$helptext-color: #333;
335:$select-triangle-color: #333;

forms/_help-text.scss
11:$helptext-color: #333 !default;

forms/_select.scss
15:$select-triangle-color: #333 !default;

typography/_print.scss
52:      border: 1px solid #999;

util/_value.scss
90:    color: #000,

_global.scss
26:  primary: #2199e8,
27:  secondary: #777,
28:  success: #3adb76,
43:$dark-gray: #8a8a8a !default;
47:$black: #0a0a0a !default;
358:    color: #000;
```
Is there a good way to add some of these to the palette?

**Comment by gakimball** [comment]
@titaniumbones The blacks, whites, and grays will stay out of the palette, because they're being used to print modifier CSS classes like `.primary`, `.secondary`, etc.

However, any instance where we're using a hex value instead of a color variable should be changed. We should only be using the color variables in our codebase, to ensure everything stays consistent.

**Comment by gakimball** [comment]
@titaniumbones Replaced those hardcoded colors: 887afea9aac345ef4f70046c14fb60d1053d6459

**Comment by titaniumbones** [comment]
@gakimball wow, fantastic, thanks.

**Comment by andycochran** [comment]
Hmm. @gakimball, maybe @titaniumbones has a point? Above it's mentioned, "we're giving people just one way to define colors." Except some colors won't be defined that way. You could do a map to define all the colors and a list to define which of those colors to use for components: 

```scss
$foundation-colors: (
  light-gray: #e6e6e6;
  medium-gray: #cacaca;
  dark-gray: #8a8a8a;
  black: #0a0a0a;
  white: #fefefe;
  primary: #fff,
  secondary: #ff19f0,
  success: #3adb76,
  alert: #ec5840,
  warning: #ffae00,
) !default;

$light-gray: map-get($foundation-colors, light-gray);
$medium-gray: map-get($foundation-colors, medium-gray);
$dark-gray: map-get($foundation-colors, dark-gray);
$black: map-get($foundation-colors, black);
$white: map-get($foundation-colors, white);
$primary-color: map-get($foundation-colors, primary);
$secondary-color: map-get($foundation-colors, secondary);
$success-color: map-get($foundation-colors, success);
$alert-color: map-get($foundation-colors, alert);
$warning-color: map-get($foundation-colors, warning);

$foundation-component-colors: (
  primary,
  secondary,
  success,
  alert,
) !default;

```
