### ISSUE TITLE
[Responsive Navigation] Menu items mis-aligned after window resized

### ISSUE THREAD

**Issue by clivewalker** [zurb/foundation-sites#7235]
**How can we reproduce this bug?**
1. Resize the browser window smaller (Safari)
2. Make it larger again

**What did you expect to happen?**
Navigation Items 1, 2 and 3 should be in a row

**What happened instead?**
Items 2 and 3 are positioned below Item 1 until the page is reloaded

**Comment by clivewalker** [comment]
<img width="917" alt="screen shot 2015-11-26 at 17 56 50" src="https://cloud.githubusercontent.com/assets/2796885/11428776/327249a2-9467-11e5-8881-310f97c9fc2f.png">

**Comment by zurbrandon** [comment]
@zurbchris can we confirm this has been fixed?

**Comment by gakimball** [comment]
This is a Safari-specific bug, where `display: table-cell;` breaks if it's swapped in and out dynamically from media queries. That's what the menu does when it shifts from small to medium here—it goes from `block` to `table-cell`.

Setting the menu itself to `display: table-row` appears to fix the issue, but it opens up a huge can of worms based on my testing.

The only solution, then, might be to revert back to floats for menu, like we did with button group.

**Comment by andycochran** [comment]
Maybe we ditch `table-cell` for inline block. I'm doing a bit of work on Menus + Button Groups, and I'll see about closing this bug with that.

**Comment by andycochran** [comment]
@zurb/yetinauts Some thoughts on which I'd appreciate feedback… 

Currently, menus items use `display:table-cell` to allow for vertical alignment. The most obvious way to close this ticket is to switch to `display:inline-block`. But I'm not sure why we need `vertical-align:middle`, which we'd lose. 

Switching to `display:inline-block` also means revising the method for `.menu.expanded`, which puts `width:100%; display:table;` on the menu. 

Expanded menus could instead use the method that's used for `.button-group.expanded` (a `@for` loop which calculates the percentage width of expanded buttons). This means either setting a new variable for the max number in that loop or using `$buttongroup-expand-max`. 

But all this brings up the existential question for which I've never heard a good answer: What's the difference in a button group and a menu? From what I understand, it's simply semantics and color. 

I'd love to merge the two. But that's a hefty change. I'm up for tackling it, but I'd love to get some feedback and a go-ahead from @Zurb before digging in.

**Comment by brettsmason** [comment]
@andycochran I think we have discussed this before on a few occasions so you probably already know I agree with you :smile: 

I'd definately at the very least like to see `display: inline-block` used on menus as its generally a lot more flexible.

With the expanded method, could we not do something like:

```
.menu {
	display: inline-block;

	&.expanded {
		display: table;

		& > li {
			display: table-cell;
		}
	}
}
```
That way we could benefit from the expanded that table-cell brings, but use inline-block otherwise.

In terms of merging button groups and menus - I have no problem with it at all as long as its clear :+1:

**Comment by andycochran** [comment]
@brettsmason Might what you suggest leave us with the same problem this ticket outlines: `display:table-cell` breaking when it's swapped dynamically via media queries? Regardless, I'd prefer abandoning `table` display altogether.

**Comment by brettsmason** [comment]
@andycochran It would only be effected if using the `.expanded` class, but I agree, remove all of the table stuff is probably best.

**Comment by andycochran** [comment]
@brettsmason Cool. 

When merging the Button Group and Menu methods, we should keep components modular. But I notice that the Button Group component isn't completely modular currently; e.g. you can't use `@import 'components/button-group';` without `@import 'components/button';`. So I was wondering if instead of having two components — Button Group _and_ Menu — we'd just have one. Maybe the Menu component conditionally generates Button Groups _if_ you have included the Button component.

**Comment by getup8** [comment]
Came across this thread as I'm trying to understand why table-cell is used instead of inline-block (the latter seems more intuitive and like the right direction to go for menus; the default menu is actually pretty frustrating to use in simple cases where you want to set margins between things).  Is there another thread or ticket to change all Foundation menus to inline-block?  Is that something you're considering?  And maybe consolidate with button groups in some way.

**Comment by rafibomb** [comment]
Menu was re-written in 6.4 mainly by @brettsmason and I'm not seeing this issue any longer. Closing!
