### ISSUE TITLE
[JS][Dropdown Menu] Potential breaking change for click menu. "disableHover" and "clickOpen" now needed.

### ISSUE THREAD

**Issue by cabdesigns** [zurb/foundation-sites#7244]
As of 6.0.4, if we want to have a dropdown menu open by click, we now have to provide both `data-disable-hover=true` and `data-click-open="true"`.

In 6.0.3, this was achieved by `data-disable-hover=true` alone. See problem below:

```
<ul class="dropdown menu" data-dropdown-menu data-disable-hover="true">
    <li class="has-submenu">
        <a href="#">
            Menu
        </a>
        <ul class="submenu menu vertical" data-submenu>
            <li><a href="#">One</a></li>
            <li><a href="#">Two</a></li>
        </ul>
    </li>
</ul>
```

This may cause issues for users of <6.0.4 who are now upgrading. Was I relying on a bug in 6.0.3? Not sure if this is intentional by design, if so please ignore this issue.

Appreciate all the efforts @zurbchris. First time using Foundation and I'm a big fan!

**Comment by zurbchris** [comment]
Hey @cabdesigns you were sort of relying on a kinda-sorta bug. Dropdown Menus had their quirks, so I went back to the drawing board with some input from the Foundation team and users on gh. There are so many possible interactions with menus (think touch vs non-touch, hover vs no-hover, etc) I decided to add one last option. You can disable hover, you can enable clicks, there is a default action with touch *enabled* browsers, where the submenu will close on subsequent clicks of it's parent. But, since knowing whether or not a device is *actually* touch compatible is nigh-impossible, there's an override available in the options: `forceFollow: true` will cause the linked path to be followed on second click of a menu anchor, regardless of the device or clickOpen state. (clickOpen:false; is overridden if the browser registers as touch, so mobile users aren't locked out of a menu). See #7344 for more.
