### ISSUE TITLE
[Sticky] Issue with sticky block and page content

### ISSUE THREAD

**Issue by foodgy** [zurb/foundation-sites#7250]
Page with products (images): https://output.jsbin.com/fipacugeci
Page with pure text: https://output.jsbin.com/cajexayage/1

First one is bugged for me. Sticky block just stops being sticky :| Any kind of window resize fix this.
Second with text is absolutely fine.

**Comment by rafibomb** [comment]
They both seem to be working. Can you describe the issue and how to replicate it?

**Comment by foodgy** [comment]
>They both seem to be working. Can you describe the issue and how to replicate it?

Open output in a new separate window.

I found out that the reason of this strange sticky block behavior were images loaded from placehold.it (example -- https://placehold.it/300x400).
These images are loaded in s few milliseconds after the page loads. That's why their height is not calculated when rendering the height of the content block.
Anyway, i replaced placehold.it images with static pics from my server and it works fine now.

**Comment by zurbchris** [comment]
Ah yes, I need to add something in the docs for this. Basically, if using non-local assets, you should have something like a window.onload function that will call `sticky._calc(true)` when the window is finished loading resources. 
```js
window.onload = function(){
  $('sticky-selector').foundation('_calc', true);
};
```

**Comment by Plaputta** [comment]
I think I have a related issue (foodgy's examples unfortunately won't load), the suggested fix doesn't help:

http://codepen.io/Plaputta/pen/WrbXZW

The sticky just stops being sticky way too early. Any ideas?

**Comment by zurbchris** [comment]
@Plaputta I've solved your issue, since you're just saying data-sticky, it should stick to the entire document, not just within a range, that was an issue in how that was calculated. The benefit of this fix is it should be silly-simple to make a sticky nav bar now.

@foodgy I am guessing since you haven't commented in a while, you've resolved this issue? Feel free to open a new one if you don't feel your question was adequately answered.
