### ISSUE TITLE
Can grid be configured to use margins rather than padding for gutters

### ISSUE THREAD

**Issue by alexmorris** [zurb/foundation-sites#7267]
Feature request.

**Comment by Renkas** [comment]
Can't see really how. box-sizing: border-box; or any other property wont include margins.

**Comment by alexmorris** [comment]
Can maybe use calc to adjust widths to remove margins from computed width

**Comment by Renkas** [comment]
I don't think that could be reliably done.

This would also add the problem that you could not change margins on the fly - as you can right now with the paddings.

Actually i really can't see any real world use case for that right now. Is there actually?

**Comment by gakimball** [comment]
We considered a margin/calc grid, but decided to keep our padding based grid. The math is *way* easier, and it also makes it easier to keep the width of the column and the size of its gutters separate. This is important because we plan to introduce a responsive gutter feature in 6.1.

The main downside is that you can't combine columns with other components for less markup, but we don't consider this a huge deal. On the contrary, keeping layout elements and other components separate makes more sense to us.

```html
<div class="row">
  <!-- Column component -->
  <div class="column">
    <!-- Callout component -->
    <div class="callout">
    </div>
  </div>
</div>
```
