### ISSUE TITLE
[Drilldown Menu] keeps the highest space

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7271]
**How can we reproduce this bug?**
http://foundation.zurb.com/sites/docs/drilldown-menu.html#basics

the is-drilldown container keeps the highest space of the highest menu

**Comment by aibrean** [comment]
#7070 is related to this.

**Comment by designerno1** [comment]
i think it's different, for me a blank white space after the drilldown menu is keept always

**Comment by zurbchris** [comment]
@designerno1 it seems to me you would prefer the content jump if one menu is longer than another? If that's the case, a pull request adding an option to disable the height matching would be cool to see :smile: 
@aibrean your issue is a little more complicated, but I know a way to fix it. I just need time to dig in to drilldown and accordion menus for a couple days and bring them up to dropdown menu's new swank.(it might not do everything you want it to, but it's fast)

**Comment by zurbrandon** [comment]
I'm going to count this as a difference in how it should work, since i"m not sure how we'd have this behave otherwise. If it wasnlt ass tall as it's child elements then the entire page content now needs to jump down and then back up, which feels worse. 

I'll close this, but feel free to reopen if you have another solution.

**Comment by designerno1** [comment]
an option to let it jump (means height adjust) would be cool
