### ISSUE TITLE
[Menu] span in the <a> tag text 1px down

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7309]
adding a span to the a-TAG of a menu causes the text to jump 1px down see screenshot, the right menu is without span the left with span
```html
<ul id="service-menu" class="horizontal dropdown menu" data-dropdown-menu>
  <li><a href="#"><span class="show-for-large">Home</span></a></li>
  <li><a href="#">Service</a></li>
</ul>
```
![menu-a-span](https://cloud.githubusercontent.com/assets/8417506/11469832/909ef828-9759-11e5-9871-416acff3ec99.jpg)

i thing its because of the
```css
.menu > li > a > span {
  vertical-align: middle;
}
```

**Comment by designerno1** [comment]
seems to be with inline elements i-TAG also drops Text 1px down

**Comment by gakimball** [comment]
Would it make more sense to put `.show-for-large` on the `<li>` itself? Unless you plan on swapping the "Home" text with, say, an icon.

**Comment by designerno1** [comment]
yes because of an icon, and even without the show-for-large the text drops 1px down

**Comment by andycochran** [comment]
Could we change 
`.menu > li > a > span { ... }` to 
`.menu > li > a > i + span { ... }` 
so the vertical-align only applies to icons?

**Comment by gakimball** [comment]
@andycochran Seems sensible, since our markup examples all explicitly require `<img>` or `<i>` *followed by* `<span>`.

I also removed the `>` between `a` and `i`/`img`/`span`. The `>` is mostly needed because menus nest inside of each other, but they don't nest inside of the `<a>`, so it's not possible for styles to leak.

In retrospect, a `.menu-icon` class would have been nice here. Maybe someday in the future...

**Comment by andycochran** [comment]
All we really need is `.menu i + span`, right?

**Comment by gakimball** [comment]
@andycochran For the base styles, yes. For the position styles, they need to be scoped to the `<li>`s of that menu.
