### ISSUE TITLE
Foundation 6.0.4 utils/_selector.scss breaks form text inputs on gulp-sass

### ISSUE THREAD

**Issue by sandermarechal** [zurb/foundation-sites#7312]
This issue is similar to #7204. Foundation 6.0.4 forms fail when compiling with gulp-sass. PR #7131 messed up the quotes in the text-inputs function. Reverting from escaped single quotes back to double quotes fixes the issue.

Why was PR #7131 approved in the first place? CSS style guides predominantly use double-quoted strings, not single-quoted strings.

**Comment by gakimball** [comment]
Not seeing this behavior in gulp-sass 2.1.0, which points to Libsass 3.4.x, which is the version we support.

We prefer single quotes because they're easier to type. We do the same for JavaScript as well. Our [scss-lint.yml](https://github.com/zurb/foundation-sites/blob/develop/config/scss-lint.yml) file documents our preferred ways to write Sass.

**Comment by sandermarechal** [comment]
I am using gulp-sass 2.0.4 with node-sass 3.3.3

**Comment by gakimball** [comment]
You'll need to be on the newest version of Libsass to compile properly. The newest version is at full feature parity with Ruby Sass, which is why we require it.

Upgrade to gulp-sass 2.1.0 to get the newest version.
