### ISSUE TITLE
Adding `_settings.scss` option for Flex grid

### ISSUE THREAD

**Issue by DevanB** [zurb/foundation-sites#7317]
I'm using Foundation for Sites (with Meteor), and was wondering if there will be support for a flex grid opt in option in `_settings.scss` sooner or later?

I am using flex grid, but found I had to `@include` every component in my `app.scss` after `@import`ing Foundation just to be able specify I don't want to use the standard grid and do want to use the new flex grid.

Another option may be to specify `@include foundation-everything-with-flex-grid` or something along those lines.

Thanks for all you all are doing! I love Foundation for Sites!

**Comment by gakimball** [comment]
The flex grid borrows all of its settings from the regular grid, so you can just use those.

We could augment `foundation-everything()` to have a flex grid option, but we also probably don't want to encourage developers to use it, because it prints all of the CSS for every component, regardless of whether or not you're using all of them. We're encouraging developers to focus on slimmer CSS.

**Comment by DevanB** [comment]
This makes perfect sense. Thanks for the clarification @gakimball.
