### ISSUE TITLE
Modal Problem when calling foundation twice

### ISSUE THREAD

**Issue by Miniconi** [zurb/foundation-sites#7362]
Hi, 

I am currently migrating to foundation 6 and I have reached a very annoying problem. 
First of all, this is a angular App, with a quite a lot of data bindings. The DOM is evolving all the time. 
Here is the issue, I several a modals and If I call $(document).foundation() twice the grey background layer stay on the screen even if the modal is closed. So the only thing to do is to refresh the page. 

The problem can be seen on the foundation page. http://foundation.zurb.com/sites/docs/reveal.html

If you call $(document).foundation() on the console, you won't be able to close modals. 

Any help with that?

**Comment by Owlbertz** [comment]
Why are you calling it twice at all?

**Comment by Miniconi** [comment]
Because when new elements are pushed to the DOM, if you want them to be foundation ready you have to call foundation. modal, dropdown etc... Before I did $(document).foundation('reflow') but with the new version it is no longer possible.

**Comment by Miniconi** [comment]
![capture d ecran 2015-12-03 11 48 00](https://cloud.githubusercontent.com/assets/1877121/11558585/c693722c-99b3-11e5-8fea-7525264b16f1.png)

**Comment by Owlbertz** [comment]
I see... Maybe you could create the components when you render the markup? Maybe this pen is helpful: http://codepen.io/zurbchris/pen/YwKvwp?editors=101

**Comment by Miniconi** [comment]
Thanks I will give it a try, sounds like a good solution :-)

**Comment by zurbchris** [comment]
Valid issue, for some reason, Foundation is double initializing modals if you call `$(document).foundation()` multiple times, this could be a slightly larger issue with how we initialize plugins, that just hasn't been caught before now, I don't yet know. The fix for this specific issue is in Reveal.prototype._init, line 143, it needs a check to see if there already is an overlay, otherwise, it's double dipping on overlay creation. I've made the fix to develop, but we probably won't be doing a deploy till next week... my bad. fixed with 274e70b
