### ISSUE TITLE
Off canvas toggle broken when using fixed title-bar

### ISSUE THREAD

**Issue by jimthegit** [zurb/foundation-sites#7372]
Hi guys,

I've found a bug wth the off-canvas menu-icon toggle. 

If the title-bar containing the off canvas menu toggle is given a position of fixed and a z-index greater than 1 (therefore exceeding .off-canvas-content z-index of 1) we can toggle open the off canvas but then any attempts to close the off canvas via the toggle fails.

I've attached a screen grab of a quick and dirty demo using the Zurb Foundation 6 docs page - if you check the inspector styles and mimic the overrides I've applied (ensuring you scale the viewport down to make the topper visible) you'll see the bug when you attempt to toggle the off canvas.
![screen shot 2015-12-03 at 16 35 57 2](https://cloud.githubusercontent.com/assets/9253831/11567037/04d11160-99dd-11e5-9783-c73fc7bface0.png)

**Comment by andyleong** [comment]
Yeah, I'm experiencing the same issue, though it seems like it only happens when I change the browser width to a new breakpoint. 

For instance, if I do a fresh load of the page in a small window, the off-canvas trigger works fine opening and closing the menu, but once I expand the window to the medium breakpoint the toggle only works to open the menu.

**Comment by simonwimell** [comment]
Same issue here. Unable to close off canvas sidebar when using fixed top-bar with z-index.

**Comment by andycochran** [comment]
@jimthegit You should use `data-toggle=""` instead of `data-open=""`.
