### ISSUE TITLE
[Accordion] Accordion break orbit slider

### ISSUE THREAD

**Issue by NanoEdit** [zurb/foundation-sites#7426]
**How can we reproduce this bug?**

1. Open accordion - orbit slider start lagging
2. Open and close accordion few times - orbit disappear 

I think this is some bug with motion-ui or something else.
After clicking on according toggle, on .orbit-slide appear these classes:
orbit-slide fade-out mui-leave mui-leave-active is-active fade-in mui-enter mui-enter-active
They hide slides

**Test case**

Just clicking on accordion, it crash orbit when slide change
http://jsfiddle.net/0yaru5vm/3/
(used last foundation and motion-ui from github)

Sorry for my english.

**Comment by gakimball** [comment]
Hey @NanoEdit, sorry for not getting to this issue sooner!

If the Motion UI classes (anything starting with `.mui-` are sticking to the element, this is usually because the CSS for those classes isn't being loaded. The classes aren't removed until the element fires a `transitionend` event, but this will never happen if the transition doesn't start at all. It won't start if the CSS for the classes isn't there.

In your JSFiddle, the reference to the Motion UI was a broken link, so I replaced it with one from cdnjs. I updated the Fiddle's JS and CSS to use Foundation 6.2.0, spent a while clicking on the accordion over and over, and nothing went wrong. The Orbit slider autoplays, and each animation happened just fine, and the slider never outright disappeared.

If you're still seeing this behavior in the latest version of Foundation (6.2.0), let me know what browser you see it in so we can work on resolving it. Thanks :)
