### ISSUE TITLE
Add nav bullets with Javascript

### ISSUE THREAD

**Issue by LeG3nDz** [zurb/foundation-sites#7431]
Hi community,

Do you know if i can "creat" .orbit-bullets with all button in Javascript rather than integrate directly in html ?

Example :

    <div id="orbit-slider" class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit data-options="bullets: true; /* don't work */">
        <ul class="orbit-container">
            <?php for ($orbit = 1; $orbit <= 4; $orbit++): ?>
                <li class="is-active orbit-slide">
                    <div class="text-center">
                        <h3>You can also throw some text in here! <?php echo $orbit; ?></h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde harum rem, beatae ipsa consectetur quisquam. Rerum ratione, delectus atque tempore sed, suscipit ullam, beatae distinctio cupiditate ipsam eligendi tempora expedita.</p>
                        <h3>This Orbit slide has chill</h3>
                    </div>
                </li>
            <?php endfor; ?>
        </ul>
    </div>

Thank you !

**Comment by zurbchris** [comment]
As in, will the JS create the markup for the buttons for you? If that's the case, no it will not.

**Comment by zurbrandon** [comment]
We changed this on purpose from 5 to 6 since we felt generating too much html through JS made it harder to style. This isn't likely something we'll change back.  This is something that PHP should be able to generate. 

I'll close this since it's not something we'll be chnaging, but feel free to reopen if you have addiotnal ideas.
