### ISSUE TITLE
[ Accordion Menu ] Missing Carets

### ISSUE THREAD

**Issue by humblehumans** [zurb/foundation-sites#7437]
Accordion Menu not displaying caret dropdown arrows, tried multiple fresh installs using Foundation CLI.

It appears that the ```:after```  pseudo element is not being added to DOM. 

Tested Line 10 of ```components/_accordion-menu.scss``` and anything in ``` @if $accordionmenu-arrows { ... }``` is not being executed. Where am I going wrong?

Can't find any reference to ```@include foundation-accordion-menu``` in repo

**Comment by humblehumans** [comment]
Not sure if this was intentional but ```@include foundation-accordion-menu``` was not listed on ```app.scss``` added it to the include list and boom carets found.

**Comment by gakimball** [comment]
Not intentional, thanks for catching it. Made the necessary changes to the templates [here](https://github.com/zurb/foundation-sites-template/commit/59efba0b3cba15b1400a27bbd55fb39cd3bc7d58) and [here](https://github.com/zurb/foundation-zurb-template/commit/e25e9ec02fc7a3beefb9fc6ffd0f400966118d42).
