### ISSUE TITLE
[Global Styles] Changing global font size

### ISSUE THREAD

**Issue by therealbenhogan** [zurb/foundation-sites#7493]
Using 6.0.5

The docs state that you can change the base font size by setting $rem-base to $global-font-size and making sure that $global-font-size is a pixel value.

In the _settings scss file I did that eg

    // $global-font-size: 100%;
    $global-font-size: 14px;

    // $rem-base: 16px;
    $rem-base: $global-font-size

However, when you do that, the max width of the site from 

    $global-width: rem-calc(1200);

Is no longer 1200px ... how can we change the global font sizes and still retain the correct global width (and not have it affect the grid breakpoints)

**Comment by ocularrhythm** [comment]
After digging around, it seems that `$rem-base` is being defaulted in the `util/_unit.scss` file. Since the `utils/utils` are being imported/compiled before the `global`, the variable is never overridden with the custom value. Declaring the variable before the `@import 'util/util` in the `_settings` file seems to do the trick.

**Comment by therealbenhogan** [comment]
Hi, that's great - thanks for helping out!
