### ISSUE TITLE
Media Queries and base font size

### ISSUE THREAD

**Issue by n-dawson** [zurb/foundation-sites#7500]
Changing the base font size affects the media queries in an unexpected way.

The medium breakpoint for example is defined as 640px which at the default base is 40em. When the base is changed to 14px the media query will update to 45.714...em. 

ems are relative to the font size defined in the browser settings when used in media queries and not the HTML element which means the medium breakpoint comes into effect at 732px instead of 640px.

I believe the solution would be to calculate the queries in em without taking into account the setting used for global font size.

**Comment by gakimball** [comment]
Yes, we've been talking about this internally. We need to change how breakpoints are printed so that the "pixel value" of the breakpoint is always the same.

So the em value for medium should always equal 640px, regardless of the page's base font size. This will involve making some adjustments to the `-zf-bp-to-em` function, which does the em calculation for breakpoints.

**Comment by jensengelmann** [comment]
I described the problem here: https://github.com/zurb/foundation-sites/issues/7021#issuecomment-163913431

In my eyes a simple fix would be changing https://github.com/zurb/foundation-sites/blob/develop/scss/util/_unit.scss#L54 to ```$value: rem-calc($value,16px);```.

Or you assign a new variable instead of hardcoding the ```16px```...

**Comment by gakimball** [comment]
Going to close this in favor in #7021, which has a more detailed discussion of the issue.
