### ISSUE TITLE
[Top Bar] Jump to Top on ZF6

### ISSUE THREAD

**Issue by AlexLaforge** [zurb/foundation-sites#7615]
**How can we reproduce this bug?**
Put the Sample Top bar code into a blank page.
http://foundation.zurb.com/sites/docs/top-bar.html

**What did you expect to happen?**
I expected the top bar would have DATA-OPTIONS, like scrolltop:false in ZF5 !

**What happened instead?**
It jump to top, and no way to prevent it !

**Test case**
Test yourself Dude ! :-(
That's REALLY a shame that ZF6 removed so many of useful features of ZF5 ! After 3 days of "attemps" to customize it, It feels like I'm using ZF3 : Going back to ZF5 , definitely !
Zurb : go back to work.

**Comment by gakimball** [comment]
The reason the links jump to the top is because the links inside don't go anywhere, they just have `href="#"`. It's not something inherent to the dropdown plugin.

The features of Foundation 5's top bar are still around, but they've been reworked to make things more flexible. Read the docs page on [responsive navigation](http://foundation.zurb.com/sites/docs/responsive-navigation.html) to learn how it all works.

I added a note to the top of the documentation explaining this: a52c6fada991cdee7859122b56c8aa5fbd6d3500 Sorry it wasn't clear!
