### ISSUE TITLE
[Calllout] close button overlaps content

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#7619]
The content of a `.callout` can be overlapped by a `.close-button`. The padding for a `.callout` should account for this. We can assume there's a close button if the `.callout` includes `[data-closable]`. 

I'll work on a PR to output something like… 
```
.callout[data-closable] {
    padding-right: 3rem;
}
```
It'll need to account for `$closebutton-position` to determine if `padding-left` or `padding-right` should be used. 

And I'm thinking the amount of padding should be calculated by `$closebutton-offset-horizontal + $callout-padding + (width of &times;)`. But there's no way of getting the width of `&times;`. What does everyone think of making close buttons square with an explicit width? It's that or just using an approximate width.

**Comment by gakimball** [comment]
This is tricky, because we tend to avoid having components directly interact with each other; we prefer to keep CSS isolated. And as you've identified, it's hard to know exactly how big that close button is going to be, making the math difficult. But what if you change the size of the close button, or use your own custom control?

This may be a case where we defer to the designer to implement their own extra styling—that's generally how we encourage folks to use Foundation.

Hopefully that makes sense—if not, we can keep discussing a possible solution.

**Comment by andycochran** [comment]
@gakimball Great point about isolating components. You're right; the `.callout` shouldn't calculate its padding based on the `.close-button`. But what do you think about introducing a new `_settings.scss` variable to adjust the padding for `.callout[data-closable]`? 
```scss
$callout-closable-padding: 1rem 3rem 1rem 1rem;
```
^ This way, designers can use any element with a `data-close` and position it wherever they want. 

I understand the desire to offload this to app-specific styling, but the vanilla FS6 should look good and function well (imagine a text link being overlapped by a close button). As-is, I expect we'll instead see lots of unintentionally overlapping close buttons.
