### ISSUE TITLE
[Drilldown Menu] The href of parent menu has been remove

### ISSUE THREAD

**Issue by deltakhiem** [zurb/foundation-sites#7636]
1. Implement drilldown menu
2. Use inspect element on browser to see HTML code of drilldown menu
3. See on the link that have a sub menu
4. That link has been remove the href attribute

**The href attribute has not been remove**

**The href attribute on the link has been remove **

**Comment by gakimball** [comment]
It's removed because the functionality of the link changes—it now opens a drilldown menu instead of the original link.

In Foundation 6.2, we added a `parentLink` option to the plugin, which will add whatever that link was as the top item within the submenu. Here's the PR that implements it: #8178

You can add the attribute `data-parent-link="true"` to your HTML to enable it.
