### ISSUE TITLE
Prevent following certain links in reveal modal

### ISSUE THREAD

**Issue by tr33m4n** [zurb/foundation-sites#7642]
Hi there,

I'm just wondering if there's a way to prevent following certain links in a reveal modal (Foundation 5)? I've tried using preventDefault() in my JS but they still get executed.

Thanks

NB: Tried posting in the Foundation forum however nothing gets executed when clicking publish, preview or save post

**Comment by ocularrhythm** [comment]
Could you post a code example of both your link and your JS?

**Comment by zurbchris** [comment]
Probably due to Foundation event listeners being applied before your own. Try this:
```javascript
$(' .some-buttons', '#my-modal').click(function(e){
  e.stopImmediatePropagation();
  e.preventDefault();
});
$(document).foundation();
```

That will make your script have precedence on the event listeners for `.some-buttons`, bubbling will be stopped with `stopImmediatePropagation`, and you'll prevent the link from being followed with `preventDefault`.

**Comment by tr33m4n** [comment]
Hi @zurbchris 
This worked perfectly, thank you!

**Comment by zurbchris** [comment]
You're welcome!
