### ISSUE TITLE
is _Settings.scss doesn't imported by default ?

### ISSUE THREAD

**Issue by dieka13** [zurb/foundation-sites#7686]
I downloaded the master branch (foundation-site-master.zip) few days ago and noticed that there's nothing happen when i change something in _Settings.scss, it turns out that there's no ''@import 'settings/settings';" line at foundation.scss file. is this supposed to be like this ?

**Comment by Knight-Yoshi** [comment]
It's to be imported after the main foundation.scss file.

**Comment by colin-marshall** [comment]
@Knight-Yoshi: That is incorrect. The settings file needs to be the very first thing you import.

@dieka13: You should create a master SCSS file that imports your settings file, Foundation components, and any other custom or 3rd party components you use in your project. A great example of this is the **[`app.scss`](https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/scss/app.scss)** file from the [Foundation Zurb Template](https://github.com/zurb/foundation-zurb-template/).

**Comment by Knight-Yoshi** [comment]
In Foundation 6 the settings.scss file is loaded after the main foundation.scss file
https://cloud.githubusercontent.com/assets/177020/11526622/b5732cac-98ec-11e5-8b12-f4c2177e0260.png

gakimball also explained it, "The reason we imported the settings file before the framework in Foundation 5 was because the act of @importing something would print the CSS. So by the time you've called @import 'settings', the framework has already done its thing and printed the CSS with the default settings.

The new model in Foundation 6 was supposed to fix this, but we still ran into some issues and ended up keeping it how it was.
" - https://github.com/zurb/foundation-sites/issues/7328#issuecomment-163340546

**Comment by colin-marshall** [comment]
@Knight-Yoshi: That graphic was not from anybody at Zurb. It was simply a Foundation user explaining his personal workflow. You are misunderstanding what gakimball said. 

> "The reason **we imported the settings file before the framework in Foundation 5**...
> "...The new model in Foundation 6 was supposed to fix this, but we still ran into some issues and **ended up keeping it how it was**.

He says they imported settings first in Foundation 5, and they kept it that way in Foundation 6.

**Comment by Knight-Yoshi** [comment]
If you look at the context, it was about why the settings file is loaded after the foundation.scss file because the user was wanting to do it that way. That image was taken from the Foundation docs site. In Foundation 6 the settings file was changed to be loaded after the initial foundation.scss file was loaded.

To resolve this lets just ask @gakimball .

**Comment by colin-marshall** [comment]
He's saying at first they tried to set it up to import the settings after Foundation in version 6, but then they went back to importing the settings file first because of issues.

Straight from the current [Foundation 6 Sass docs](http://foundation.zurb.com/sites/docs/sass.html):

> You're also going to want a settings file for your project, which will allow you to modify the default styles of Foundation. Download the latest settings file here, add it to your project as `_settings.scss`, then import it **before** Foundation itself.

Then it gives a code example:
```scss
@import 'settings';
@import 'foundation';
```

**Comment by Knight-Yoshi** [comment]
Well then it was changed in the docs. Because I remember when Foundation 6 was released it was the main foundation file, settings, and then the foundation-everything mixin. Which is what I also do and everything has worked fine thus far, because nothing happens until a component mixin, or the foundation-everything mixin is called.

**Comment by gakimball** [comment]
@Knight-Yoshi The settings file has never been imported after the framework; it's always been before. For reference, here's `app.scss` in the ZURB Template the day Foundation 6 came out: <https://github.com/zurb/foundation-zurb-template/blob/31460612c999e8bfe8f488eb713bca33b6a3cb2e/src/assets/scss/app.scss>

@dieka13 To answer your question, the settings file in the framework file isn't meant to be edited directly. Generally you shouldn't be editing any framework files directly, because package managers will overwrite them when you make updates.

You downloaded a ZIP file of this repo, but if you're looking to start a blank project with Foundation, we have recommended ways to do that. We have two starter projects, the [Basic Template](https://github.com/zurb/foundation-sites-template) and the [ZURB Template](https://github.com/zurb/foundation-zurb-template), which wire everything up with a build system for you. Note that these templates include a *copy* of the settings file, bundled with your own Sass files, and `app.scss` doesn't reference the file inside the framework folder itself.

Let me know if that clears everything up. If not, we're happy to answer more questions :)

**Comment by Knight-Yoshi** [comment]
Fair enough then.
