### ISSUE TITLE
Dropdown is flickering

### ISSUE THREAD

**Issue by isomis** [zurb/foundation-sites#7754]
I made a dropdown for the cart dialog (see upper right): http://phil.dutchquality.nl/nl

Only sometimes is flickering and end closed. Are there any suggestions to fix this?

also the lettertype is changing weird after a hover. 

extra info: its not get triggered twice.

**Comment by rafibomb** [comment]
The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
