### ISSUE TITLE
[Dropdown Menus] Menu with Logo: Submenu position

### ISSUE THREAD

**Issue by foodgy** [zurb/foundation-sites#7771]
I was trying to make a simple dropdown menu with logo, but noticed a bug. Submenu appears much lower than expected. It happens because of ```display: table-cell``` property of menu's ``li``.

Look at this example [F6.1.1]: https://jsfiddle.net/nf1nsmj4/

**Comment by gakimball** [comment]
This is happening because the `<li>`s inside the menu are `display: table-cell`, which adds padding above and below each item to vertically-align them. However, the submenu is trying to anchor to the bottom of the `<li>`, which is now super tall.

There's not an easy fix for this. *However*, in Foundation 6.1.2 we introduced a new pattern for the top bar syntax which alleviates this. You can now define a title area (`.top-bar-title`) that's separate from the body of the top bar. Using this HTML and a little extra CSS to center align the menu, we get the desired result.

I took your JSFiddle, updated it to Foundation 6.1.2, and reworked the HTML and CSS a bit to get the desired result: <https://jsfiddle.net/nf1nsmj4/1/>
