### ISSUE TITLE
Namespace conflict with breakpoint gem

### ISSUE THREAD

**Issue by erutan** [zurb/foundation-sites#7773]
Whenever I used Foundation 5 I'd disable your grid system - it's great for protoptying or people that don't want to use SASS, but I found singularity.gs is more powerful in terms of differing column widths, responsive grids, requires less markup, etc... and it's just simpler to use SASS from the start than to cut out a whole bunch of HTML classes at the end of the process.

Your breakpoint SASS mapping for typo / buttons / grid has a namespace conflict with https://github.com/at-import/breakpoint (which is required for responsive grids in singularity.gs). Annoyingly while they're both `@include breakpoint()` one uses mapping and the other variables so they're not interchangeable. I don't imagine there's going to be a naming convention shift at this point due to this, but it's a little frustrating being forced into your grid system if I want to use the rest of Foundation for Sites.

Alternatively it'd be nice to get responsive grids (you can set number of columns per breakpoint) and uniquely sized grids (one often doesn't need a ton of equidistant columns, whatever ratio of main vertical containers you require is nice and then you can subdivide within those), etc that are currently available in singularity.gs in future releases.

**Comment by gakimball** [comment]
We don't plan on changing the name of `breakpoint()`. Even if we changed it to, say, `media()`, that would conflict with Bourbon. We avoid namespacing commonly-used mixins/functions, for developer convenience.

As for the grid features, you can absolutely do responsive grids. The syntax for grids in general is a bit more verbose, because column widths are defined on individual classes, rather than all at once in one mixin. The section of our documentation on [building semantic grids](http://foundation.zurb.com/sites/docs/grid.html#building-semantically) explains how the grid mixins work. If you scroll down farther, there's an explanation of how to build responsive grids as well.

Can you explain what "uniquely sized grids" is? Our grid allows you to define rows that use a column count other than 12, and individual columns can also be sized with a unique parent context, i.e. `1 of 5`. Is there another feature there Foundation doesn't have?

**Comment by erutan** [comment]
Thanks for the quick reply. Assumed there'd be no namespace change but had to ask. :)

I took a look at the docs and you can override existing grids within breakpoints.  There doesn't seem to be a way to set the overall master grid variables though, e.g. "I want a 2 column grid for mobile, then a 12 column symmetrical grid at foo breakpoint, etc". I personally enjoy setting a very simple grid for mobile and using isolation grid-span useful - only options are (1, 2) (1, 1) (2, 1).  I'll expand it out into either an asymmetric grid or traditional 12 col symmetric grid in breakpoints. e.g. https://github.com/at-import/Singularity/wiki/Creating-Grids#responsive-grids For F6 it'd be set in a SASS map ala gutters - this seems like it'd be something that could be baked in with a manner that wouldn't conflict too much (as opposed to margins + calc() so we don't need extra row containers, or namespacing breakpoint).

Uniquely sized grids was a crap way of explaining it, blame it being a bit late in the evening? https://github.com/at-import/Singularity/wiki/Creating-Grids#asymmetric-grids - I find this a lot simpler for straightforward layouts (rigid cols is better for a media portals etc).

This should have been an earlier comment, but the general grid discussion seemed to happen earlier and I figured I could just work around it as usual.

**Comment by gakimball** [comment]
We did this in Foundation 3—the mobile grid was four columns, while the desktop grid was 12. Starting with v4, all breakpoints used the same twelve-column grid. We did this because we found the mental math was easier when reading a bunch of grid classes (or grid mixins). You always know you're dividing by 12, or whatever column count you've defined.

With Foundation 6, we've made it easier to define columns with arbitrary widths, and you can also define rows with unique column counts.

> the CSS focus detracts from the SASS and being able to just jump into a SASS centric solution while keeping the rest of foundation worked really well before.

Are there any features we lost from 5 to 6? I don't believe there are.

(Closing this, but let's continue the discussion.)

**Comment by erutan** [comment]
Yeah multiple grids a preference when they're symmetrical - they become more mandatory when you have asymmetric ones (which aren't always the right solution, but make things a lot simpler when they are).  I never had issues remembering what grid I was on because I'd use consistently named semantic breakpoints with my media query bubbling, but feel given Foundation's intent it should be something that it allows you to do vs sticking with by default.

I didn't use the F5 grids much (a single client project iirc), generally starting with classes output for typo/forms/buttons + singularitygs & breakpoint then adding in components as needed.  When possible I'd use Foundation as the starting point for a project and build on it, I really enjoy the design philosophy behind it and prototyping in SCSS with it after wireframe sketching / handful of key hi-fi comps works great.

The cleanliness of setting up responsive asymmetric grids as outlined here is really really nice (it'd break parity with the CSS features, which is a philosophical decision, but most of the pieces are in place): https://github.com/at-import/Singularity/wiki/Creating-Grids#responsive-grids. That's a lot nicer than creating a whole bunch of media query bubbles for every column and manually making sure they all work nicely together. F6 can do most of what singularitygs does, but it's not as pleasant. A few complex functions built on top of some SASS maps and mixins that currently exist would probably do the trick.
