### ISSUE TITLE
[Interchange] Interchange, loads script multiple times

### ISSUE THREAD

**Issue by Ne-Ne** [zurb/foundation-sites#7838]
**How can we reproduce this bug?**

Resize the page with Chrome Dev Tools open, google maps loads multiple times.

**What did you expect to happen?**

Operate without error messages, it appears it is preloading external scripts frequently.

**What happened instead?**

Works, with JS console errors

**Test case**

Visible on Docs site (see below), I re-sized the browser from small to large:
![screen shot 2016-01-11 at 15 07 38](https://cloud.githubusercontent.com/assets/2177851/12237184/4ea53cc4-b875-11e5-8125-1be9fc6a5eaa.png)

**Comment by zurbchris** [comment]
So, I've known about this issue for a while, and this is a lesson in developer responsibility. The developer(s) in question this time being the ZURB team :laughing:. The Google Maps api is being loaded via `jQuery.getScript` which is listening to the `replaced.zf.interchange` event. Sounds great so far, except that it's listening to *all* replace events and trying to load the script (or is successfully loading it, I can't really tell), every time a replace event is fired from that particular Interchange plugin. I'll fix this, and the fix is pretty simple, but the takeaway is, Foundation can only do so much on it's own, it's up to you to use it responsibly :smile:

**Comment by zurbchris** [comment]
for reference, this is what it *was* doing:
```js
$('#docs-example-interchange').on('replaced.zf.interchange', function() {
      $.getScript("https://maps.googleapis.com/maps/api/js?key=XXXXXXXXXXXXXXXXXXXXXXXX&sensor=false&callback=initializeMaps");
});
```

and it was fixed with a pretty simple boolean flag check

```js
var loaded = false;
$('#docs-example-interchange').on('replaced.zf.interchange', function() {
  if(Foundation.MediaQuery.atLeast('large')){
    if(!loaded){
      $.getScript("https://maps.googleapis.com/maps/api/js?key=XXXXXXXXXXXXXXXXXXXXX&sensor=false&callback=initializeMaps")
      .done(function(){
        loaded = true;
      });
    }else{
      window.initializeMaps();
    }
  }
});
```

I want to point out that though it did add a few lines to our code for this particular page, we were able to take advantage of the public api exposed in the Foundation global object, and make sure our current media query was the size we wanted before we went and loaded a script all willy-nilly.

**Comment by Ne-Ne** [comment]
Thanks for the breakdown @zurbchris, I thought at one point I was seeing things.
