### ISSUE TITLE
[Sticky] tall Sticky side

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7865]
if you got a tall sticky navigation that is higher than the browser window it should behave like this

http://leafo.net/sticky-kit/
Example: Scrollable Sticky Element
My Last Site

the navigation should not be sticky until the end of the navigation is reached if you then scroll up the navigation should also scroll up to the top of the navigation and unstuck if the top anchor is reached

**Comment by rafibomb** [comment]
I would probably call this a feature or enhancement on the current functionality. We'll review it with the team to see where it goes on the roadmap.

**Comment by designerno1** [comment]
yeah but it would be a very very good feature, because right now we nearly can't use sticky for a sidenav because a menu often is taller than the screen and so you cant reach the end of the navigation, except you use stick to bottom, then it is reachable but not as perfect as sticky_kit.

**Comment by zurbchris** [comment]
So, I played with this a bit this morning, just to see if this was something that should be in Foundation, or should be user configured. It's a very small thing, but is a per use decision (in my opinion), and so then should be answered by the dev using it. You can achieve what you're looking for by adding `overflow:scroll;` to the content contained in sticky.

```html
<div data-sticky-container>
  <div class="sticky" data-sticky>
    <div class="some-content"></div>
  </div>
</div>
```
```css
.some-content {
  overflow: scroll;
}
```

**Comment by designerno1** [comment]
hm that does not work for me, because you have to set a height on some-content, or set it to browser height through javascript.
and the behavior is not as perfect as from sticky_kit and we know it from other pages as fb ...

**Comment by designerno1** [comment]
is this that feature you mention in js file?
```js
//this would be the stickTo: both option... tricky
```

**Comment by andycochran** [comment]
I'm confused. Can't this already be done with `data-btm-anchor="foo:bottom"`?

**Comment by designerno1** [comment]
don't think so
the function i mentioned is, scrolling down the tall side sticky scrolls down, scrolling up the tall side sticky scrolls up until the top reaches window top position scrolling down again sticky scrolls also down until bottom reaches window bottom pos and so on and so on

**Comment by andycochran** [comment]
I think I understand. You want it to:

* stick only to the bottom while the bottom of `data-sticky-container` is in view 
* stick only to the top when the top `data-sticky-container` is in view 

Right?

**Comment by designerno1** [comment]
hm no i don't think that's what i want it to
i send you an email with a example of what i mean

**Comment by zurbchris** [comment]
The intent of that setting is this: Stick to the top of the viewport on scroll down, then if and only if the bottom anchor point was reached, and the sticky element became unstuck, stick to the bottom of the view port on scrollup. Tricky because you have to account for the change in scroll points to prevent snapping to a location when the anchor point is reached.

**Comment by designerno1** [comment]
yes can't we adapt it from the sticky kit?

**Comment by zurbchris** [comment]
If you want to tackle that, I'd like to see a pr :+1:

**Comment by designerno1** [comment]
@zurb/yetinauts 
anyone who could address this feature?

**Comment by colin-marshall** [comment]
@designerno1 I'm pretty sure you can do this already if you set the `data-top-anchor` of the sticky nav to `id-of-div-directly-above-sticky-nav:bottom`. I'll do some more investigation...

**Comment by colin-marshall** [comment]
@designerno1 this example is supposed to do what you are asking:
http://zurb.com/building-blocks/shrinking-sticky-navigation-menu-f6

It becomes unstuck too soon because of a bug, but if you resize the window to a different breakpoint it starts working like it's supposed to. If you could turn that building blocks example into a visual test that would that would be very helpful if you have time and we will address it as we are fixing the other bugs.

**Comment by designerno1** [comment]
i created a pen to show what i mean:
https://codepen.io/designerno1/full/YqdYjv/

it's nearly what i'am looking for.
it gets stick if bottom of sticky reaches window bottom and stick until bottom sticky reaches bottom-anchor.
But then when you scroll up it gets sticky when bottom of sticky reaches window bottom,
But it should anchored until sticky top reach window top and then get sticky to window top until it reaches top-anchor and then gets anchored

is there a way to do that

**Comment by fleps** [comment]
Hey guys

I know this is old but I have a similar issue and can't understand how to fix it.

Basically I have a side navigation that will stick to the top as soon as the header disappears, and this works fine.

The problem is that over time the navigation got more and more items and now when I'm on a laptop screen the height of the navigation is bigger than the viewport, so what happens is that it get's stick to the top and cut the bottom, so the user can never reach the items at the bottom of it.

What's the best way to fix this? Basically what I want is to keep the sitcky to the top if the viewport is bigger and the nav can be fully visible, but if not, as soon the header disapear the nav should also scroll a little bit and stick to the bottom of the viewport.

Is this possible with current feature / options?

Thanks!

**Comment by DanielRuf** [comment]
@fleps please create a new issue if this is still relevant.
