### ISSUE TITLE
[Reveal] tall Reveal scrolling close button

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7875]
if you got a tall reaval with a closing button the close button is inside the scrollable area so if you scroll down you can't see the close button, that is not good for usability.

**Comment by rafibomb** [comment]
How would you change it? Position absolute on the .close and make the outer modal box the reference?

**Comment by designerno1** [comment]
i think this wouldn't work because the modal has a overflow-y:auto , don't think you can pull it out there with position:absolute

**Comment by andycochran** [comment]
Could `.sticky` be used here?

**Comment by designerno1** [comment]
hm but isn't this "using a sledge-hammer to crack a nut"

**Comment by designerno1** [comment]
the whole reaval seems to be a little buggy?!?

**Comment by andycochran** [comment]
I wouldn't call Sticky a sledgehammer. It's a specialized tool for preventing elements from scrolling out of view. One of the goals rewriting Foundation was to make sure components could be repurposed. Using Sticky for this case seems appropriate, and it keeps Reveal leaner.

**Comment by zurbchris** [comment]
I concur with @andycochran, esp. since I wrote, (for good or ill), most of the js for Foundation 6, and designed many of the plugins to be as reusable as possible. In this case, though, @designerno1 is quite correct. All the media containers: dropdown, tooltip, reveal, are a little buggy and need some tlc.

Most helpful would be to take a large portion of the positioning/sizing out of js and put it in the sass, where it belongs. There's currently too much room for error, with event listeners and whatnot all impacting where an element is positioned.

**Comment by rafibomb** [comment]
@designerno1 Seems like there are a few different things happening here. We started a conversation on the Reveal Modal and would love to hear your struggles with it and suggestions. http://foundation.zurb.com/forum/posts/38459-f6-reveal-modal-suggestions

**Comment by gakimball** [comment]
With 6.2 we reworked modal positioning to be less buggy. Part of that includes going back to moving the modal HTML inside of the modal overlay, so setting up scrolling is way easier.

As for close button positioning, if you want to position the close button over the overlay instead of the modal itself, you can add `position: fixed` to it. [Here's a test file.](https://github.com/zurb/foundation-sites/blob/5f611eff8fb405c2406893d7431c0fd7b0d0f063/test/visual/reveal/tall.html)
