### ISSUE TITLE
[Sticky] Event names in documentation are incorrect

### ISSUE THREAD

**Issue by licyeus** [zurb/foundation-sites#7914]
Documentation at http://foundation.zurb.com/sites/docs/sticky.html lists the event names as `stuckto.zf.sticky` and `unstuckfrom.zf.sticky`. Per the source, those should be [`sticky.zf.stuckto`](https://github.com/zurb/foundation-sites/blob/master/js/foundation.sticky.js#L279) and [`sticky.zf.unstuckfrom`](https://github.com/zurb/foundation-sites/blob/master/js/foundation.sticky.js#L319).

Would submit a PR myself, but the "Edit this Page" link on the docs takes me to [a lorem-ipsum-filled page](https://github.com/zurb/foundation-sites/edit/develop/docs/pages/sticky.md), not the actual source of the Sticky docs.

**Comment by zurbchris** [comment]
That takes you to the markdown page used to generate the documentation. The issue you filed is a known issue, and an ongoing problem we're having with JSDoc not compiling comments on events correctly.

**Comment by gakimball** [comment]
@zurbchris Either way the event names in the code itself are written backwards: namespace, then event name. See: <https://github.com/zurb/foundation-sites/blob/develop/js/foundation.sticky.js#L279>

If that was intentional, then we'll need to rework the JavaScript reference template to account for that.

**Comment by JeremyEnglert** [comment]
I'll update the docs with the correct event names.

**Comment by jeremylind** [comment]
Looks like this still isn't fixed. See: [http://foundation.zurb.com/sites/docs/sticky.html#js-events](url).

**Comment by jordanbrauer** [comment]
@jeremylind lol yup. Just came accross this issue myself. In fact, even the 'correct' `sticky.zf.stuckto` and `sticky.zf.unstuckfrom` don't work.

```javascript
 /*
sticky.zf.unstuckfrom:top, 
sticky.zf.stuckto, 
sticky.zf.unstuckfrom, don't work either.
*/

$('.element').on('sticky.zf.stuckto:top', function() {
  console.log('fixmeplease');
});
```

Quite annoying considering this issue prevents us from _easily_ adding custom events to the `sticky.js` plugin _and_ is practically 9 months old to boot (@JeremyEnglert). Come on guys, this doesn't help your advanced users.

**Comment by kball** [comment]
Yeah, we're identifying a lot of issues in the events, so definitely hear your pain.  The docs are assuming a structure to events that sticky is violating, so unfortunately I don't have a quick fix to the docs... I believe the real fix is to fix the event name to match the structure of the rest of our events

The event name fix will need to wait until 6.3 because it is backwards incompatible.

@coreysyms is compiling a list of events and lifecycle hooks so we can standardize this across all of foundation, hopefully we'll be able to hit that in roughly the same timeframe.

In the meantime, the actual event names getting fired are as highlighted by @licyeus in the original comment, `sticky.zf.unstuckfrom:top`, `sticky.zf.unstuckfrom:bottom`, `sticky.zf.stuckto:top`, and `sticky.zf.stuckto:bottom`

**Comment by dtlevin** [comment]
Has this been fixed? 

I see it working in your codepen example but can not get anything to fire here. 

Has anyone else been able to get anything to fire? if so can you post you code?

**Comment by thomasfrobieter** [comment]
@dtlevin Take a look at this pen: https://codepen.io/zurbchris/pen/rxMaoX

I experienced the same problem, but this is working for me. It seems that the :top / :bottom suffix is mandatory - which is not entirely clear by the documentation.

**Comment by renatonascalves** [comment]
Wow! Two years to update the documentation. Really?!

**Comment by ncoden** [comment]
@renatonascalves  Sorry for the late reply, some old issues got "lost" as we were working on the lastest. We are currently making a pass on all the Foundation issues to prepare the v7.

Also, this should be resolved in See https://github.com/zurb/foundation-docs/pull/24 ;)
