### ISSUE TITLE
Magellan deepLink not scrolled to after page (re)load

### ISSUE THREAD

**Issue by tomkeysers** [zurb/foundation-sites#7927]
Hi,

I'm creating a one pager with a magellan menu. I've set the magellan deepLinking option to true so the url gets #activeSection at the end. But the main reason I want this is so a link to a certain section of the website could be shared; hence on a page load it would automatically scroll to the part that is referenced in the url.

BUT that is not working. When I reload or load with a #activeSection in the url, it is automatically replaced by the #firstSection of the page.

I am using an own js fix for this now, where I check the window.location.hash in the url and let the page scroll to it, but ideally this should be covered by the Magellan module, should it not..?

Am I missing another option, or could you provide a fix in the future perhaps?

Thanks in regards.

**Comment by zurbchris** [comment]
Well, that shouldn't happen. Here's the thing though, browsers will scroll to the hash of a page once it reads the url and finds a target element with a corresponding id. There are a few ways to get around this, from fairly simple to really hacky. For reloading I get the same thing you're getting, it'll start me at the top of the page or wherever the first magellan target is. For loading in a page from a new tab with a #something at the end though, I do indeed get scrolled to the appropriate location, it's just not Magellan causing the scroll, it's the browser. 

One thing your issue did bring up though, is there wasn't a good way for Magellan to see where the heck it should be on page load, so I've added a tiny check on page load to do just that.

As for your primary issue, I've put in a method for scrolling to a `location.hash` via smooth scroll on page load, but it's the developer's responsibility to stop the browser's from scrolling the page, as the html will be parsed well before the Magellan JavaScript will be. Not much I can do for you there, except point you to this [StackOverflow question](http://stackoverflow.com/questions/3659072/how-to-disable-anchor-jump-when-loading-a-page) on the matter.

This brings up another issue, that I'll need more than 10 minutes to resolve, and that's only setting the active state of a link if the minimum scroll point is reached. As it stands currently, the active state is auto updated on page load to the first item in the list, which won't always be appropriate, and then the page scrolls to that location if you have `deepLinking: true` in your settings. No bueno. 

Anyway, this issue turned in to my own incubator for ideas for a few minutes, so thanks for that and also sorry for hijacking the issue for a moment.

**Comment by tomkeysers** [comment]
Hi Chris, thanks for your detailed answer! I understand, I'll work my way around for the time being.

I want to mention something else regarding magellan and deepLinking though: I noticed that the site I'm building is verry laggy (scrolling) on mobile devices. After uncommenting part after part I discovered to my great surprise that this is caused by the deepLinking option of magellan ... Not just magellan, it works fine when deepLinking:false, but when it's set to true, suddenly the mobile scrolling becomes very laggy :/

Probably something you'd want te keep in mind regarding the enhancement of magellan and deeplinking.
