### ISSUE TITLE
[Reveal] iphone overlay issue

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7971]
checked reveal on iphone looks like this
![reveal-iphone](https://cloud.githubusercontent.com/assets/8417506/12518183/3d24c36e-c137-11e5-90df-e7c49b8f30a5.jpg)

can't scroll blocks screen :-(

**Comment by zurbchris** [comment]
version? There was an issue with Safari, (Surprise!!), a while back involving z-indexing that I'm pretty sure @gakimball resolved, though I don't know where the commit is.

**Comment by designerno1** [comment]
version is develop head.

i only see this commit 
https://github.com/zurb/foundation-sites/commit/ea0e6b8191cd7ea99d6ab9d65d621e0e8d9285f1

maybe you can test it with an iphone? i gave you the link on gitter.

**Comment by designerno1** [comment]
maybe it's because my reveal is outside .off-canvas-wrapper?

**Comment by zurbchris** [comment]
Quite possibly.

**Comment by designerno1** [comment]
damn i have no iphone ;-)

**Comment by zurbchris** [comment]
@designerno1 checkout [this branch](https://github.com/zurb/foundation-sites/tree/update-reveal) and look at/test/play with the new positioning function for Reveal. I also tweaked the sass a bit and it seems to be pretty stable on iOS with a couple exceptions. 

Because Safari is the demon-spawn of web browsers, locking out scrolling on the main content is nigh impossible without other tradeoffs. So, at this point there is code for it, (_reveal.scss ln: 131 - currently commented out), that will lock the scroll, but it also forces the window to scroll to the top, and I haven't been able to reliably counter that with JS.

Based on my messing about with it yesterday, everything other than the above mentioned issue seems more performant and reliable.

**Comment by gakimball** [comment]
Fixed via 330018d577bfbdaf30dad96fa6a05e4a074419e6

**Comment by designerno1** [comment]
Really fixed by removing the console.log ?

**Comment by gakimball** [comment]
@designerno1 Sorry, here's the right commit: 82ceb63c67fd00107c652ccfa83ceab5877ef918
