### ISSUE TITLE
 [Media Queries] Warning with xxlarge breakpoint classes

### ISSUE THREAD

**Issue by natewiebe13** [zurb/foundation-sites#7979]
How can we reproduce this bug?
- Add the `xxlarge` breakpoint to the `$breakpoint-classes` setting
- Compile with sass

What did you expect to happen?
- No errors/warnings

What happened instead?
- Got a warning saying `xxlarge only` and `xxlarge down` cannot be used because it's the largest class.

I'm guessing this is related to: e5ca4fd

The visibility classes and top bar classes are causing the error.

```
WARNING: breakpoint(): the media query "xxlarge only" cannot be used because xxlarge is the largest breakpoint.
	on line 56 of bower_components/foundation-sites/scss/util/_breakpoint.scss
	from line 130 of bower_components/foundation-sites/scss/util/_breakpoint.scss
	from line 54 of bower_components/foundation-sites/scss/components/_visibility.scss
	from line 82 of bower_components/foundation-sites/scss/components/_visibility.scss
	from line 10 of stdin

WARNING: breakpoint(): the media query "xxlarge down" cannot be used because xxlarge is the largest breakpoint.
	on line 56 of bower_components/foundation-sites/scss/util/_breakpoint.scss
	from line 130 of bower_components/foundation-sites/scss/util/_breakpoint.scss
	from line 71 of bower_components/foundation-sites/scss/components/_top-bar.scss
	from line 39 of stdin
```

**Comment by gakimball** [comment]
Have you modified `$breakpoint-classes` to use all five of the default breakpoints?

**Comment by natewiebe13** [comment]
Yes. (small medium large xlarge xxlarge)

**Comment by hugw** [comment]
I'm facing the same warning after update.

Here's my code:

```
$breakpoints: (
  xsmall: 0,
  small:  30em,
  medium: 48em,
  large:  62em,
  xlarge: 75em
);

$grid-column-responsive-gutter: (
  xsmall: 20px,
  small:  20px,
  medium: 20px,
  large:  20px,
  xlarge: 30px
);

$breakpoint-classes: (xsmall small medium large xlarge);
```

**Comment by gakimball** [comment]
In 6.1.2 we added warnings if you attempt to create an `only` or `down` range with the highest breakpoint in the list. So you get that warning with `xxlarge only` and `xxlarge down`.

However, as it turns out, if you use every breakpoint in `$breakpoint-classes`, you get those warnings no matter what, because some components iterate through `$breakpoint-classes` and print `only` ranges, like you're seeing in your code.

In light of that, we've opted to drop the warning in favor of having a better fallback for each.

**Comment by sebastiansulinski** [comment]
Did you push the changes yet?

**Comment by gakimball** [comment]
@sebastiansulinski Yep: 8252c2ba8f2703a377dc0cf594aa5a2e3ab2ad7a

**Comment by sebastiansulinski** [comment]
Great - thanks.

**Comment by Anjade** [comment]
The problems are not only the warnings!
I can work with my site while foundation watch creates my app.css, but a build makes a wrong css-file, missing definitions!

**Comment by gakimball** [comment]
@Anjade What do you mean by a wrong CSS file?

**Comment by Anjade** [comment]
Means that i miss some css, that was inside before.

I word since weeks for a new site, then yesterday i made an update to all this stuff like npm, grunt
and suddenly i had this error for xxlarge.

When i build instead of watching i have an incomplete file.

BUT!

Maybe it is my fault, while i have outsourced the footer.
(Now included with php include instead of build it inside.)

Maybe this is the fault, i will try it tomorrow when i am back in my office.

**Comment by webdesignberlin** [comment]
Same Problem here.
I Use "foundation-sites": "^6.1.2" with a custom scss file to overwrite basic foundation variables:

```scss
@import './node_modules/foundation-sites/scss/foundation';
// Overwrite foundation standards
$breakpoints: (
        small: 0px,
        smallwide: 480px,
        medium: 640px,
        large: 1024px,
        xlarge: 1200px,
        xxlarge: 1440px
);
$breakpoint-classes: (small smallwide medium large xlarge xxlarge);
$primary-color: $color-primary;

@include foundation-flex-grid;
@include foundation-visibility-classes;
@include foundation-flex-video;
```

Since i add the custom ``smallwide`` key and value to ``$breakpoints`` map and ``$breakpoint-classes``, i became the same warning ``WARNING: breakpoint(): the media query "xxlarge only" cannot be used because xxlarge is the largest breakpoint.``

But only on Mac:
npm 3.5.3
node 5.1.0
grunt-sass 1.1.0

Windows workes fine.
npm 3.5.4
node 4.2.4
grunt-sass 1.1.0

**Comment by gakimball** [comment]
@webdesignberlin See [my comment](https://github.com/zurb/foundation-sites/issues/7979#issuecomment-174738756) above.
