### ISSUE TITLE
[Top Bar] top bar title misaligned

### ISSUE THREAD

**Issue by TvrtkoM** [zurb/foundation-sites#7987]
steps made:
- checked out latest source from develop
- removed node_modules dir
- removed bower_components
- npm install
- bower install
- gulp build

result:
- foundation examples in docs for top bar look good

if copied code for responsive toggle (advanced example) and including css (or scss foundation-eevrything) and js from _build i get this:
![...](http://img.ctrlv.in/img/16/01/24/56a560a77b7b9.png)

there are adjustment margins set in docs.css for __.docs-code-live .top-bar-title strong__ which are not in foundation.css

am i doing something wrong?

**Comment by rafibomb** [comment]
Updated this codepen to 6.1.2 and not seeing the issue here: http://codepen.io/rafibomb/pen/ZQEGog

Since it's not happening in the docs it's likely something else. The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here.

**Comment by dougmacklin** [comment]
Hey @rafibomb, I figured out the issue here, in the 'Advanced' section of the [Top Bar docs](http://foundation.zurb.com/sites/docs/top-bar.html#advanced), the .top-bar-title includes the 'Site Title' text, whereas in your codepen it is inside a the .top-bar-left div.
