### ISSUE TITLE
.row inside .row.collapse automatically collapsed

### ISSUE THREAD

**Issue by DominoCMS** [zurb/foundation-sites#8000]
Converting from F5 to F6 shows difference in showing rows inside collapsed rows.
All nested rows become collapsed automatically and there seem to be no way to make them uncollapsable.
Should either be a class to uncollapse, or like in F5, nested rows should be collapsed only by adding .collapse class.

This is how I hacked it.
.row.collapse .row {
	margin-left: auto;
	margin-right: auto;
}

If this is not on purpose, please fix it.
Thanks

**Comment by gakimball** [comment]
The nested rows aren't collapsed (each column still has its padding), but they don't offset from the edge any more. This was an intentional change as it keeps nested grids more consistent.

This is 5:

![image](https://cloud.githubusercontent.com/assets/1142001/12731117/0981fa7c-c8e4-11e5-88cd-de98cec4bfc3.png)

This is 6:

![image](https://cloud.githubusercontent.com/assets/1142001/12731123/151d8c2a-c8e4-11e5-991d-404de5ddef7b.png)
