### ISSUE TITLE
[F 6.1.2] Bug off canvas and Reveal with Android Browser

### ISSUE THREAD

**Issue by xfifix** [zurb/foundation-sites#8009]
I find a bug with the Android Brower, when i want show my off-canvas there is just the overlay 
that appears.

I have another Bug with reveal i have the overlay show above the reveal.

**Comment by xfifix** [comment]
the animation "transform: translateX(xx);" didn't work on Android Browser.

**Comment by xfifix** [comment]
fix this issue with replace transform: translateX(xxx) to -webkit-transform: translate3d(xxx,0,0) scale3d(1,1,1);

**Comment by andryyosua** [comment]
while we are on topic,, and opening new issue is not necessary,
this issue is also appear on IE9.. off-canvas wouldn't open and only showing overlay

i fixed this issue with `-ms-transform: translateX($offcanvas-size);`

so for full fix this issue
`-ms-transform: translateX($offcanvas-size);
-webkit-transform: translate3d($offcanvas-size,0,0) scale3d(1,1,1);`

**Comment by JeremyEnglert** [comment]
@xfifix I'm having a hard time replicating this issue as I'm not sure I completely understand the problem.

If you could use the new issues template, that would be helpful: https://github.com/zurb/foundation-sites/blob/develop/.github/ISSUE_TEMPLATE.md

For now, I'm going to close this. Feel free to reopen it using the new template if you believe the issue still exists.
