### ISSUE TITLE
[F 6.1.2] Bug calculation property width with ie 

### ISSUE THREAD

**Issue by xfifix** [zurb/foundation-sites#8023]
On IE the width are bad , Why ???

**Comment by rafibomb** [comment]
The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
