### ISSUE TITLE
Possible solution to the eternal debate about .hide and !important

### ISSUE THREAD

**Issue by esaborit4code** [zurb/foundation-sites#8037]
I know that there are at least **six** issues/PRs regarding this debate (#6190,  #6621, #6024, #6050, #6051 and #7218) and, attending to the needs metioned in them (ability to use jQuery visibility methods and avoid overwriting through classes like `.button`) here's the solution I tried and suggest:

```css
.hide.hide {
  display: none;
}
```
Credits go to the double class selector hack mentioned in [Hacks for dealing with specificity](http://csswizardry.com/2014/07/hacks-for-dealing-with-specificity/#safely-increasing-specificity) by @csswizardry.

Do you think it's a good solution or do you think hacks like this should not be in Foundation's codebase?

**Comment by gakimball** [comment]
We do use the double class hack in the grid, but it feels dirty, especially when *another* specificity issue could always crop up later that required an even more specific selector.

We had an issue in Foundation 5 where one specific visibility class didn't have `!important`. For 6, we ensured that every visibility class has `!important`. As utility classes, we have to ensure they work everywhere. `.hide.hide` will beat `.button.expanded`, but only if that class comes *after* the button in the CSS file, and it won't work if you add an one tag to that selector. `!important` is the most bulletproof way to do this. We're trying to limit our use of `!important` to *just* utility classes, although there are one or two lingering in components. We'll weed those out over time.

As far as the jQuery issue, managing state through classes instead of `.show()` and `.hide()` is going to be more sustainable in the long run anyway.

**Comment by esaborit4code** [comment]
Agree.

Thank you for your clear answer, @gakimball.
