### ISSUE TITLE
[Off-canvas] Scrolls to top on open by large content

### ISSUE THREAD

**Issue by Silvester20** [zurb/foundation-sites#8050]
When I click on the "open left panel" button the page scrolls to top, which shouldn't. The "forceTop" option is already set to false so I don't know why it scrolls to top. Maybe a bug? At least it is very annoying, maybe someone knows how to prevent this scrolling?

http://codepen.io/anon/pen/ZQoVPr

**Comment by Baedda** [comment]
I have got the same issue. As I look in the code of foundation.offcanvas.js I can see, that this option is not in use right now. Every line in the code that is relevant for "forceTop" is commented out.

```javascript
OffCanvas.prototype.open = function(event, trigger) {
  if (this.$element.hasClass('is-open') || this.isRevealed){ return; }
  var _this = this,
      $body = $(document.body);
  $('body').scrollTop(0);
  // window.pageYOffset = 0;

  // if(!this.options.forceTop){
  //   var scrollPos = parseInt(window.pageYOffset);
  //   this.$element[0].style.transform = 'translate(0,' + scrollPos + 'px)';
  //   if(this.$exiter.length){
  //     this.$exiter[0].style.transform = 'translate(0,' + scrollPos + 'px)';
  //   }
  // }
```

This is a huge usability problem. Why this code isn´t in use?

**Comment by zurbchris** [comment]
Talk to the guys who make Safari. *cough cough* Seriously though, it works great in Chrome, Firefox, Edge, and even IE 11, but the code you are referring to breaks on Safari, which is why it's not in use. Off-Canvas as a concept is a tricky one, and very difficult to make work cross-browser. For a very similar experience to an off-canvas, I humbly recommend a solution like [this codepen](http://codepen.io/zurbchris/pen/adEJJg).

**Comment by Baedda** [comment]
Hey chris,
what do you mean with _it works great in Chrome_? On my enviroment the page scroll up to the top in Google Chrome. And this is a hard coded feature in the plugin that can´t be disabled at the moment.
`$('body').scrollTop(0);`

**Comment by zurbchris** [comment]
As in, when I was developing it, (in Chrome), the default action was the Off-canvas was sticky relative to the viewport and would allow the page scroll to remain wherever it was on opening. This broke in browser testing, requiring the off-canvas to be positioned at the top of the document, that, coupled with auto-focus and focus trapping for accessibility reasons, forces the page to scroll to the top. There's not much I can do about it at this time, because we can't drop support for Safari, and as of yet, don't have another solution that works on all browsers.

**Comment by Silvester20** [comment]
Did you even take a look at my example? If you did and maked some tests in different browsers you will notice that it only works in Firefox. In other words, only in Firefox the off-canvas doesn't scroll to top on close/open panels, in all the other browsers it does.

Thanks for the other solution though, but still the mentioned issue with the off-canvas is a serious one. Not only me and Baedda complaining about it, so I hope this could be fixed in the next release.

**Comment by zurbchris** [comment]
That is exactly what is expected based on the current implementation @Silvester20, except the weird thing in Firefox. It should scroll to the top on all browsers if there's a focusable element contained in the off-canvas pane. Again, this is not how I *wanted* to build this thing, it's just I'm limited to what I can do with translates and transforms on the entire content section of a page and maintain browser support.

**Comment by Baedda** [comment]
I understand the reason what the forceTop option is used for and I understand why this is nenecessary.
But in my case I want to disable this behavior. I set forceTop to false and autoFocus also to false. I just want the off-canvas to slide in without effecting the scrolling in any way.
But in Chrome it jumps to the top and this doesn´t happen in Firefox or IE.

@Silvester20 did the same thing. He used `data-options="forceTop:false;"`to set the option to false so I think that he doesn´t want to have that browserjump. But the jump happens every time the Off-Canvas is opened. But it should only happen if the Off-Canvas is revealed or the option is set to true.
