### ISSUE TITLE
Equalizer inside tabs not updating height on tab change

### ISSUE THREAD

**Issue by dvolz** [zurb/foundation-sites#8073]
http://foundation.zurb.com/sites/docs/equalizer.html#applyheight
I have `.parent-row` inside multiple tabs with two columns that I am equalizing. Equalizer equalizes the first tab's columns on load, but on tab change, equalizer does not update and keeps the height of the columns in tab-1.
```
var elem = new Foundation.Equalizer($('.parent-row'));
$('.tabs').on('change.zf.tabs', function() {
  elem.applyHeight();
  console.log('test'); // This works
});
```

**Comment by zurbchris** [comment]
Without seeing your markup, there's one of two things going on:
1) You're trying to use 1 Equalizer plugin to equalize elements contained within *different* tabs, which won't work, because inactive tabs have display: none;, and therefore, don't have a height.
2) You're trying to instantiate multiple Equalizers, 1 per tab, programmatically. If this is the case, you need to initialize each one individually, or let Foundation do it, using data-plugin attributes.

Here's a thought, related to potential cause 2:
```js
$('.tabs').on('change.zf.tabs', function(e, tgt){
  $( tgt.find('a:first').hash ).find( '[data-equalizer]' ).foundation( '_reflow' );
});
```

Side note: `Equalizer.applyHeight` requires an array of heights which is calculated by `Equalizer.getHeights`, so at the very least what you would have to do is what is in Equalizer itselft: 
```js
elem.getHeights(function(heightsArray){
  elem.applyHeight(heightsArray);
});
```

**Comment by dvolz** [comment]
Thanks for the help @zurbchris - the example code really helps. I could see that helping a lot people in the documentation as well. The JS skill level necessary to do stuff in F6 seems higher than F5, some example code might help the more novice users figure stuff out. 

Thanks again!
