### ISSUE TITLE
RTL support for box util

### ISSUE THREAD

**Issue by n0o0bSina** [zurb/foundation-sites#8074]
Box util does not support RTL views according to that some plugins like "dropdown" does not work correctly.

**Comment by abdullahsalem** [comment]
Thanks @n0o0bSina for opening this issue, I agree with you, and I've gusseted this solution in PR #7928  
I am not sure if that is a perfect solution from engineering perspective, because I think every utility should be independent component, but I used `Foundation.rtl()`. Anyway, I generally believe that the Box utility must be aware about the current direction before it sets the box's position.

**Comment by n0o0bSina** [comment]
Your right but each application have its own engineering perspective if you check other utilities you can see Foundation object also used. don't worry and tanks for fixing brother :+1:

**Comment by abdullahsalem** [comment]
Thanks @n0o0bSina

**Comment by abdullahsalem** [comment]
Hi @n0o0bSina,
I've just noticed what you mentioned about the issue. In face, I just added the code that fixes the direction, but if you believe that there is additional fix should be added, it would be nice if you send a PR :)
By the way, I didn't check out the case you mentioned yet; because I am too busy these days.
Thanks,

**Comment by kball** [comment]
the fix from #7928 has made it into 6.2-stable here: https://github.com/zurb/foundation-sites/commit/dec7a581bc6b879a7afc8ec3ae9752ba32b1358a, which should fix this
