### ISSUE TITLE
Possible Incorrect import path

### ISSUE THREAD

**Issue by thecodegoddess** [zurb/foundation-sites#8098]
foundation-sites/assets/foundation.scss shows 
`@import './scss/foundation';`

shouldn't it be 
`@import '../scss/foundation';` to resolve correctly?

**Comment by gakimball** [comment]
That file is mostly for us to use—it assumes you have the current working directory as a load path. That being said, can't hurt to change the path to be relative.

**Comment by gakimball** [comment]
It's worth noting, however, that to get full control over what elements of the framework you're using, we recommend loading the framework files directly (under the `scss` folder, rather than `assets`). [Here's an example entry Sass file](https://github.com/zurb/foundation-sites-template/blob/master/scss/app.scss) from one of our Sass templates.
