### ISSUE TITLE
Simple Menu Align Right problem

### ISSUE THREAD

**Issue by anteksiler** [zurb/foundation-sites#8102]
Simple Menu that is aligned right should reverse the link margin:

```
<ul class="menu simple align-right">
```

**Comment by andycochran** [comment]
Why not use `.text-right` instead of `. align-right`?

**Comment by andycochran** [comment]
Actually, the same issue applies. That doesn't fix the margin issue.

**Comment by andycochran** [comment]
Trying to sort this out… 

It can be fixed by adding this to `@mixin menu-simple` in `_menu.scss`: 
```scss
&.align-#{$global-right} {
  li {
    margin-#{$global-right}: 0;
    margin-#{$global-left}: get-side($menu-item-padding, $global-right);
  }
}
```

However, applying the `.align-right` class also causes any `.menu` (simple or otherwise) to lose its height. Not sure if this is desired. It can be fixed by adding this to `&.align-#{$global-right} {}` in `@mixin foundation-menu`: 

```scss
&::after {
  clear: both;
  content: '';
  display: block;
}
```

@gakimball Any thoughts on this? I'll make a PR…

**Comment by JeremyEnglert** [comment]
I understand the issue here, but I also think this is something that is easily handled on a case-by-case basis. It also looks like other changes to how the menu works has improved on issues mentioned here. 

Closing this.
