### ISSUE TITLE
Add docs how to close a callout via JS

### ISSUE THREAD

**Issue by timaschew** [zurb/foundation-sites#8150]
For React users and other libraries like that, closing a callout doesn't work how it's explained in the docs.

I started the debugger and figured out that there is a `$(calloutElement).fadeOut().trigger('closed.zf')` statement.
Calling the statement by hand works.

**Comment by gakimball** [comment]
Do you mean this example?

```html
<div class="alert callout" data-closable>
  <h5>This is Important!</h5>
  <p>But when you're done reading it, click the close button in the corner to dismiss this alert.</p>
  <p>I'm using the default <code>data-closable</code> parameters, and simply fade out.</p>
  <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
    <span aria-hidden="true">&times;</span>
  </button>
</div>
```

**Comment by timaschew** [comment]
yes

**Comment by gakimball** [comment]
Any plugin that responds to the click events done with `data-toggle`, `data-open`, or `data-close` can be done programmatically by triggering a `toggle`, `open`, or `close` event on the element.

So for the callout, you can trigger the close with a `close` event:

```js
$('#callout').trigger('close');
```

Is that what you're looking for?

**Comment by timaschew** [comment]
Okay, just don't understand why I need to do it by hand in this case of callout. 
Is this part documented anywhere?

But when using the responsive topbar it works without any modification. So clicking the hamburger to toggle the menu.

**Comment by gakimball** [comment]
You shouldn't have to do it programmatically—the HTML example in the live documentation works as intended.

If you're using the framework with React, though, that might be introducing some other issues. Can you explain in more detail what exactly you're trying to do?

**Comment by timaschew** [comment]
> $('#callout').trigger('close');

Nope this doesn't work.

Here is a codepen
http://codepen.io/timaschew/pen/zrQopb?editors=1010

**Comment by gakimball** [comment]
I don't have a ton of React experience so I'm not sure what the issue is. If React is blocking typical DOM events (since it uses its own event system) then they aren't going to fire. The triggers are handled through one delegated event on the `document`:

```js
$(document).on('close.zf.trigger', '[data-closable]', function(e) {
});
```

So if React is preventing this event handler from being attached, *or* if React is preventing the `click` event on the close button from bubbling up, then using `.trigger()` won't work.

Thankfully it seems like you have a workaround. Note that for most plugins you won't have this issue, because you can call plugin methods directly, for example:

```js
$('#modal').foundation('open');
```

It's only the open/close/toggle triggers that have this other behavior.

**Comment by isapir** [comment]
@gakimball I actually _was_ looking for https://github.com/zurb/foundation-sites/issues/8150#issuecomment-183514245

    $('#callout').trigger('close');

How come it is not in the docs?  At least I couldn't find it there.
