### ISSUE TITLE
Add Color Helper CSS Classes

### ISSUE THREAD

**Issue by jshdoubleu** [zurb/foundation-sites#8160]
I imagine helper classes for text colors could be very useful.

What if you don't want a heading not to be in primary color or with class "subheader" in light-gray but in your secondary or medium-gray?

For Example: Create for each color:
```
.text-color-#{$color-name} {
  color: {$color-value} !Important;
}
```
so you can do the following:
```
<h1 class="text-color-secondary">Some heading in secondary color</h1>
<p class="text-color-medium-gray">A very medium day and text</p>
```

**Comment by Deckluhm** [comment]
Since [`6.1.1`](https://github.com/zurb/foundation-sites/releases/tag/v6.1.1), you can override the [`$foundation-colors`](https://github.com/zurb/foundation-sites/blob/v6.1.1/scss/_global.scss#L106) map to add / modify any color you want.

Then you can easily iterates through this map to create your own classes like this:
```
@each $name, $color in $foundation-colors {
  .text-color-#{$name} { color:$color !important; }
}
```
However, I highly recommend you to avoid using the `!important` flag when you can.

You could instead use the same design Zurb is using for many components in Foundation (`buttons`, `callouts`, `badges`...etc.) and avoid using `!important`:
```
@each $name, $color in $foundation-colors {
  h1.#{$name} { color:$color; }
}
```
Then you can use colored `h1` titles using the same syntax than with other Foundation components:
```
<h1 class="success">I'm a green title</div>
<h1 class="warning">I'm a yellow title</div>
<h1 class="alert">I'm a red title</div>
```

**Comment by gakimball** [comment]
We try to keep our suite of utility classes slim, so text color classes aren't of interest to us right now.
