### ISSUE TITLE
Reveal full-width on smaller screens

### ISSUE THREAD

**Issue by designerdean** [zurb/foundation-sites#8166]
Is there a way to change the reveal/modal so that it's not full width on smaller screens? I've rounded the corners of the modal in my environment and it looks strange being flush to the left and right sides.

**Comment by rafibomb** [comment]
The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
