### ISSUE TITLE
Move to ESLint

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#8169]
With [ESLint 2.0](http://eslint.org/blog/2016/02/eslint-v2.0.0-released) out, it seems like as good a time as any to hop on that bandwagon. We'll take whatever rules exist in our [current JSHint config](https://github.com/zurb/foundation-sites/blob/develop/.jshintConfig) and adapt them to ESLint rules where possible.

**Comment by colin-marshall** [comment]
Just got this setup using [gulp-eslint](https://github.com/adametry/gulp-eslint) and [babel-eslint](https://github.com/babel/babel-eslint). It works but we might want to put this on hold until babel-eslint adds support for ESLint 2.0: babel/babel-eslint#253, babel/babel-eslint#254. Doesn't sound like it's too far off.

Sass-lint is almost ready btw.

**Comment by gakimball** [comment]
I knew I could count on you! :) Keep us posted.

**Comment by colin-marshall** [comment]
After comparing with JSHint, I think the ESLint is probably ready to go as is. I think the `.jshintConfig` file wasn't even being read because it needed to be named `.jshintrc`.

I started by running `.jshintConfig` through [ESLint-Rules-Mapper](https://github.com/valorkin/eslint-rules-mapper) and made some adjustments from there. Most important change to note is that I switched from the default parser to babel-eslint.

The rules in `.eslintrc` are set with the numbers 0, 1, or 2.

**0 = disable** rule
**1 = warning** on break of rule
**2 = error** on break of rule

ES6 modules are currently turned off. Turn them on by changing `"sourceType": "script"` to `"sourceType": "modules"` under `"parserOptions"`.

I think you can take it from here :)

**Comment by gakimball** [comment]
@colin-marshall Regarding the old file not being read, yes, that was our mistake ;)

And you may have noticed I stripped the `import` and `export` statements out of the upgraded code. We decided to hold off on UMD support for now, because it turned out to be a bigger problem to adapt our existing codebase.

**Comment by gakimball** [comment]
Merged #8182
