### ISSUE TITLE
[Feature] [Request] VCard, Inline List, PricingTables/Panels

### ISSUE THREAD

**Issue by SalahAdDin** [zurb/foundation-sites#8171]
Hi guys, i like your work.

I'd been thinking about three features that you had but now you deprecated it.

Inline list is one of this, but, i think that this can replace putting `display: inline block`, but in the old version had many other sass properties.

VCard it's a good presentation card template, i'm using it, but with the new version i didn't what do i do. WIll be very useful for us.

Pricing tables ware a good feature that could replace Bootstrap Panels but you deprecated it, why? Have many uses.

In addition, i think that Boostrap List Groups will be very good feature for foundation, because is a good and beautiful way for do a group list.

And, add a degrade colours for callouts as Boostrap Alerts.

Thank you very much guys, if you want i can help with this features. Thanks.

**Comment by Deckluhm** [comment]
**Inline Lists**

Here is the Foundation 6 alternative to Foundation 5 Inline Lists:
http://foundation.zurb.com/sites/docs/menu.html#simple-style

As said in the documentation:
> This style imitates the inline list from Foundation 5.

**Callouts**

Callouts already have `$callout-background-fade` variable you can set (from 0 to 100%) to adjust the background color contrast.

**vCards**

Personally I don't think vCards should be back. There are so many different information a vCard can contain, I think it is better for everyone to create his own component which fit their own needs (instead of trying to do a vCard component with dozens of Sass variables to please everyone's needs).

**Pricing Tables**

For pricing tables, I don't really know what to think. It was pretty convenient to have it in Foundation 5 but at the same time I'm not sure it should be in a framework like Foundation.

You should take a look at #6194, there are some interesting thoughts on pricing tables (and more generally any removed components from Foundation 5).

**Comment by andycochran** [comment]
<p data-height="268" data-theme-id="0" data-slug-hash="MKxMQK" data-default-tab="result" data-user="andycochran" class='codepen'>See the Pen <a href='http://codepen.io/andycochran/pen/MKxMQK/'>Foundation 6 Pricing Table</a> by Andy Cochran (<a href='http://codepen.io/andycochran'>@andycochran</a>) on <a href='http://codepen.io'>CodePen</a>.</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

**Comment by gakimball** [comment]
Thank you for the thorough reply, @Deckluhm! You're spot on in your response. vCards and pricing tables felt like niche components to us, which is why we dropped them.

As for little things like list groups, it comes down to a difference in philosophy. We generally don't bake in as many modifier classes or variations on core components, to keep the core of the framework lighter.

We have a bunch of premade UI elements on [Building Blocks](http://zurb.com/building-blocks), including a few pricing table designs.

**Comment by SalahAdDin** [comment]
@andycochran Thank's.
@gakimball Man, but you come back Orbit, and, for this, thank you.
