### ISSUE TITLE
news-magazine.html

### ISSUE THREAD

**Issue by Simeto** [zurb/foundation-sites#8189]
At news-magazine.html. When you click on the dropdoun menu button and then outside of the menu, the dropdown list isn't hide durin you hover the menu again.

**Comment by Deckluhm** [comment]
This is because [news-magazine.html](http://foundation.zurb.com/templates-previews-sites-f6/news-magazine.html) (and probably other templates) doesn't use the latest Foundation version (`6.0.0` instead of `6.1.2`).

It works as expected if you use the latest version: http://codepen.io/anon/pen/OMYPxL

Next time you open an issue, please provide a link of the page you are talking about, it wasn't obvious you were talking about a template page ;)

**Comment by gakimball** [comment]
We have a new minor version of Foundation coming out soon (6.2 on Friday), so when that's out, we can take a look at upgrading our example templates.

**Comment by Simeto** [comment]
Thank you for the ansewrs. I will take a look when the new version is comming.
