### ISSUE TITLE
Crossfade Animation with Toggler? 

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#8211]
With Toggler being able to [handle multiple elements in 6.2](https://github.com/zurb/foundation-sites/issues/7806), I am curious if there is someway to create a crossfade type effect, using only Toggler (and the Motion UI, of course)? 

The only way I see to do this is to position the two elements that need to be cross-faded with absolute positioning which has it's drawbacks and I want to avoid any absolute positioning. 

Is there a way to achieve this? 

If there is a way, then I please consider this a feature request or a request for a building block example.

**Comment by gakimball** [comment]
It wouldn't work out of the box, and it's actually pretty complicated.

To get the elements to properly cross-fade, they have to be sitting on top of each other. To do that, one of them has to be `position: absolute`. If they're not the same height, *then* you need to ensure that the shorter element is the one that has `position: absolute`. Otherwise, if a tall element gets the property, it will be overlapping the content below it.

You might be able to set it up by tapping into the `.mui-enter` and `.mui-leave` classes, which are dynamically applied to the elements as they transition in and out.

**Comment by Lynda333** [comment]
@gakimball - I played around with a few ideas but nothing worked well. I ended up using some of my own javascript that has absolute positioned elements and used JS to calculate the heights. I did find a few jQuery plugins that help with this and I believe it's best left to them or a custom solution than something Foundation should integrate.

**Comment by gakimball** [comment]
Agreed :) Orbit is the one place where we do this, and it does require a lot of setup, which makes it tricky to bake into the framework as a generic thing.
