### ISSUE TITLE
Different browser interpret for flex grid

### ISSUE THREAD

**Issue by pgrmCreate** [zurb/foundation-sites#8212]
Foundation use flex grid and with Advanced Sizing, we can typing : 

```
<div class="row">
         <div class="columns">Whatever's left!</div>
         <div class="small-4 columns">4 columns</div>
</div>
```

On  chrome : A colum with 4 size and a other block will take left place
On firefox : A column with 4 size and a other row block with 12 places

It is normal ?

**Comment by gakimball** [comment]
Can't recreate this in the latest version of Firefox, what version do you have?

See: <http://codepen.io/anon/pen/mVZvyY>

**Comment by pgrmCreate** [comment]
Excuses me Gakimballl, i forget important informations : My container without size has image.

You can see that here : http://codepen.io/anon/pen/RrXaJw

**Comment by emolr** [comment]
@pgrmCreate what you describe sounds like a side effect from the way firefox handles images with are larger than the container. 

e.g. If the container is 500px wide (relative with flex or %) and the image is 900px wide. 
Then firefox does not respect `max-width: 100%` on the image in the same way as webkit. 
`max-width: 100%`on an `img` in firefox does not make the `img` shrink just because the parent container is smaller. 

They don't mix it up so to say, and only looks at the image width.

So I would not say it's a bug in the grid, but different implementations of the max-width property on images in the different browsers.

I hope it clarifies your issue :)

**Comment by pgrmCreate** [comment]
Yes, perfectly **emoir**, thanks you for your indications

**Comment by gakimball** [comment]
We're aware of this issue, but there's not an easy way to solve it.

Like @emolr said, Firefox won't respect `max-width: 100%` on an image instead of a flex child. The solution is to add a `width` of any kind to those images, either `100%` or a defined value.

We can't set that as a framework default, or it would mess up people's designs. So instead, we added a [callout in our documentation](http://foundation.zurb.com/sites/docs/flex-grid.html#browser-support) explaining the problem and the solution.
