### ISSUE TITLE
Yeti Launch: Error: EBUSY/An error occured in task ‚clean‘.

### ISSUE THREAD

**Issue by suntrop** [zurb/foundation-sites#8213]
I downloaded Yeti Launch today to test it for my new project.
On the first run everything looked good, but after I changed the title in layouts/default.html and put two images in the assets folder and a PDF in the project root it stopped working.

When I run the project I always get this:

```
 $ Starting 'build‘...
 $ [15:27:22] Starting 'clean‘...
 $ [15:27:22] 'clean' errored after 9.08 ms
 $ [15:27:22] Error: EBUSY, unlink 'dist/index.html‘
 $ at Error (native)
 $ [15:27:22] 'build' errored after 13 ms
 $ [15:27:22] Error in plugin 'run-sequence‘
 $ Message:
 $ An error occured in task ‚clean‘.
```

I had restarted my Mac (latest El Capitan) already, but I get this error all the time I try to run the project.
Don’t know where that error comes from.

**Comment by colin-marshall** [comment]
@suntrop sorry for the super late response to this issue. I'm not sure if this applies only to Yeti Launch (which is no longer in development/supported) or if it is also present in all template installs. Since this older I'm going to close it out as we tidy up the open issues. Feel free to reopen if the problem persists for you. Thanks!
