### ISSUE TITLE
docs: prevent anchor tags jumping top

### ISSUE THREAD

**Issue by fx3O2** [zurb/foundation-sites#8219]
Hey there, new foundation user here! :bear: :beer: 

So I read the docs and see a lot of demos I like to try out and play around with. There is just this one thing driving me crazy. Some links don't seem to have a target defined and jump top :top: while some others toggle just some fluff (offcanvas, dropdown, ...). This isn't really consistent. So instead of jumping top, wouldn't it be much more pleasant to stay at the same position and add some `#marker`? Even if I know, I just can't stop clicking on those links. :joy_cat:

Thanks!

**Comment by fx3O2** [comment]
Oh, I just saw there is a docs repo. :crying_cat_face:

**Comment by gakimball** [comment]
So the problem is, we want `href`s in our example so people remember to add them. Like if it's a link in a menu, we want it to have `href` in the code example. However, if you put `href="#"`, the page jumps to the top, and if you put `href=""`, the page reloads. So there's not a *super* great way to have code examples like that.

We tend to just put `href="#"` on everything. Now, any JavaScript plugins that involve clicking on things, we always cancel the default click action so it won't jump to the top. So anywhere in the docs you're seeing links jump to the top, they're just plain ol' links.

If there are any specific examples where the intended behavior confuses you, let me know. :)

**Comment by fx3O2** [comment]
@gakimball You still can have `href`s. Just setting it to `#` isnt enough. You need to set them to some non-existent target, e.g `href="#asdf". This would be the super great way and it will never jump. There are enough of these links on the [kitchen sink](http://foundation.zurb.com/sites/docs/kitchen-sink.html) page.
