### ISSUE TITLE
Inline Button inside of top-bar

### ISSUE THREAD

**Issue by dedayoa** [zurb/foundation-sites#8224]
Hello,
I'm using Foundation 6. See my code below

```html
<div class="top-bar-right">
   <ul class="menu">
   <li>
   <div class="input-group">
   <input class="input-group-field" type="text">
   <div class="input-group-button">
   <input type="submit" class="button" value="Submit">
   </div>
   </div>
   </li>
   </ul>
</div>
```

I discovered that the margin-right property of. `.top-bar input` gets applied to the button causing it not to display as expected (margin to its left)

**Comment by kball** [comment]
I appreciate the code snippet, but I'm not 100% clear what the issue was and what you expected to happen, or which version of 6 you were using.  Going to close, if you're still seeing this with foundation 6.2.1 please reopen with the info requested here: https://github.com/zurb/foundation-sites/blob/develop/.github/ISSUE_TEMPLATE.md
