### ISSUE TITLE
No Shadow on hover of Media Element Section Thumbnail

### ISSUE THREAD

**Issue by LDigital84** [zurb/foundation-sites#8227]
Within a media element section you have this: 

    <div class="media-object-section">
         <div class="thumbnail">
            <img src= "assets/img/avatar-1.jpg">
         </div>
      </div>

When you hover over that image a shadow (or glow I guess you could say) appears. This is fine _for links_ but if there is no link, no shadow should show. 

This happens because of this: 

    .thumbnail:hover, .thumbnail:focus {
        box-shadow: 0 0 6px 1px rgba(33, 153, 232, 0.5);
    }

If it has a link or some action, then the shadow is appropriate, otherwise, there should be no shadow.

**Comment by andycochran** [comment]
:+1: I'm for removing this altogether. If you want your thumbnails to glow, do so in your app.

**Comment by Lynda333** [comment]
I don't mind it on images with links but not on images alone.

**Comment by gakimball** [comment]
I can get behind this, it's a holdover from Foundation 5 where the `.th` class was specifically designed to go with the Clearing lightbox.

A PR will need to be targeted at a 6.3 branch, which we don't have yet.

**Comment by kball** [comment]
@andycochran can you tackle this?

**Comment by andycochran** [comment]
@kball There's a style in `/node_modules/foundation-docs/scss/_page.scss` that conflicts with this fix. 

```scss
.docs-component .thumbnail {
    display: block;
}
```

How can I nix this?

**Comment by kball** [comment]
how does it conflict?

**Comment by andycochran** [comment]
@kball Actually, it's not a conflict with the fix. I'll go ahead and PR and the docs styles can be handled separately. 

So, the fix is to only put the hover shadow on thumbnails that are links. The docs say the `.thumbnail` class can go on an `<a>` that wraps an `image`. And since the docs force thumbails to `display:block`, the `<a>` is the full-width of its container. However, the image it wraps might not fill that width. So you get this: 

<img width="713" alt="screen shot 2016-04-27 at 5 43 34 pm" src="https://cloud.githubusercontent.com/assets/409279/14869146/a41a1e62-0c9f-11e6-8d93-92d8aa59c9b8.png">
 
This is a problem regardless of my PR. You just can't see it 'cause the docs don't actually include an example of `.thumbnail` on and `<a>`.

**Comment by andycochran** [comment]
@kball I think all of the `.docs-component .thumbnail` styles can be removed. They only center the thumbnails in the columns. That could be done with `.text-center`.
