### ISSUE TITLE
Feature Request: Outer Labels on Switches

### ISSUE THREAD

**Issue by LDigital84** [zurb/foundation-sites#8266]
With switches you have the ability to have [inner labels](http://foundation.zurb.com/sites/docs/switch.html#inner-labels). I like this ability but as I was working with a site a few weeks ago I had my client say he was confused by the inner labels. Which was "on" which was "off"? Or in my case, which was yes, which was no?

So I asked on [UX Stackexchange](http://ux.stackexchange.com/questions/89151/using-switches-for-yes-no-checkboxes) about my dilemma. What would be the best solution? The solution was, what I would call, outer labels. In other words, the labels are outside the switch but indicate which way the switch is flipped. Here is a screenshot: 

![outer-label](https://cloud.githubusercontent.com/assets/1938824/13377007/13fdc7ee-dd87-11e5-9ec1-a71a14e8ba26.jpg)

I manually coded the example you see in the screenshot but I would like to request this as a feature of the switch and not one that we have to manually code. 

Thank you!

**Comment by andycochran** [comment]
Yeah, switches can be a confusing UI element. If my answer is no, I can click an element that says “No” but then it says “Yes.” Have I answered yes or no? Hmm… 

It's all in how you use 'em. 

Switches are most confusing when the only feedback is the switch's state (e.g. a form that must subsequently be submitted). Switches are most useful when an obvious change is instantly apparent separate from the switch itself (e.g. a content section's visibility is toggled or a feature is enabled/disabled). 

Consider only using switches the way you'd use IRL ones. Something happens when you flip a light switch—a light turns on/off—regardless of whether it's labeled on/off. 

If you can't determine the state of a switch, you might be better served by a different element. Maybe try `<input type="radio">`.

**Comment by colin-marshall** [comment]
We will revisit this feature request for outer labels on switches in F7. Thanks!
