### ISSUE TITLE
v6.2 JavaScript does not play nice with Angular

### ISSUE THREAD

**Issue by designerdean** [zurb/foundation-sites#8289]
We upgraded our Angular app to use Foundation v6.2. The styling and positioning of the reveal modal is a lot better. However, Angular inside of the reveal modals doesn't execute anymore. It was working fine with Foundation v6.1.2. The browser console shows no errors, it just acts as though the Angular code is plain HTML. Angular doesn't execute inside the reveal modals at all. Our team has spent hours trying to figure it out, but with no luck. Ideas? Help?

BTW, we are using Angular v1.3.15.

**Comment by gakimball** [comment]
Other than reworking the positioning logic, the other change we made to Reveal in 6.2 is moving the HTML of the modal to be inside the overlay element in the DOM. Before, the modal sat wherever it was in the document originally, which created a lot of issues with scrolling and positioning.

The issue might be related to the modal's HTML being moved.

**Comment by designerdean** [comment]
@gakimball Is the reveal modal documentation (http://foundation.zurb.com/sites/docs/reveal.html) updated with the latest recommended markup?

**Comment by gakimball** [comment]
Yes, the markup hasn't changed.

**Comment by designerdean** [comment]
@gakimball Would you be able to look at our testing environment? Maybe there's something you'll see that I'm not saying. The link is below. Just scroll to the bottom of the left panel and then click "View results on other sites." Then enter a zip code in the search box and hit magnifying glass button. It's just refreshing the page instead of submitting the form.

https://platform-homie-dev.azurewebsites.net/

**Comment by gakimball** [comment]
> Is it possible the HTML is being moved after Angular initializes?

Depends on when you call `$(document).foundation()`. I would assume you have to call that after the complete Angular view has been initialized, so that the DOM is in place for Foundation plugins to attach to.

With that in mind, it's possible you need to listen for when the modal is done initializing, and then add some extra logic to account for it.

```js
$('#modal').on('init', function() {
  // ...
});
```

I see the issue you described in the page you linked. You might need to set up that Angular logic *after* the modal is moved, if possible.

**Comment by JAndritsch** [comment]
It doesn't appear to be just Angular. I am building an app using React and found out that my onClick handlers inside the Reveal markup are no longer firing after upgrading from 6.1.2 to 6.2. 

Here's a sample of the code I am trying:

```
        <div className="reveal tiny" id="loginModal">
          <h1>Log in</h1>
          <div>
            <label>Username:</label>
            <input type="text" name="username" />
          </div>
          <div>
            <label>Password:</label>
            <input type="password" name="password" />
          </div>
          <div>
            <button className="button" type="button">Log in</button>
          </div>
          <button className="close-button" type="button" onClick={this.handleCloseModalClick}>
            <span>&times;</span>
          </button>
        </div>
```
It seems like relocating the modal causes Angular/React bindings to fail because they're no longer nested within their mount node. Both Angular and React applications require you to define a parent element where your application with live. Relocating the modal essentially moves the node outside of that parent and it no longer becomes part of the application.

**Comment by designerdean** [comment]
I don't suppose anyone has had any luck with this?

**Comment by JAndritsch** [comment]
Unfortunately I just had to roll back.

**Comment by gitnik** [comment]
click handlers also stopped working for me in angular 1.5. Since I obviously need the correct reveal positioning what am I supposed to do now?

**Comment by circlingthesun** [comment]
This might help: http://circlingthesun.github.io/angular-foundation-6/

**Comment by kball** [comment]
I think @circlingthesun's approach is correct.  Angular and React both operate under the assumption that they have complete control of the DOM, so interacting with Foundation 6's javascript plugins directly is always going to be a bit hit or miss.

It looks like a similar project for react is here: https://github.com/aruberto/react-foundation-components
