### ISSUE TITLE
Responsive Form middle label

### ISSUE THREAD

**Issue by DaSchTour** [zurb/foundation-sites#8299]
**How can we reproduce this bug?**

```html
<form>
  <div class="row">
    <div class="small-12 medium-3 columns">
      <label for="middle-label" class="middle">Label</label>
    </div>
    <div class="small-12 medium-9 columns">
      <input type="text" id="middle-label" placeholder="Right- and middle-aligned text input">
    </div>
  </div>
</form>
```

**What did you expect to happen?**

For this example I would like to have the label above the input with no padding on small devices. But on bigger devices I need the label so be alligned on the middle to the input. So it would be nice, if the middle would not add padding if it's inside a full width column.

**Possible solution**

```sass
form .columns {
	@each $breakpoint, $gutter in $grid-column-gutter {
		&.#{$breakpoint}-#{$grid-column-count} {
			label.middle {
				padding: 0;
				margin: 0;
			}
		}
	}
}
```

**Comment by kball** [comment]
@brettsmason @andycochran @JeremyEnglert does this seem like a reasonable thing to do, or is this something that should happen at the application layer?

**Comment by andycochran** [comment]
I understand the desire for responsive `.middle` labels. I think that's a 100% valid request. But I don't think it should be tied to the grid. That makes too many assumptions. 

The `.middle` class could be reworked to be responsive. However, the class names could get ugly, e.g.: 
```html
<label class="medium-middle large-unmiddle">Label</label>
```

How do you say, "not middle?" 

Regardless, I don't think "middle" is even semantic—especially since the label doesn't align to the middle of taller form elements like a `textarea`. Literally, it's "padded" not aligned to the middle. (Not that `.medium-padded` and `.medium-unpadded` are the solution.)

Any thoughts on how we might name a responsive version of `.middle`, which we can deprecate in a future version?

**Comment by andycochran** [comment]
I'm going to close this, as it's an edge case that should be done with app-specific styles.
```scss
@include breakpoint(small only) {
  .middle {
    padding: 0 !important;
    margin: 0 !important;
  }  
}
```
