### ISSUE TITLE
uncss causing issues when building for production.

### ISSUE THREAD

**Issue by baglio** [zurb/foundation-sites#8348]
**How can we reproduce this bug?**

When css are injected via javascript.

**What did you expect to happen?**

That uncss identifies the aforementioned code in order not to remove it.

**Test case:**

I'm using [Magnific Popup](http://dimsemenov.com/plugins/magnific-popup/) to add a lightbox effect. It uses some css classes which **aren't present in the code from the beginning**, but they're injected as the user interacts with the images.

This removes the classes from the final css output when running `npm run build`
I don't know if it's an expected behaviour or a bug; either way, I saw that uncss is also deprecated in favor of cleanCss.

Could this be the cause of the issue?

**Comment by gakimball** [comment]
There's two things you can do:

You can whitelist the Magnific Popup classes, which means UnCSS will ignore them. If you're using the most recent version of the ZURB Template, these options are in the file [`config.yml`](https://github.com/zurb/foundation-zurb-template/blob/master/config.yml#L13v). If you're using a slightly older version, those same settings are in your Gulpfile.

Looking at the class structure of Magnific Popup, they all start with `.mfp-`, so the ignore setting will look like this: `^\.mfp-.*`

Your other option is to just remove UnCSS entirely since it can sometimes be a hassle ;)

Let me know if that helps!

**Comment by baglio** [comment]
Thank you for your help gakimball.

Last night I've figured out how to exclude certain classes by copying the regex expressions which were already defined in the gulp.js file.

I was making sure everything was working properly before post anything else about this issue.
Thanks again, I hope this could be of any help to somebody. :)
