### ISSUE TITLE
Wrong anchor-color variable?

### ISSUE THREAD

**Issue by maiolica** [zurb/foundation-sites#8368]
Shouldn't this line:
https://github.com/zurb/foundation-sites/blob/develop/scss/typography/_base.scss#L124
`$anchor-color: $primary-color !default;`

be changed to:
`$anchor-color: map-get($foundation-palette, primary) !default;`

**Comment by andycochran** [comment]
Nope. The `_global.scss` file gets these 5 variables from the map: `$primary-color`, `$secondary-color`, `$success-color`, `$warning-color`, `$alert-color`. 

But if you add your own colors to the palette, you'll need to get them via `map-get`. 

Relatedly, I'm not sure what happens if you remove any of these 5 colors from the map. Are they required?

**Comment by colin-marshall** [comment]
@ncoden @andycochran is it ok to close this old issue out? Thanks.
