### ISSUE TITLE
Slider not showing the correct position when toggled from hidden

### ISSUE THREAD

**Issue by jspekken** [zurb/foundation-sites#8391]
When the slider is directly shown on the page everything works just fine and the slider slides to the correct position, but when a slider is displayed after the initial page load the slider will not slide to the correct position.

You can see this behavior here: http://codepen.io/anon/pen/EKyLmW

Maybe it's an idea to incorporate a method like the 'reflow' methods from foundation 5?

**Comment by gakimball** [comment]
We do have reflow plugins, although Slider appears to be missing one.

**Comment by jspekken** [comment]
@gakimball Do you know where I can find an example of a reflow plugin so that I can (maybe) create a pullrequest to fix this issue?

**Comment by gakimball** [comment]
@jspekken [Here's an example from Equalizer.](https://github.com/zurb/foundation-sites/blob/4c974baef093fe6c409496a81b52ac789a44a94d/js/foundation.equalizer.js#L116) It re-calls whatever internal logic is needed to set up the plugin properly. In the case of Equalizer, it's calculating the heights of every element in a set.

**Comment by coreysyms** [comment]
Tagging this to #9320 so I can add in a mutation event for Slider, this will fix the issue for 6.3. Will close this issue after I add in slider mutation.

**Comment by kball** [comment]
So this isn't actually solved by adding the mutation observer, at least as currently instantiated, because in this case the parent is what is changing... we'd have to put an observer on every parent for hidden elements (see e.g. this pen: http://codepen.io/seantimm/pen/lDeCv/).  I think I see the reason this is failing though, so going to fix it as well as add the mutation observers.

**Comment by kball** [comment]
actually, I'm not sure the right way to fix this because it currently depends on dimensions that don't exist when the object is display: none; Do we think exposing `_reflow()` is sufficient and requiring the user to call it after unhiding?

**Comment by coreysyms** [comment]
I made some notes over on #9379, I believe that passing in proper CSS values on init() will fix this. You can see in @jspekken code pen that the "fill" bar does properly layout after being toggled from display none, it's the "handle" that needs to get that value as well.

**Comment by kball** [comment]
@coreysyms the tricky thing is that while fill can be a straight percentage based on value, the handle is "offset" by its size, which is determined by css and read by the JS... not sure how we can prefill that... we could do a 'rough guess' and not do the offset, but it will result in the layout being slightly different if its adjusted while the slider is hidden instead of visible.

**Comment by kball** [comment]
Closing this as fixed based on #9379
