### ISSUE TITLE
Dependencies managed incorrectly in npm package

### ISSUE THREAD

**Issue by jescalan** [zurb/foundation-sites#8417]
The npm package presumably is intended to be used through some sort of module system, like webpack, browserify, etc. However, the actual script that it exposes is built like a typical attach-everything-to-window js file, wrapped in an IIFE that presumes jQuery to be present as a global.

For any module system, this doesn't work out. It just throws an error saying that the variable `jQuery` is missing, and there's no way to make it present other than attaching it to global, which kind of defeats the point of module systems. In addition, in es6 it's not possible, since imports are extracted and stacked at the top before other code.

The way I would go about solving this is by bundling jquery along with the npm package, and exposing both as exports. So, for example, in es6 you would import as such:

``` js
import {Foundation, $} from 'foundation-sites'
```

or in es5 or below:

``` js
var Foundation = require('foundation-sites')
var $ = Foundation.jQuery
```

...then you would have everything you need. While this slightly restricts the user from loading up their own version of jquery, if I'm not mistaken it's not advisable to do this anyway, since foundation's javascript expects a specific jquery version, and loading up a different version might mean things break, which just causes more issues and confusion. The way I see it, loading foundation and the correct version of jquery is a much easier way to do things -- you never have an issue with the jquery version's compatibility with foundation, and you can load em both up in one shot.

Now, in all likelihood most users are using foundation in the standard everything global manner, so you don't want this to break anything. Luckily, you can use a [UMD](https://github.com/umdjs/umd) wrapper to ensure that both are exposed as globals if loaded directly and not through a module system.

Would be happy to take a shot at a PR for this if it would be helpful!

**Comment by gakimball** [comment]
We want to get UMD support in, but we weren't able to make it work with Babel's UMD shim. This is because, while most UMD shims put a module on `window` as a fallback, all of ours are namespaced within `window.Foundation`, and others within `window.Foundation.util`.

I explain this in more detail in issue comments [here](https://github.com/zurb/foundation-sites/issues/7758#issuecomment-174599729) and [here](https://github.com/zurb/foundation-sites/issues/7758#issuecomment-183084377).

The solution might be a generic UMD shim plugin, where we override the methods it uses to generate module names and so on, as opposed to using Babel's module transforms.

If you want to take a crack at it we can support you in that effort.

**Comment by DaSchTour** [comment]
Just want to through in some points into the discussion.

1. What about other module loaders? For example SystemJS?
2. Why not use TypeScript and have full modules and maybe an easy way to build Angular 2 Directives around it and move away from jQuery?

**Comment by localpcguy** [comment]
It appears that TypeScript doesn't have any problems compiling the current JS, so I would support exploring that further, particularly for the use case of easily working with Angular2 down the road.

**Comment by colin-marshall** [comment]
@DaSchTour is it safe to close this out since we have other issues/PR's discussing TypeScript and module loading?

**Comment by DanielRuf** [comment]
> bundling jquery along with the npm package

Not a great idea.

In the production builds in our projects we solve this using specific webpack configs.

See https://webpack.js.org/configuration/resolve/ and https://webpack.js.org/configuration/externals/

https://stackoverflow.com/a/28989476/753676

There are the `resolve`, `ProvidePlugin`, and some loaders described.

**Comment by DaSchTour** [comment]
Well I have to admit, that from my point of view the current state of foundations javascript functions is: "throw it away and don't use it". For any new projects I would suggest to use just foundation SCSS and (re)build javascript functions of foundation in a modern javascript framework. So I would tend to close this. Changing the current javascript with jQuery to work with modern module loaders and bundlers may be a lot of work for nothing, because it's just a matter of time everybody has stoped using jQuery.

**Comment by colin-marshall** [comment]
Thanks @DaSchTour.
