### ISSUE TITLE
unCSS is breaking production builds by removing foundation classes

### ISSUE THREAD

**Issue by codexnovus** [zurb/foundation-sites#8483]
**How can we reproduce this bug?**

1. Step one
On foundation V 2.1.0, add a sticky menu. In my case I slightly modified the title bar example in documentation and add options so it would be sticky on small.
2. Step two
Verify it works in testing. Execute "npm build run" to build a production version
3. Step three
Open it. The script applies the class .is-stuck but unCSS removed it. 

I checked it out by disabling unCSS. Then it works.

Can provide build files if needed.

**Comment by fndaily** [comment]
Try adding this to your config.yml or unccss options:

```!!js/regexp ^\.(reveal)```

**Comment by ncoden** [comment]
Please always provide involved files.

UnCss analyse your html/js files and remove from Foundation and you CSS the unused classes.
This error shouldn't come from Foundation. The only way foundation classes could be removed is **you didn't pass to UnCSS your html/js files** using the Foundation classes.

Have you checked you passed all your html/js files to UnCSS ?

**Comment by nitrokevin** [comment]
this may be related, I'm using Yeti Launch and when I switch to production the UnCSS breaks part of the site, in my case the orbit slider no longer works

**Comment by imperator99** [comment]
Hey @codexnovus I had the issue over the last couple of days. Unfortunately the documentation for resolving it is lacking and it is _very_ hard to figure out which CSS styles are being removed, and the way the 'ignore' setting is implemented in the Foundation default gulpfile.js does not seem to work. I resolved this issue with Sticky (and also Interchange and Modernizr) by using the following 'ignore' settings (taken from [here](https://github.com/blixmbe)):
`ignore: [
      new RegExp('.foundation-mq'),
      new RegExp('.is-stuck'),
      new RegExp('.svg'),
      new RegExp('.cssanimations'),
      new RegExp('.csstransitions'),
      new RegExp('.multiplebgs'),
    ]`

Now, I initially began this site using Yeti Launch, but ditched it soon after because it was ruining my workflow (it doesn't play nicely with multiple computers). It also downloads an older version of Foundation, which doesn't include the flex-grid options and may also have a broken uncss setting.
I hope this helps.

**Comment by kball** [comment]
uncss has been removed from the template by default
