### ISSUE TITLE
Recruit more Yetinauts to work on issues and PR

### ISSUE THREAD

**Issue by ncoden** [zurb/foundation-sites#8499]
I see many issues and PR without response. I don't think it's a good thing for a so big and active community. You should recruit more Yetinauts to work on it.

**Comment by ncoden** [comment]
Hi @colin-marshall 

Since this issue I started to contribute a little to Foundation. I can't always resolve issues and purpose PR, but I can add tags, or close abandoned issues. It could help you by tracing the more important things.
Can the community give me the rights for this ? Thx

**Comment by colin-marshall** [comment]
@ncoden sorry for the slow response. Thank you very much for your contributions to Foundation! It's great to see fresh faces helping out.

The Yetinaut program is brand new. I believe if you keep contributing you will eventually be added on. I don't think that will take too long at the rate you are contributing. Your contributions won't go unnoticed by the people at ZURB, just give it a little time.

Keep up the great work!

**Comment by rafibomb** [comment]
@colin-marshall Thanks for jumping in! You've been doing great things!

@ncoden Great PR's! You're right! There is a great community around Foundation and there are lot's of people like Colin and yourself that contribute. We just launched the Yetinauts into space and are working to build this up more each week. Part of what we're doing moving forward will help people contribute in meaningful ways. 

Look for more planning and road-mapping so that people know where to contribute and how to add the most value. We're really excited about the working with our awesome community to push Foundation forward even faster (if that's possible).

We've gotten to know our Yetinauts over time and learned what their into doing. We'd also like to get to know you more , Nicolas! The [Help Wanted](https://github.com/zurb/foundation-sites/labels/help%20wanted) would be a great place to start or [answering questions on the forum](http://foundation.zurb.com/forum)

**Comment by ncoden** [comment]
Thanks @colin-marshall @rafibomb . So I'll continue to contribute when I have the time for ;)

I'm currently working on `(flex-)grid`, and the modifiers mixins you provide for your components, to make them usable in a semantic scss.

BTW, is it possible to discuss about major changes on syntax ? There is lot of modifications we could do to facilitate the Foundation use and maintenance, like `BEM`/`SMACSS` mix for naming, `layout/module/section` recommandation, `sass-lint` (npm) or `scss-lint` (gem)...

*I don't know how you work at Zurb, but I use [this](https://gist.github.com/ncoden/433349c10060173ebe51) for my [projects](https://github.com/ncoden/caliopen.web-client-ng/tree/refactor/foundation). There is still a lot work to do, but you can pick some ideas.*

Thx :)

**Comment by kball** [comment]
@ncoden major changes on syntax are probably not going to happen for v6, but if there are compelling cases for alternatives we can definitely consider them when it comes time to move towards a v7 for foundation.

That being said, I know there was a lot of thought put into the class naming conventions that exist, though I'm not the best person to talk on that subject (maybe @gakimball or @zurbrandon can chime in), perhaps you're running into some situations where there's a bug/inconsistency with the conventions that should get cleared up?

**Comment by ncoden** [comment]
:+1: I was thinking of v7 yes.

I'm not stuck with the actual convention: CSS is a hack, there is always a more or less dirty way to do something. But I think it could be better, more modular, easier to use with sass.
