### ISSUE TITLE
[Dropdown Menu] Documentation incorrect for plugin Events

### ISSUE THREAD

**Issue by dsd3v** [zurb/foundation-sites#8502]
The documentation for the Foundation 6 Dropdown Menu lists the event names in CamelCase as:
[http://foundation.zurb.com/sites/docs/dropdown-menu.html#js-events](http://foundation.zurb.com/sites/docs/dropdown-menu.html#js-events)
**show.zf.dropdownMenu**
**hide.zf.dropdownMenu**

Within the 6.2 plugin source code the event names are actually not CamelCase:
[https://github.com/zurb/foundation-sites/blob/develop/js/foundation.dropdownMenu.js](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.dropdownMenu.js)
**From line 260:**
`/**
     * Fires when the new dropdown pane is visible.
     * @event DropdownMenu#show
     */
    this.$element.trigger('show.zf.dropdownmenu', [$sub]);`
**From line 305:**
`/**
       * Fires when the open menus are closed.
       * @event DropdownMenu#hide
       */
      this.$element.trigger('hide.zf.dropdownmenu', [$toClose]);`

**What did you expect to happen?**

Per the docs, CamelCase should work:
`$('[data-dropdown-menu]').on('show.zf.dropdownMenu', function() {
                    console.log('dropdown menu shown');
                });
                $('[data-dropdown-menu]').on('hide.zf.dropdownMenu', function() {
                    console.log('dropdown menu hidden');
                });`

**What happened instead?**
The events only work without CamelCase however:
`$('[data-dropdown-menu]').on('show.zf.dropdownmenu', function() {
                    console.log('dropdown menu shown');
                });
                $('[data-dropdown-menu]').on('hide.zf.dropdownmenu', function() {
                    console.log('dropdown menu hidden');
                });`

**Comment by Owlbertz** [comment]
For the accordion menu the event is also camel cased, so I guess the code should be aligned to match the other plugins and the docs.

**Comment by briantan888** [comment]
Noticed for accordion menu, event keydown.zf.accordionmenu is not camel case but click.zf.accordionMenu is. Is there a standard that foundation is following?

**Comment by Owlbertz** [comment]
As per [this document](https://github.com/zurb/foundation-standards/blob/master/javascript.md#events) the plugin name should be camel cased I'd say, since the documentation comment should be `[pluginName]#[eventName]`. Unfortunately the code example only has `thing`, but I guess the above also applies for the event itself.

**Comment by acarnwath** [comment]
Just filed #8631 for a similar issue with Equalizer

**Comment by hulparuadrian** [comment]
This thread saved me from more hours of agony. Hope that the docs will be updated soon so others won't run into the same issue.

**Comment by pandymic** [comment]
In a similar vein, I just suffered through troubleshooting a similar issue with the "init" event that fires when the plug-in is initialized.

The `Foundation.registerPlugin` (Line 52 in foundation.core.js) fires `jQuery.trigger` (Line 62) using the hyphenated plug-in name instead of either of the cases discussed in these comments. I was expecting either "dropdownMenu" or "dropdownmenu" but found "dropdown-menu"

Not sure if this inconsistency is specific to the DropdownMenu plug-in, or is a larger overarching issue with the event namespaces in general.

**Comment by DanielRuf** [comment]
Fixed in https://github.com/zurb/foundation-docs/pull/24

Alse see https://github.com/zurb/foundation-sites/pull/10965
