### ISSUE TITLE
switch elements with optional inner labels not aligning vertically in some browsers

### ISSUE THREAD

**Issue by jeffreybasurto** [zurb/foundation-sites#8529]
I can reproduce this with iOS v8, Safari.

The issue appears to be the use of  `transform: translate(-50%);` which only works in my test when adding -webkit-transform.  

Perhaps it would be a good idea to include -webkit-transform and its cohorts to support as far back as possible without changing the implementation.

**Comment by colin-marshall** [comment]
@jeffreybasurto if you wouldn't mind, can you please share a screenshot or setup a [codepen](codepen.io) for testing? Thanks!

**Comment by Owlbertz** [comment]
According to [caniuse](http://caniuse.com/#feat=transforms2d) iOS Safari only supports transform without the vendor prefix since version 9.0. Not sure if this is a conflict between different understanding of what a version is. Autoprefixer as it is used in the Gulp SASS is configured to support the two latest versions of each browser. The question is if iOS 8 is still two versions behind the current 9.4 or not...

**Comment by JeremyEnglert** [comment]
Please supply a Codepen example and I will re-open this issue.
