### ISSUE TITLE
Rails assets pre-compilation fails when using sub-components of v6.2.0

### ISSUE THREAD

**Issue by StanBright** [zurb/foundation-sites#8546]
**How can we reproduce this bug?**

1. Rails 4.2.5.2 with enabled assets precompilation
1.1. use uglifier v3.0.0 (I tested with v2.7.2 & v2.7.1, and had the same issues)
2. config/environments/production.rb => config.assets.js_compressor = :uglifier (the default)
3. "require" any of the js components in application.js

e.g. add a require to "foundation.core.js"
`//= require bower_components/foundation-sites/js/foundation.core`

4. Try precompiling the assets:
`RAILS_ENV=production rake assets:precompile`

**What did you expect to happen?**

What one would expect to happen is the pre-compilation process to finish successfully.

**What happened instead?**

pre-compilation fails with:
"ExecJS::ProgramError: Unexpected character '`' (line: 1042, col: 29, pos: 69716)

Error
    at new JS_Parse_Error...."

**Workaround/Note**
If I use the "dist" version that includes all JS components, it works as expected and finishes successfully.

**Comment by kball** [comment]
@StanBright this is due to the fact Foundation 6.2 has moved to ES6/ES2015, and the rails asset pipeline supports it out of the box.  The recommended solution from the sprockets team is here: https://babeljs.io/docs/setup/#rails

Alternatively, check out the foundation-rails gem, where we handle bundling and integration: https://github.com/zurb/foundation-rails
