### ISSUE TITLE
Input unresponsive 

### ISSUE THREAD

**Issue by DarkGhostHunter** [zurb/foundation-sites#8548]
Inputs inside animated reveals can lock out the user from inserting data inside the `input` (text, password, etc).

**How can we reproduce this bug?**

1. Open a `.reveal`
2. Input text inside the `<input>`
3. Close the `.reveal` and open another `.reveal`
4. Repeat the process from Step 2.

Happens in: Chrome 50 (64-bit), Canary 51, Firefox 45.0.1
Does NOT happens in Edge 25.10586.0.0 / EdgeHTML 13.10586
Untested: Safari, Opera, Chrome Mobile, Safari Mobile.

**What did you expect to happen?**

Being able to insert text inside the input.

**What happened instead?**

1. Inputs get locked with no visual aid.
2. JS Console spits an error that repeates itself as many times the inputs become locked:
`foundation.js:1 Uncaught TypeError: Cannot read property 'find' of undefined`

**Test case:**

http://codepen.io/DarkGhostHunter/pen/groRrg

- jQuery 2.2.3
- Foundation 6.2.0 (JS)
- Motion UI 1.2.2
- What-input 1.1.4 (Y U NOT 2.0?)

**Comment by brettsmason** [comment]
@DarkGhostHunter This is a known bug which has been fixed in the dev branch. The 6.2.1 patch is due out this week which will fix your issue (see [8492](https://github.com/zurb/foundation-sites/issues/8492) for more details).

I'm going to close this, but if you continue to have issues after 6.2.1 comes out please reopen this!
