### ISSUE TITLE
6.2.1 - Disabled buttons has background-color on hover

### ISSUE THREAD

**Issue by Silvester20** [zurb/foundation-sites#8562]
When an button is disabled with the 'disabled' class & 'disabled' attribute present, there should not be an background-color change on hover, like it was in 6.2.0.

**Comment by colin-marshall** [comment]
The `pointer-events:  none;" declaration was removed from the `.disabled` class in `6.2.1`. That was preventing the hover events from occurring, so that's why the background shows up now.

This should be an easy fix to make the hover classes not apply to disabled buttons. I can take a look next week.
