### ISSUE TITLE
CSS in Download Everything is different from CDNJS

### ISSUE THREAD

**Issue by Opus4210** [zurb/foundation-sites#8618]
I had downloaded Foundation 6.2.1 using the Download Everything option. When I was working with a couple of the off-canvas samples, I couldn't find the menu-icon class (as mentioned in issues #8565 and #7033). So I referenced the CSS at [CDNJS](https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.1/foundation.css) and found the menu-icon class there. That prompted me to compare the two.
1. For readonly/disabled textarea and select, the cursor element is "not-allowed" in Download Everything and "default" in CDNJS
2. The menu-icon class is missing from Download Everything
3. There are 2 definitions (dupes) of .menu-item.dark in CDNJS
4. Transitions (classes slide_, hinge_, scale*, etc.) are missing from CDNJS

Maybe I'm incorrectly assuming that they should be in sync, but they're so close that it seems to me they should be.

**Comment by kball** [comment]
The build processes are slightly different, and the customizer includes the motionUI classes by default in "everything", while the CDN simply loads the compiled `.css` file from the repo which does not include motion UI by default... so that accounts for item 4.

I believe the other three differences have all been addressed, so closing this issue.
