### ISSUE TITLE
Add Foundation Flexbox stylesheet to CodePen

### ISSUE THREAD

**Issue by simonrcodrington** [zurb/foundation-sites#8620]
Hey guys.

When building pens with CodePen (http://codepen.io/). They provide the option to add quick CSS stylesheets to your pens to get you up an running. They now offer a link directly to the foundation 6.2 minified stylesheet but no option to link to the flex version.

CodePen uses the [http://www.jsdelivr.com/](http://www.jsdelivr.com/) CDN to deliver their stylesheets. From what I understand this is a free service where people can submit a stylesheet to be hosted.

I don't know if it's either you guys or CodePen who adds these files, but I'd love to be able to use the flex version of your stylesheet (with all default options etc) in my pens. 

I might also be able to add this to their CDN on your behalf (I would just download the standard options for the Foundation 6 package and upload it to them)

Let me know what you guys think

Cheers

**Comment by rafibomb** [comment]
Hi Simon,
It sounds like you are seeking a Flex version of the Foundation. It looks like CDNJS already offers this. We added it to this codepen:
http://codepen.io/rafibomb/pen/oxdRBW

Does this help? Can you suggest a some better placed to distribute this?

**Comment by colin-marshall** [comment]
@rafibomb while we're on the topic of CodePen, I have a related suggestion. There are quick-add dropdown boxes in the CSS and JS settings of a pen. There is an option to quick-add Foundation CSS, but there is no Foundation option on JS page of the settings. Since JS is required for the majority of Foundation's components, it seems awkward to not also have it as a quick-add option in the JS section. 

If we could convince CodePen to also have a Foundation (Flex) option to the CSS quick-add menu, that would be killer.

**Comment by simonrcodrington** [comment]
Hi @rafibomb thanks for that. That file was pretty much all I needed for my pens. I'll just have to manually copy this link into each of my pens. 

I'd be keen on seeing the flex-grid offered as a dropdown option on CodePen, but I guess it would be up to them as to what quick options they allow. 

Cheers

**Comment by Owlbertz** [comment]
Side node: the CodePen template Rafi mentioned is also part of the [Github issue template](https://github.com/zurb/foundation-sites/blob/develop/.github/ISSUE_TEMPLATE.md) in the repo.
I'll close this issue because information was provided.
