### ISSUE TITLE
Foundation 6 with private jQuery (RequireJS)

### ISSUE THREAD

**Issue by iFarmGolems** [zurb/foundation-sites#8622]
Hello,

I am not sure if this problem belongs here, but I am not able to get F6 working with private jQuery using RequireJS.

I've tried:

```
require(['jquery-private','foundation'],function (jQuery) {
    jQuery(document).foundation();
})
```

Inside jquery-private: 

```
define(['jquery'],function ($) {
    return $.noConflict(true);
});
```

But it fails saying that (...).foundation is not a function. When I try to `console.log(jQuery)` in require call, it looks OK as it shows jQuery object.

Anyway, is F6 AMD compatible? Because I can't see `if (define.amd ... ...)` in the code.

Thanks for the answer.

**Comment by Owlbertz** [comment]
Foundation has no explicit AMD definition, but should work with requireJS.
```js
requirejs(['jquery', 'what-input', 'foundation'], function($, whatInput, Foundation) {
  // initialize Foundation
  $(document).foundation();
});
```
This works for me, Foundation as passed from the parameter will be `undefined` but the script loading works and Foundation is initialized correctly. How is your requireJS configured?
Can you provide a link to an example?

**Comment by iFarmGolems** [comment]
Yes, your example is working perfectly fine, however what I am trying to achieve is not to have jQuery as a global variable.

When you require jquery like in your example, it registers itself as a global and you can call it either jQuery or $. When you do it like in my example [here](https://github.com/iFarmGolems/Foundation-6-private-jQuery), you can see that I am loading jQuery via loader which returns jQuery.noConflict(true).

I think the problem here lies in extending the jQuery object - since I can not reference one local jQuery to go under "jQuery" or "$", something like this:
```
        require(['jqueryloader'], function([$,jQuery]) {
            Some magic here...
        })
```
i.e. I can't put an array in the anonymous function to say that my private jQuery can be referenced either with "$" or "jQuery".

This line fails `  $.fn.foundation = foundation;` because I think you are extending the "jQuery" object somewhere in the code, which in my case, can **not** be referenced via name "jQuery" but the symbol "$" instead.

**Comment by Owlbertz** [comment]
I will pull this down in the next days and see if I find a way to get this working.

**Comment by Owlbertz** [comment]
So here's what I found out. I guess the issue you encounter happens because when Foundation is loaded, the components are initialized via the `!function($){}(jQuery)` wrapper, but since jQuery is not there yet it fails to load.
An easy way to get around is is to wrap the whole Foundation JavaScript into one big AMD wrapper, which takes care of defining jQuery itself, so I you would notneed your `jqueryloader` here.
This works for me and does not expose jQuery globally. However, getting this done for the public versions would require adjusting the whole structure of Foundation. If this is a thing then I might have a look what will be the best way to achieve that. In the mean time you might need to adjust your files locally.

**Comment by iFarmGolems** [comment]
I understand. Thank you for your response and effort!
