### ISSUE TITLE
Cmd + combo won't work on my page all of the sudden

### ISSUE THREAD

**Issue by andrewjschmitt** [zurb/foundation-sites#8733]
**How can we reproduce this bug?**
1. I have
2. No Clue
3. Or I Would Have
4. Troubleshot it
5. Already
6. Myself

**What did you expect to happen?** && **What happened instead?**

I've created an app with Django. So a lot of my pages load off the same template save a few customizations to a few pages. The cmd (or ctrl for windows) + combination keys, such as cmd+r to reload, all of the sudden one day just stopped working on one of the pages. It's virtually no different than any of the other pages. The layout is a little different, but has the same libraries and code essentially. Every time I hit "cmd" the console logs "Component not defined!" from foundation.min.js (I'm using the most recent version). 

I can't seem to replicate it anywhere. Its clearly something stupid going on. But it's literally been months and I haven't been able to figure it out. I figured I'd ask the group and see if anyone can point me in the right direction to finding the solution. 

Help me. 

Please.

**Comment by Deckluhm** [comment]
You should try to reproduce your issue using CodePen (or any similar service) because it often helps you to identify what is causing the issue.

In your case, it can show you that this is (or not) Django related. Or maybe you have an event handler that changes the behavior of some keys?

Last thing: is there any preprocessing on your assets, especially javascript files?

**Comment by andrewjschmitt** [comment]
So actually if I hit any key at all on the keyboard it throws "Component not defined!". What throws that error? And why would it be throwing it?

**Comment by Owlbertz** [comment]
This issue occurs if you are using the Keyboard util in a component that is not correctly defined. Somehow the keys you press end up being processed by an event handler that leads to said message and will prevent the default action. If you can provide a link to your page I will have a look and sort that out.

**Comment by andrewjschmitt** [comment]
@Owlbertz Thank you! I suspected that. The thing is I didn't include that plugin explicitly. So either it's being included by default or by accident I don't know. All I have done is initialize foundation `$(document).foundation();` and referenced the minified library. If you know of a way for me to effectively disable keyboard util I'm all ears.

**Comment by Owlbertz** [comment]
The Keyboard Util is required by many plugins because it adds necessary accessibility support by handling keyboard inputs (e.g. using arrow keys to navigate through menus). I highly recommend you to  use this library - not only because there is no way to easily disable its usage, but also because you would lose one of the reasons why this framework is so good (the accessibility that it provides).

As this is part of almost every Foundation installation (besides the people that only have like the CSS features defined in their custom download) I wonder what causes this issue for you. I feel like the easiest way is if I have a look at your code/page so I can check that. If that is not possible for some reasons we'll think of something different.

**Comment by IamManchanda** [comment]
@andrewjschmitt we are awaiting your reply if you want this thread to be reopened
Does this issue still exists??

Also would be great if you can help us with a codepen!
