### ISSUE TITLE
[Sticky] Plugin does not work correctly when initialized in JS

### ISSUE THREAD

**Issue by maggo** [zurb/foundation-sites#8782]
**How can we reproduce this bug?**
1. Create markup for sticky element
2. Initialize with `new Foundation.Sticky($element, options);`

**What did you expect to happen?**

Stickyness like when initialized by `$(document).foundation();`

**What happened instead?**

Classes and attributes get added but element doesn't stick at scroll

**Test case:**

https://jsfiddle.net/9L4bk6Le/

**Comment by denisahac** [comment]
Using `$(document).foundation();` alone doesn't get the desired results unless you properly specify the required data attributes. 

I think `$(document).foundation();` is required before using `Foundation.Sticky(elem, options);` since the Sticky plugin has this option `data-sticky-on` which requires MediaQuery plugin which in turn extracts `$('foundation-mq').css('font-family');` values and does require `$(document).foundation();` to generate element that holds the media query breakpoints declared in _settings.scss.

I had a couple of projects and used ZF6, some of the JS plugin don't properly work without calling the `$(document).foundation();` first.

Tried the following code and it worked perfectly by just using `$(document).foundation();` alone.

```js
$(document).foundation();

var sticky = new Foundation.Sticky($('.sticky'), {
	marginTop: 0,
	anchor: 'sticky-anchor'
});
```

**Comment by JeremyEnglert** [comment]
I agree with the above fix. If this still does not work for you, let me know and I'll reopen the ticket.
