### ISSUE TITLE
label cursor: pointer

### ISSUE THREAD

**Issue by umphy** [zurb/foundation-sites#8813]
**How can we reproduce this bug?**
1. Surround an `<input type="checkbox"/>` in a `<label>`

**What did you expect to happen?**

I expect when mouse hover over label text, the cursor will change to a pointer.

**What happened instead?**

The cursor did not change to a pointer.

**Test case:**

https://jsfiddle.net/mggnfpao/

**Comment by denisahac** [comment]
The problem with the later part when we implement the `cursor: pointer` is that the checkbox/radio is affected by the style. The default implementation is to only change the cursor of the label when the checkbox/radio is a sibling of the element.

How about we change the implementation a bit, instead of label we'll do custom cursor on the label and checkbox/radio input. What do you think?

**Comment by umphy** [comment]
Sure, I don't have any preference on how it's implemented as long as the behaviour is what's expected :)

**Comment by andycochran** [comment]
We should note that the default browser behavior for a checkbox on hover is the default cursor, and the checkbox itself provides a click target. 

Also, checkboxes need to work in groups, on the same line. When you wrap a label around a checkbox, the label becomes block-level. This allows you to click anywhere on its line—which is worse than not getting `cursor:pointer`. 

So, I'm not sure we need to support wrapping labels around checkboxes. It's easy enough to fix with app-specific styles.

**Comment by kball** [comment]
Based on the above conversation, and the fact we're intending to go LESS into styling elements and more into keeping styles in classes, this seems like this is WONTFIX
