### ISSUE TITLE
Wacky font-family spec'd

### ISSUE THREAD

**Issue by dlewand691** [zurb/foundation-sites#8815]
Discovered this when using cssstats.com.

`.foundation-mq {
  font-family: "small=0em&medium=40em&large=64em&xlarge=75em&xxlarge=90em"; }`

Being used in these files:

- bower_components/foundation-sites/dist/foundation-rtl.css
- bower_components/foundation-sites/dist/foundation-flex.css
- bower_components/foundation-sites/dist/foundation.css

Should be set to what?

**Comment by denisahac** [comment]
Some of the Foundation javascript components rely on media query and since the custom media queries are generated using SASS it needs a way for the javascript to read the user defined MQ.

When you call the `$(document).foundation();` one of its objectives is to create a custom element with a class of `.foundation-mq` it then reads by `foundation.util.MediaQuery.js` to extract the breakpoints.

See line number 30 of [MediaQuery](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.util.mediaQuery.js)

**Comment by brettsmason** [comment]
As @denisahac kindly pointed out, this is created by the 'foundation.util.MediaQuery.js' and is used to list the breakpoints. Closing this as its been answered, but feel free to re-open if you have other issues.

**Comment by dlewand691** [comment]
Ah, thanks for the clarification, I'll ignore.

**Comment by djmtype** [comment]
It might be relevant to point this out in the documentation for those of us who don't include the entire Foundation library. 

I was including responsive accordion tabs component and couldn't figure out why it wasn't functioning after including the relevant Sass and js files. 

This hack found in the global styles is absolutely necessary for it to work: 

```
.foundation-mq {
  font-family: "small=0em&medium=40em&large=64em&xlarge=75em&xxlarge=90em"
}
```

**Comment by DanielRuf** [comment]
Well, the JS and Scss is definitely needed which should be clear. And the mediaquery helper / component s also needed for most components.
