### ISSUE TITLE
dropdownMenu.js forceFollow docs incorrect & code not working

### ISSUE THREAD

**Issue by micschk** [zurb/foundation-sites#8843]
The forceFollow option in foundation.dropdownMenu.js allows forcing links to be followed on touch devices (instead of opening their dropdown and being followed on second click).

The docs say it is FALSE by default, while it actually is TRUE by default (it's just not working).

forceFollow is never considered in the JS code because it is only checked on second click (after the first 'hasClicked'), around line 147;

``` js
if(hasSub){
          if(hasClicked){
            if(!_this.options.closeOnClick || (!_this.options.clickOpen && !hasTouch) || (_this.options.forceFollow && hasTouch)){ return; }
            else{
              e.stopImmediatePropagation();
              e.preventDefault();
              _this._hide($elem);
            }
         ...
```

Should be:

``` js
if(hasSub){
          if(hasClicked || _this.options.forceFollow){
            if(!_this.options.closeOnClick || (!_this.options.clickOpen && !hasTouch) || (_this.options.forceFollow && hasTouch)){ return; }
            else{
              e.stopImmediatePropagation();
              e.preventDefault();
              _this._hide($elem);
            }
         ...
```

**Comment by ncoden** [comment]
Hi @micschk, sorry for the (very) late reply.

> The docs say it is FALSE by default, while it actually is TRUE by default (it's just not working).

This issue has been reported several time since. There is a discussion open at https://github.com/zurb/foundation-sites/issues/9464, we are working on it.

> forceFollow is never considered in the JS code because it is only checked on second click (after the first 'hasClicked'), around line 147;

This is the normal behavior: the link is forced to be followed on the second click on touch devices. See the documentation of the `forceFollow` options:
```js
  /**
   * Boolean to force overide the clicking of links to perform default action, on second touch event for mobile.
   * @option
   * @example false
   */
  forceFollow: true
```
[js/foundation.dropdownMenu.js:421](https://github.com/ncoden/foundation-sites/blob/5573453df250bdf0ce1dec239675cc0375e3e152/js/foundation.dropdownMenu.js#L421)

Can I close this issue and mark it as duplicate ?
