### ISSUE TITLE
[Typography Helpers] Small-text center doesn't work with other classes

### ISSUE THREAD

**Issue by arnotypografics** [zurb/foundation-sites#8876]
**How can we reproduce this bug?**

1. I made a div with class row.
2. Two divs are inside one large-3 and one large-9
3. I gave them the classes medium-text-center and small-text-center

**What did you expect to happen?**

On a large screen the texts should be aligned left.
On a medium screen it should be aligned center, and it does that successfully.
On a SMALL screen it should be aligned centered aswell but instead it aligns left just like large, however i did not specify a large align with a class so that would inherit the default left align style.

**What happened instead?**

It is centered left but it has the class small-text-center

**Test case:**

http://codepen.io/anon/pen/mEyMMj

**Comment by Deckluhm** [comment]
Because Foundation is *mobile-first*, there is no class `small-text-center`.
Just use the `text-center` class (and if you need specific behavior for medium / large screens, use `medium-text-center` / `large-text-center`).

You can see here how these classes are generated: https://github.com/zurb/foundation-sites/blob/develop/scss/typography/_alignment.scss

`$-zf-zero-breakpoint` variable being equal to `small` by default: https://github.com/zurb/foundation-sites/blob/master/scss/util/_breakpoint.scss#L21

The documentation should probably be clearer on that point.

**Comment by rafibomb** [comment]
@Deckluhm Good answer!
@arnotypografics 
You can use `.large-text-left` or `.large-text-right` to override the CSS.
