### ISSUE TITLE
Magellan doesn't work as expected when the links are not in the same order as the targets

### ISSUE THREAD

**Issue by mark-tan** [zurb/foundation-sites#8960]
### Steps to reproduce:

1. Make a page with several sections, each with `id` and `data-magellan-target` specified.
2. Make a nav element with `data-magellan` containing `<a>` links to the `id`s, but don't put them in the same order as the sections
3. Scroll

### Expectation:

The correct link should get the `active` class.

### Reality:

The link corresponding to the order of the sections got the `active` class instead.

**Comment by andycochran** [comment]
Yup. http://codepen.io/andycochran/pen/VjbJKk 😞

**Comment by GustavSt** [comment]
I have the same issue but another scenario. If I have four links and for reasons the third link does not have corresponding id in the page. 
When scrolling down to the forth section the third link is the one getting active anyway.
My issue would be fixed if this issue was fixed I think. My work around was listening to the 'update.zf.magellan' event and manually add and remove the active class as I know when I want what link to be active

**Comment by andycochran** [comment]
@colin-marshall do you have any thoughts on this one?

**Comment by andycochran** [comment]
@GustavSt I've updated my Codepen to also demonstrate your scenario.

**Comment by mark-tan** [comment]
Having two nav links to the same target doesnt work as expected either. Id like for both links to get the active class.

**Comment by mark-tan** [comment]
@andycochran @GustavSt 
Hi guys. Made a PR for this case. https://github.com/zurb/foundation-sites/pull/9066
