### ISSUE TITLE
onClick functions not calling within Reveal

### ISSUE THREAD

**Issue by SylarRuby** [zurb/foundation-sites#8965]
Rails 5 w/React
Foundation 6.2.3.0

When I open up a modal, I have a button that calls another function. It's not working. Calling the function outside the modal works. Is there an attribute to add on the modal?

```

sayHi: function() {
 console.log("Hi");
}

_loop: function() {
 var foo = this.props.bar.map( function(a,b){
  return(
   <button className="small button success" data-open="exampleModal1">Open</button>
   <div className="reveal" id="exampleModal1" data-reveal="">
  <h3>Are you sure</h3>
  <p>This action cannot be undone and it's final!</p>
  <button className="close-button" data-close="" aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
  <div className="f__right flex">
    <button className="small button success" onClick={this._sayHi}>Hi</button>
    <button className="small button alert" data-close="">Close</button>
  </div>
</div>
  )
 }.bind(this));
  return(<div>{foo}</div>)
},

render: function() {
 return(<div>{this._loop()}</div>)
}

```

**Comment by kball** [comment]
I suspect the problem here is that the reveal plugin actually removes the modal from the dom and repopulates it in another place, which probably messes up React, which expects to be the only thing manipulating the DOM.  The best solution is probably to use the React port: https://github.com/aruberto/react-foundation-components
