### ISSUE TITLE
Buggy keyboard behavior on drilldown menu.

### ISSUE THREAD

**Issue by sassanh** [zurb/foundation-sites#8978]
First of all thanks for your efforts for providing this great library. I like many others appreciate it. Here's the description of a bug I found:
1. Go to http://foundation.zurb.com/sites/docs/drilldown-menu.html in Chrome 51 or Safari 9.1 or Firefox 46.0.1 or Firefox 47 (actually I guess browser version or kind doesn't matter)
2. Click on "Item1" in the sapmle
3. Click on "Item 1A"
4. Click on "Back"
5. Press down arrow key on your keyboard
6. Whoops, suddenly you're back into "Item 1A" (Bug 1)
7. Press Up
8. press Enter
9. Whoops, it animates like it's going back to the parent menu, but it doesn't (Bug 2)
10. Try to go back with clicking on Back item.
11. Whoops you can't. (Bug 3)
12. Keep Enter pressed for 5 sec on Back item.
13. OK enough, seems like keyboard navigation is not production ready on drilldown menu at all.

**What did you expect to happen?**
It to work.

**What happened instead?**
It didn't work.

**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.

No need for CodePen or JSFiddle, http://foundation.zurb.com/sites/docs/drilldown-menu.html is enough.

OK, actually I don't need this keyboard navigation on my drilldown menu at all. All I need is to be able to disable it (it being keyboard navigation on drilldown menu) so that I can deploy my code on the server without worrying about users who try to navigate it with keyboard.
It'd be great if I could remove the outlines it renders on items (trying to show which item is selected by keyboard, but just trying). It'd be great if I could disable fancy features and have a simple working drilldown menu.

**Comment by Owlbertz** [comment]
Hi,
you're right, the keyboard navigation for Drilldown seems to be broken (again). This seems to be one of the most broken feature during releases... It seems like this happened from [6.2.1](http://codepen.io/anon/pen/dXRNYL) to [6.2.2](http://codepen.io/anon/pen/YWQNxz).

If you don't care about modifying the Foundation files, you can remove the event listener in the module.

**Comment by sassanh** [comment]
@Owlbertz thanks for info, I do care about modifying Foundation files, is it alright in 6.2.1? I can downgrade.

**Comment by Owlbertz** [comment]
You can check out the first link in my post which leads you to a pen in 6.2.1. Keyboard navigation works there for me. Just check it out and see if downgrading is sufficient for you, but be aware that there obviously may be other issues in previous versions.

You could also remove the event listener in your custom code (e.g. where you initialize Foundation JS) using ```$('[data-drilldown] *').off('keydown.zf.drilldown');```. Kind of a sloppy workaround, but it should disable the keyboard interaction for all Drilldown elements on you site. Of course you can adjust the jQuery selector as you need it. Please note that you need to select the menu items instead of just the menu itself, because that's where the event listener is applied to.
Also keep in mind that you should re-enable keyboard navigation once this has been fixed as this is crucial for your websites accessibility.

**Comment by sassanh** [comment]
@Owlbertz thanks for detailed information. Unfortunately I decided not to use foundation for this particular project (not only because of this issue, it's a conclusion based on several reasons). Foundation is great toolkit for lots of use cases but I think in order to make it a stable general solution maybe you should improve your development procedure a little bit by writing massive tests, marking features that are covered by tests in documents so that users can find out easily which feature is robust and stable and encouraging developers to write tests so that over time Foundation gets even more helpful to developers than what it already is.

**Comment by sassanh** [comment]
@Owlbertz btw, it seems to be broken even in 6.2.1, it's broken in the Codepen sample you provided.

**Comment by kball** [comment]
I believe this was fixed in #9002
