### ISSUE TITLE
[Button] v5 'expand' no longer supported, add backwards-compatible 'expand' to the new 'expanded' style rules

### ISSUE THREAD

**Issue by adambundy** [zurb/foundation-sites#9010]
Is there a reason not to do this? Would be great if either worked, at least for a bit until deprecation.

**Comment by Deckluhm** [comment]
As described in the [_Semantic Versioning_ specification](http://semver.org/):
> Given a version number MAJOR.MINOR.PATCH, increment the:
>
> **1. MAJOR version when you make incompatible API changes,**
> 2. MINOR version when you add functionality in a backwards-compatible manner, and
> 3. PATCH version when you make backwards-compatible bug fixes.

Foundation `v6` is definitely a MAJOR version since a lot of stuff has been rewritten and many things are "incompatible API changes".

Reintroducing the `.expanded` class would mean reintroducing lot of `v5` classes for backward-compatibility sake — and I don't think it's a good thing.

MAJOR versions always break stuff but it's a necessary to keep projects moving on.

**Comment by andycochran** [comment]
@Deckluhm is right. Many v6 classes were changed for semantics sake. 

If you need to keep using `.expand`, you can add this to your app: 

```scss
.expand {
    @extend .expanded;
}
```

I'm gonna close this one.
