### ISSUE TITLE
Abide always considers radio buttons to be invalid when value is empty

### ISSUE THREAD

**Issue by aexmachina** [zurb/foundation-sites#9162]
The Abide#requireCheck() method contains a case for `checkbox`, but not for `radio`. It looks to me that `case 'radio'` should be added as follows:

```js
    switch ($el[0].type) {
      case 'checkbox':
      case 'radio':
        isGood = $el[0].checked;
        break;
```

**Comment by kball** [comment]
radio buttons are funky due to the fact that required is on the radio button set, rather than the radio button, and thus they are handled separately in validateRadio.  It is entirely possible there is still a bug; can you include a testcase/reproduction of bug, perhaps in a codepen?

You can use this as a base:
- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)

**Comment by aexmachina** [comment]
Okay that is strange, when I reproduce it in the CodePen it works fine.
