### ISSUE TITLE
drilldown with dropdown has white space if load on small screen

### ISSUE THREAD

**Issue by AlexAlexandru** [zurb/foundation-sites#9189]
So I want to have dropdown for medium and bigger devices and drilldown for small devices.
**How can we reproduce this bug?**

1. Load the codepen on an window that is <600 px ( first resize your window to < 600px and then load the codepen)
2. The responsive menu has a lot of white space for unkown reason

**What did you expect to happen?**
Normal menu to appear.
**What happened instead?**
White space showed.

- [CodePen with the issue](https://codepen.io/anon/pen/BzEjov)

**Comment by brettsmason** [comment]
@AlexAlexandru This problem is because you have added the `is-dropdown-submenu-parent` classes directly to the menu. If you remove these the menu works just fine - [https://codepen.io/brettsmason/pen/wzqrYv](see here). Those classes are added dynamically by the JavaScript so you don't need to manually add them.

I'm going to close this, but any further problems please let us know.
