### ISSUE TITLE
Sticky not working! (F5)

### ISSUE THREAD

**Issue by jdfweb** [zurb/foundation-sites#9236]
**How can we reproduce this bug?**

1. Step one
View my website: https://goo.gl/usRvGL
2. Step two
Inspect the navigation
3. Step three
See why the sticky is not working!

**What did you expect to happen?**

I expected when the user scroll down the page, the main navigation sticks to the top of the browser.

**What happened instead?**

It doesn't!

--

Hey all,

So I've applied a sticky to the navigation bar on my site here: https://goo.gl/usRvGL

I wrapped my main navigation (logo / menu items) in a div class labelled, "sticky" - just as the F5 docs say! However, the nav certainly doesn't stick as I scroll down.

Just an FYI - when I apply the "fixed" class, that function does work! So the JS is loading. Although fixing the bar immediately is not what I want for that main navigation, as it blocks out the top bar information.

Anyone have any ideas as to why it's not working? It's probably something small!

Cheers,
JD

**Comment by jdfweb** [comment]
Anyone?

**Comment by rafibomb** [comment]
The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by jdfweb** [comment]
I've posted there on this exact issue - http://foundation.zurb.com/forum/posts/48038-sticky-not-working-f5 - and the help has been lacklustre at best. That's why I came here.

@rafibomb - I've seen you give help to people numerous times. Valuable help, in-fact. Unfortunately, instead of a solution, you closed my issue when I actually needed help.

Back to Bootstrap, I guess.
