### ISSUE TITLE
$-zf-zero-breakpoint error message

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#9268]
A zero breakpoint is required as the first key/value of the `$breakpoints` map. But [the error](https://github.com/zurb/foundation-sites/blob/12317b1854283b3a2708d586f1141d523684f8cd/scss/util/_breakpoint.scss#L24) is misleading. 

This:

``` scss
@error 'Your smallest breakpoint (defined in $breakpoints) must be set to "0".';
```

Should probably be:

``` scss
@error 'The first key in the $breakpoints map must have a value of "0".';
```

And a note should also be added to [the docs page](http://foundation.zurb.com/sites/docs/media-queries.html#changing-the-breakpoints).

**Comment by colin-marshall** [comment]
@andycochran would you care to resolve this one if you have time? Thanks!

**Comment by ncoden** [comment]
hmmm... We often assume in the code that a breakpoint is always greater than the previous one in the `$breakpoints` map. This should be made more clear in the documenation.

Sadly, we cannot customize the `settings.scss` file since it is generated. This is not the first time I run into this issue, we should be able to add some intos in the settings file. Should be begin to update `settings.scss` manually ?

**Comment by soleshoe** [comment]
Error is really weird because the smallest $breakpoints value is indeed 0.

I just commented out the test in "/util/_breakpoint.scss" and set the value as expected :

`// @if nth(map-values($breakpoints), 1) != 0 {
//   @error 'Your smallest breakpoint (defined in $breakpoints) must be set to "0".';
// }
// @else {
//   $-zf-zero-breakpoint: nth(map-keys($breakpoints), 1);
// }

$-zf-zero-breakpoint: nth(map-keys($breakpoints), 1);` <- expected value

**Comment by ncoden** [comment]
@soleshoe Do you mean that you have a `$breakpoints` map defined with the first value as `0` and you still have this error message ?

**Comment by soleshoe** [comment]
Yes it looks like (the map is defined just above and the first element "small" value is indeed '0')

**Comment by ncoden** [comment]
@soleshoe Thanks. This issue is more about the message itself. Could you open a new issue, with your configuration and a test case ?

**Comment by kagarmoe** [comment]
I just ran into this error, as well. I have a `$breakpoints` map defined with the first value as 0 and I still tet this error message.

**Comment by DanielRuf** [comment]
Hi @kagarmoe,

Can you open a new issue with all relevant details so we can check this and if it was part of the last releases? This would be great.

**Comment by tomer494** [comment]
Hi all,

I found the solution to this issue that works for me. I hope it can help solve the issue.
in \src\styles\foundation\settings.scss
Change 
$breakpoints: (
    small:      0px,
To
$breakpoints: (
    small:      0,
![image](https://user-images.githubusercontent.com/62674387/93014049-65dc2280-f5b6-11ea-8148-5c03063fc028.png)

**Comment by DanielRuf** [comment]
Correct, see https://github.com/foundation/foundation-sites/blob/v6.6.3/scss/settings/_settings.scss#L109
