### ISSUE TITLE
Alignment issue with top-bar-title

### ISSUE THREAD

**Issue by pmyjavec** [zurb/foundation-sites#9284]
Hey,

I've just started with a fresh installation and tried to build a top bar using [this official guide](http://foundation.zurb.com/sites/docs/top-bar.html). Unfortunately I ended up with a poorly aligned `top-bar-title` and `top-bar-right`. Here is an example:

![screen shot 2016-10-22 at 12 58 25 pm](https://cloud.githubusercontent.com/assets/315096/19617023/4ec8d9a0-9857-11e6-883f-ffc574ea39d3.png)

Here is the code which can be used to re-create the issue:

```
<div class="top-bar">
  <div class="top-bar-title">
    <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
        <button class="menu-icon dark" type="button" data-toggle></button>
    </span>
    <strong>Bali Compost Crafters</strong>
  </div>
  <div id="responsive-menu">
    <div class="top-bar-right">
      <ul class="menu">
            <li><a class="page-link" href="/">Contact Us</a></li>
      </ul>
    </div>
   </div>
</div>
```

In order correct the alignment I simply had to add the following to my CSS, which I got from [posts](http://stackoverflow.com/questions/35388106/top-bar-not-aligning-in-foundation-6) where others seem to be experiencing the same behavior. 

```
.top-bar-title {
    float: left;
    margin-right: 1rem;
    margin-top: 0.5rem;
}
```

Let me know if I can be of anymore assistance and hope this information helps!

Thanks.

**Comment by brettsmason** [comment]
@pmyjavec There is actually an issue open here: https://github.com/zurb/foundation-sites/issues/9029 along with a PR currently open to address this here: https://github.com/zurb/foundation-sites/pull/9039

The issue comes from the docs having additional styling that isn't contained within Foundation.

I'm going to close this as its a duplicate issue - but this should hopefully be in the next release (6.3). Thanks for the report!
