### ISSUE TITLE
[Flex Grid] $width variable in the method signature of the flex-grid-row() mixin is incorrect

### ISSUE THREAD

**Issue by aflashyrhetoric** [zurb/foundation-sites#9496]
The method signature for the flex-grid-row() method ([link here](http://foundation.zurb.com/sites/docs/flex-grid.html#flex-grid-row)) is: 
```
@include flex-grid-row($behavior, $width, $columns, $base, $gutter) { }
```
However, after pulling in `foundation-sites` from npm (via `yarn`, like so: `yarn add foundation-sites`), I found that the variable is not named `$width` but rather, `$size`. Passing in a $width variable yielded an error mentioning that "no such variable $width exists."

**Comment by ncoden** [comment]
Hi @aflashyrhetoric,

The name of the variable has been updated at #8570, and it a part of the `v6.3.0` release. When you installed `foundation-sites` from npm, you probably installed a release candidate (`v6.3.0-``rc1`/`rc2`/`rc3`) while the documentation was still for `v6.2.4`.

@kball: It is not the issue here, but it make me think it could be useful to provide a documentation for _several_ versions ?

**Comment by aflashyrhetoric** [comment]
Ahhhh, I see. Thank you for the clarification! I like the way that [Laravel](https://laravel.com/docs/5.3) does it, with a little dropdown in the top right.

**Comment by ncoden** [comment]
It is automatically generated with SassDoc (inside SuperCollider) from the comments above our Sass mixins and functions. For example for `$size`, see https://github.com/ncoden/foundation-sites/blob/ea91b2a4a1a8f2fdfea9c55995cce00c686eadf8/scss/grid/_flex-grid.scss#L13

**Comment by kball** [comment]
@ncoden definitely worth considering, though the logistics are somewhat tricky.
