### ISSUE TITLE
Version 6.3.0 Breaking Builds

### ISSUE THREAD

**Issue by andrewjmead** [zurb/foundation-sites#9507]
I noticed that version 6.3.0 no longer has the dist files in the `dist/` directory. These files are now in `dist/js/` and `dist/css/`. This change is breaking webpack builds.

I'm not sure if foundation uses [semver](http://semver.org/), but I was surprised to see a backwards-incompatible change on a minor release. Was this intentional? Thanks!

**Comment by ncoden** [comment]
It was intentional, see the [6.3.0 chanlog](https://github.com/zurb/foundation-sites/releases/tag/v6.3.0).

I agree that is we follow semver scrupulously, we should call this version `7.0`. But we make _little breaking changes_ very often and so the version number would not be very useful to understand the amount of changes between two versions.

Like someone said [here](https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e), Semver is good for machines, for but for humans. We consider this is a _little change_ because it can be fixed _very easily_, and thus we include it into a minor release.

**Comment by andrewjmead** [comment]
Thanks for the response @ncoden. I had just tracked down the change here https://github.com/zurb/foundation-sites/pull/9078.

I only opened an issue because I teach web development and this broke some student projects. I'm fine with the change, I just wanted to make sure it was intentional and wouldn't get rolled back in a few days.

**Comment by Spankyed** [comment]
He really does care ;()
