### ISSUE TITLE
Pre tag overflows the width of the container

### ISSUE THREAD

**Issue by BicanMarianValeriu** [zurb/foundation-sites#9565]
**How can we reproduce this bug?**

Write a long piece of css code for example.
Put that on a column div.
The pre tag will overflow the width of the column container

**What did you expect to happen?**
I expect to see a X axis scrolling bar.

**What happened instead?**
Text overflows the container width.

**Test case:**
pre {overflow-x:auto} will fix that.

**Comment by ncoden** [comment]
Hi @BicanMarianValeriu

I confirm this is is an unexpected behavior. I'll open a PR and add `pre {overflow-x:auto}` to our global styles, because of I think there is no case where we would expect the `pre` content to overflow.

I made a codepen to verify the bug. Next time, please provide one. It really help us. https://codepen.io/ncoden/pen/ENzmwZ
