### ISSUE TITLE
Inline labels with form validation.

### ISSUE THREAD

**Issue by abram27** [zurb/foundation-sites#9600]
Abide validation doesn't work with foundation inline labels.  Not sure if can add both, Ideally I would like to move the form-error span beneath the input group under the same label tag (currently abide only activates **siblings** that have class form-error).

```html
<label>
    Amount
    <div class="input-group">
        <span class="input-group-label">$</span>
        <input data-bind="value: total, attr: {required: validate}" class="input-group-field" type="number" min="0.01" step="0.01" />
        <span class="form-error">Amount is required.</span>
    </div>
</label>
```

Expected behavior is to keep same formatting of input-group when validation classes are added.

**Comment by ncoden** [comment]
Hi @abram27.

I edited you post to show HTML correctly. Please use three "`" to create code blocks.
I did not totally understood your issue so I created a CodePen. Please provide one the next time, it helps us a lot !

https://codepen.io/ncoden/pen/EZaVga

---

The problem is at [js/foundation.abide.js:123](https://github.com/ncoden/foundation-sites/blob/5b572ab0a5ca665cf5ba235e5f77d3451db07a8f/js/foundation.abide.js#L123). Like you said, _abide only activates siblings that have class form-error_. I agree this is problematic and we should allow to explicitly declare relations between Form Errors and Inputs, and more generally relations between every component.

To resolve this issue, I would tend to add an attribute like `[data-form-input]` / `[data-input]` / `[data-form-for]`, which would work like `label[for]` to declare the input a Form Error is related to, everywhere on the page or with any class. @kball What do you think ?

Also, I do not like the way we are currently finding form errors, automatically and by their classes. But it require more discussions about how we handle interactions between element and components, so I'll keep this for later.

**Comment by ncoden** [comment]
Also, I wonder which tag I should add to this issue. Is it a `bug` ? A `feature request` ? Or something else ? The documentation does not explicitly precise that only siblings Form Errors are showed. Should we expect that all Form Errors within `label` are concerned ?

**Comment by kball** [comment]
I agree with @ncoden that we should allow explicit labeling via data attributes, and we should use data attributes for finding, not classes. The one other question I have is... is there a simple "base case" that auto-finds the error, e.g. within a label?

**Comment by ncoden** [comment]
> is there a simple "base case" that auto-finds the error, e.g. within a label?

I am not sure to understand. Do you ask if this is something we should support, automatically finding the Error Inputs within the label ?

**Comment by abram27** [comment]
I guess it would be considered a new feature even though the current example doesn't work.  I would be fine with some way to relate an error message to the input and keep the current implementation as a fall back.  I don't think users would necessarily want to have to explicitly define the relation for every error message to the input.  Thanks for the pointer on how to format the html, I don't post on github issues a lot.

**Comment by ncoden** [comment]
@abram27 We do not plan to remove the current "auto label finding" behavior, well not for now. Just to add a way to explicitly declare this relation, and maybe expand the search range to the whole `label` content.
