### ISSUE TITLE
Responsive Navigation with Dropdown/Drilldown on small screens (broke in update from F6.2 to F6.3)

### ISSUE THREAD

**Issue by 30bySixty** [zurb/foundation-sites#9724]
#### How to reproduce this bug:
Follow documentation to build a responsive dropdown/drilldown menu. 

#### What should happen:
On small screens, the `.is-drilldown li /a` components should be rendered per the `display: block` attribute (e.g. each menu item should be on a separate line).

#### What happened instead:
Each menu item shows up in the same line.

#### Test case:
https://codepen.io/30bySixty/pen/WRdxbV

#### Additional information:
The above seems to be somewhat resolved when removing the following attributes from the .menu component:

    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;

**Comment by IamManchanda** [comment]
Can you explain in brief the issue ?
Here is the updated codpen ( 6.2.x release ) => https://codepen.io/IamManchanda/pen/apEJpQ
so that you can tell me what difference/issue you are facing

**Comment by kball** [comment]
Broadly I think the issue here is that `.drilldown` and `.horizontal` are colliding and causing problems... you can resolve this here by changing your menu class to from `.horizontal` to `vertical.medium-horizontal`

in 6.4 with the menu rework from https://github.com/zurb/foundation-sites/pull/9670 you would be able to just remove `.horizontal` completely and it would "just work" defaulting to vertical for drilldown and horizontal for dropdown
