### ISSUE TITLE
[Slider] Vertical Slider Input Issue

### ISSUE THREAD

**Issue by steadynow** [zurb/foundation-sites#9733]
the 'data-start' value above zero on the vertical slider breaks the draggable & click select features on the slide bar, adding a negative % value to the slider handle. 
Changing the value of the slider via the input works correctly.

#### How to reproduce this bug:
1. Step one
Click or drag on the vertical slider

#### What should happen:
red slider-handle span should move to that position & update the input box on right.

#### What happened instead:
input value updated correctly, but position of span is negative

#### Test case:

[https://codepen.io/steadynow/pen/bgLbyQ](https://codepen.io/steadynow/pen/bgLbyQ)

- [CodePen with Foundation 6.3.0 and MotionUI]

**Comment by IamManchanda** [comment]
As this is related to JS [ `data-options` ] , 
@kball ..... Kevin sir can you look into this?

**Comment by DanielRuf** [comment]
New codepen: https://codepen.io/DanielRuf/pen/KKPWqWa?editors=1100

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/commit/685d85787cc3db2d13a96d9602532b5ddf80a2ef

`data-invert-vertical` and `noInvert` are also not used anymore.

This issue is fixed by https://github.com/zurb/foundation-sites/commit/685d85787cc3db2d13a96d9602532b5ddf80a2ef#diff-ec33ab57e14cd68eaa29c1e08dcc7a3e

See https://codepen.io/DanielRuf/pen/VwZpWWR
