### ISSUE TITLE
Positioning of dropdown is not correct when two buttons open the same dropdown

### ISSUE THREAD

**Issue by hfinnlz** [zurb/foundation-sites#9766]
#### How to reproduce this bug:

1. Create two buttons that both point to the same dropdown code using example markup on http://foundation.zurb.com/sites/docs/dropdown.html
2. Click your first button
3. Click your second button

#### What should happen:
The dropdown pane should appear in the right place depending on which button was clicked. This is the expected behavior based on previous versions of Foundation.

#### What happened instead:
The dropdown only appears next to the first button, regardless of which button has been pressed

#### Test case:
https://codepen.io/anon/pen/ygQoVj

**Comment by IamManchanda** [comment]
@hfinnlz Hmmmn..... Intresting
But i would argue that this is meant to be like this => https://codepen.io/IamManchanda/pen/Grwvyr

I dont think that current code allows you to what you would like to have ..... But i also agree that there should be some way to open same content div in multiple dropdown's 

@kball ..... on taking decision on this.

**Comment by kball** [comment]
This is definitely a bug. The code appears to presuppose a single unchanging anchor and uses that for positioning, rather than pulling the current anchor off of the event trigger.

The fix will involve keep track of the triggering anchor and using that for positioning... @hfinnlz or @IamManchanda do either of you want to take a crack at this?
