### ISSUE TITLE
Disabled buttons with tooltip doesn't work

### ISSUE THREAD

**Issue by Vuurvlieg** [zurb/foundation-sites#9841]
When the "disabled" attribute is added to a button, the tooltip won't display (or won't display correctly).
Check [this example](https://jsfiddle.net/yfgLyp4f/)

**Comment by kball** [comment]
This is due to a browser limitation, which is then codified cross browser by jquery (see https://bugs.jquery.com/ticket/11382 and https://bugs.jquery.com/ticket/11764)

Disabled elements literally do not trigger the hover/click events, so there's no way for us to tap into them to show the tooltip.

The workaround is to remove the `disabled` attribute, just use the `disabled` class for the display properties and use JS to prevent any additional things that might get triggered (if you don't have an href or event handlers, you may not even have to do anything.)
