### ISSUE TITLE
Equalize heights of items into "rows" across multiple columns

### ISSUE THREAD

**Issue by adrianwhite** [zurb/foundation-sites#9889]
Discussion was initially on #9883 with @gpspake 

I have multiple items of differing type/category (news, events, blog posts) I want to list in columns to maintain their association. I want to add equalizer to the parent row and have the items in the columns (probably with data-equalizer-watch) have the same height as the tallest item that has the same offsetTop. Or a simpler explanation: the first items in each column have the same height, the second items in each column have the same height, and so on.

It is possible to create this functionality (and I have done so before) using nested equalizers as shown by @gpsake http://codepen.io/gpspake/pen/vxRyMV?editors=1010 but as he pointed out this quickly becomes ugly and difficult to maintain.

![screen shot 2017-03-21 at 21 13 14](https://cloud.githubusercontent.com/assets/1485452/24171156/3a273808-0e7b-11e7-9d09-03aac3fa4953.png)

Example of markup would be something like:
```
<div class="row" data-equalizer>
  <div class="medium-4 columns">
    <div class="callout" data-equalizer-watch>
      <img src= "http://foundation.zurb.com/sites/docs/assets/img/generic/square-1.jpg">
    </div>
    <div class="callout" data-equalizer-watch>
      <img src= "http://foundation.zurb.com/sites/docs/assets/img/generic/square-1.jpg">
    </div>
  </div>
  <div class="medium-4 columns">
    <div class="callout" data-equalizer-watch>
      <p>Pellentesque habitant morbi tristique senectus et netus et, ante.</p>
    </div>
    <div class="callout" data-equalizer-watch>
      <p>Pellentesque habitant morbi tristique senectus et netus et, ante.</p>
    </div>
    <div class="callout" data-equalizer-watch>
      <p>Pellentesque habitant morbi tristique senectus et netus et, ante.</p>
    </div>
  </div>
  <div class="medium-4 columns">
    <div class="callout" data-equalizer-watch>
      <img src= "http://foundation.zurb.com/sites/docs/assets/img/generic/rectangle-1.jpg">
    </div>
    <div class="callout" data-equalizer-watch>
      <img src= "http://foundation.zurb.com/sites/docs/assets/img/generic/rectangle-1.jpg">
    </div>
    <div class="callout" data-equalizer-watch>
      <img src= "http://foundation.zurb.com/sites/docs/assets/img/generic/rectangle-1.jpg">
    </div>
  </div>
</div>
```

**Comment by adrianwhite** [comment]
I have created a rather naive solution that is probably quite sub-optimal:
https://gist.github.com/adrianwhite/9e80759b9e425479e6ae00c897f48d38#file-foundation-equalizer-js-L186
This requires `data-equalize-by-row="true"` and  `data-equalize-on-stack="true"` options and probably `data-equalize-on="[breakpoint]"` if columns are stacked at smaller breakpoints as it'll run unnecessarily. The equalizable items also need `data-equalizer-watch`.

**Comment by adrianwhite** [comment]
Yeh. Ignore that Gist. It is a very silly implementation.

**Comment by gpspake** [comment]
Thoughts on this.
I believe this is a valid feature request and I can think of some good use cases for it. I also think that it's probably viable.

In the context of doing fancy stuff with equalizer, I've found that an important question to ask is "are we equalizing to a single height or Multiple heights?" Most of the time, we're going to be equalizing to a single height i.e. the tallest item being watched.
There are a couple of **cases where you equalize items to multiple heights**: 
The first, **nested equalizer**, isn't really equalizing to multiple heights as there are multiple watchers equalizing to a single height which gives the _impression_ of equalizing to multiple heights. This is the approach used above. While it appears that the first (pseudo)row is being equalized, the second (pseudo)row is being equalized etc... they really just have multiple watchers. This works great and is totally correct but it's not scalable at all. You have to add an additional equalizer container for each (pseudo) row that gets added to the columns.
*note: I'm saying _pseudo_ row because we're really talking about several distinct columns with stacked items that are equalized and give the _appearance_ of a row.

The second would be the **equalize-by-row** feature which is more in line with what we're going for here because you syntactically have one instance of equalizer that effectively equalizes to multiple heights. The reason it doesn't fit this use case is that it equalizes wrapped items in a single row - not across multiple columns.

A good first step would probably be to sketch out what the markup (the classes and data atts) would look like to equalize items across columns. Once that's relatively solid I think a lot of the equalize-by-row code could be reused.

So for example
```
<div class="row" data-equalize-columns="name">
  <div class="columns large-4" data-equalize-columns-watch="name">
    <div class="equalizer-item"></div>
    <div class="equalizer-item"></div>
  </div>
  <div class="columns large-4" data-equalize-columns-watch="name">
    <div class="equalizer-item"></div>
  </div>
  <div class="columns large-4" data-equalize-columns-watch="name">
    <div class="equalizer-item"></div>
    <div class="equalizer-item"></div>
    <div class="equalizer-item"></div>
  </div>
</div>
```
Equalizer would do the following
Count the number of items in each column
Assign an index to each item, beginning with 1, in each column
Then, equalize all items in the container with index 1, all items in the container with index 2, etc...

I'm not saying that's the correct syntax, you might even to be able to reuse some of the equalize-by-row syntax but that's what I have in mind.

**Comment by kball** [comment]
So this is interesting... does it make sense to generalize even further and have equalizer understand the concept of sets?  

This would not pre-assume you're using a grid, and also allow you to do some interesting responsive behaviors, where you e.g. only equalizing the columns on small and medium but in sub-sets on e.g. medium up.  Using the same grid example for simplicity, and tentatively borrowing from interchange for syntax, I'm imagining something-like
```
<div class="row" data-equalizer data-equalize-sets data-equalize-sets-on="[column, small], [column first second, large]">
  <div class="columns large-4" data-equalizer-watch data-equalizer-set="column">
    <div class="equalizer-item" data-equalizer-watch data-equalizer-set="first"></div>
    <div class="equalizer-item" data-equalizer-watch data-equalizer-set="second"></div>
  </div>
  <div class="columns large-4" data-equalizer-watch data-equalizer-set="column">
    <div class="equalizer-item" data-equalizer-watch data-equalizer-set="first"></div>
  </div>
  <div class="columns large-4" data-equalizer-watch data-equalizer-set="column">
    <div class="equalizer-item" data-equalizer-watch data-equalizer-set="first"></div>
    <div class="equalizer-item" data-equalizer-watch data-equalizer-set="second"></div>
    <div class="equalizer-item" data-equalizer-watch data-equalizer-set="third"></div>
  </div>
</div>
```

Does this make sense?  Thoughts?

**Comment by JeremyEnglert** [comment]
Marking this as a feature request for F7.
