### ISSUE TITLE
[Accordion] Button line incorrect

### ISSUE THREAD

**Issue by MProG** [zurb/foundation-sites#9917]
Rails 5, foundation 6.3, chrome 56.0.2924.87 (64-bit)

http://codepen.io/MProG/pen/mWQeoB

I added button grope at content
`  .accordion-content data-tab-content=''
    .button-group.tiny
      = link_to t('post.button.reject'), post_path(model, state: :rejected), method: :put, class: "button alert"
      = link_to t('post.button.read_source'), link, class: "button"`

This variant work fine. But when i want add 'float-right' class to button-group, bottom line hase incorrect place

`  .accordion-content data-tab-content=''
    .button-group.tiny.float-left
      = link_to t('post.button.reject'), post_path(model, state: :rejected), method: :put, class: "button alert"
      = link_to t('post.button.read_source'), link, class: "button"`)

**Comment by IamManchanda** [comment]
@MProG 

Please provide test case ?
Here is the codepen from which you can fork => #9827

**Comment by MProG** [comment]
@IamManchanda Sorry i cant't reproduce this bug. But found other. Incorrect bottom line http://codepen.io/MProG/pen/mWQeoB

**Comment by IamManchanda** [comment]
@MProG Solution for this is easy if you happy to use [flexbox](http://caniuse.com/#search=flexbox)
=> http://codepen.io/IamManchanda/pen/gmQXVo

Simply use `align-right` instead of `float-right` in this case

After all, browser usage of IE9 now is less than 0.25% then why not use flexbox ( https://github.com/zurb/foundation-sites/issues/9591#issuecomment-277500217 )

**Comment by MProG** [comment]
@IamManchanda Thanks

**Comment by IamManchanda** [comment]
@MProG Glad i could help you!
